// migrations — schema migrations with the `database:migrate` runner.
//
// The migrations in ./migrations/*.sql are embedded into migrations.gen.odin by
// `migragen` (see `just gen-migrations`), so this binary carries its migrations
// internally — no files to ship. We apply them to a SQLite database, print the
// status table, then roll the most recent one back.
//
// To load from disk at runtime instead, use migrate.from_dir("migrations")
// in place of the generated MIGRATIONS slice.
//
// Run: just run-example migrations
package migrations_example

import "core:fmt"

import sql "database:sql"
import migrate "database:migrate"
import sqlite "database:drivers/sqlite"

main :: proc() {
	db, open_err := sql.open(&sqlite.driver, ":memory:")
	if open_err != nil {
		fmt.eprintfln("open: %v", open_err)
		return
	}
	defer sql.close(db)

	// MIGRATIONS is the embedded slice generated by migragen from ./migrations.
	// Apply everything pending. Idempotent: safe to run on every startup.
	applied, uerr := migrate.up(db, MIGRATIONS)
	if uerr != nil {
		fmt.eprintfln("up: %v", uerr)
		return
	}
	fmt.printfln("applied %d migration(s)", applied)
	print_status(db, MIGRATIONS)

	// Roll the most recent migration back one step.
	if derr := migrate.down(db, MIGRATIONS); derr != nil {
		fmt.eprintfln("down: %v", derr)
		return
	}
	fmt.println("\nrolled back the latest migration")
	print_status(db, MIGRATIONS)
}

print_status :: proc(db: ^sql.DB, ms: []migrate.Migration) {
	st, serr := migrate.status(db, ms)
	if serr != nil {
		fmt.eprintfln("status: %v", serr)
		return
	}
	defer migrate.destroy_statuses(st)

	fmt.println("  version         name              applied")
	for s in st {
		mark := "yes" if s.applied else "no"
		fmt.printfln("  %-15d %-17s %s", s.version, s.name, mark)
	}
}
