// Code generated by tools/migragen. DO NOT EDIT.
package migrations_example

import migrate "database:migrate"

MIGRATIONS := []migrate.Migration{
	{
		version = 20260101090000,
		name    = "create_articles",
		up      = "CREATE TABLE articles (\n    id    INTEGER PRIMARY KEY,\n    title TEXT NOT NULL,\n    body  TEXT\n);\n",
		down    = "DROP TABLE articles;\n",
	},
	{
		version = 20260102090000,
		name    = "add_published",
		up      = "ALTER TABLE articles ADD COLUMN published INTEGER NOT NULL DEFAULT 0;\nCREATE INDEX idx_articles_published ON articles (published);\n",
		down    = "DROP INDEX idx_articles_published;\nALTER TABLE articles DROP COLUMN published;\n",
	},
}
