package querygen

import "core:strings"
import "core:testing"

import sql "database:sql"
import sqlite "database:drivers/sqlite"

// The committed example file, embedded at compile time so the test doesn't
// depend on the working directory.
EXAMPLE_SQL :: #load("testdata/queries.sql", string)

// --- Parsing ---

@(test)
test_parse_basic :: proc(t: ^testing.T) {
	src := `-- name: GetUser :one
-- arg: id i64
SELECT id, name FROM users WHERE id = ?;`

	specs, perr := parse_queries(src)
	defer destroy_specs(specs)

	_, has := perr.?
	testing.expect(t, !has, "no parse error")
	testing.expect_value(t, len(specs), 1)
	testing.expect_value(t, specs[0].name, "GetUser")
	testing.expect_value(t, specs[0].card, Cardinality.One)
	testing.expect_value(t, len(specs[0].args), 1)
	testing.expect_value(t, specs[0].args[0].name, "id")
	testing.expect_value(t, specs[0].args[0].type, "i64")
	testing.expect_value(t, specs[0].sql, "SELECT id, name FROM users WHERE id = ?")
}

@(test)
test_parse_placeholder_mismatch :: proc(t: ^testing.T) {
	src := `-- name: Bad :exec
-- arg: id i64
INSERT INTO users (a, b) VALUES (?, ?);`

	specs, perr := parse_queries(src)
	defer destroy_specs(specs)

	pe, has := perr.?
	testing.expect(t, has, "expected a parse error")
	testing.expect(t, strings.contains(pe.msg, "2 placeholder"), "names the mismatch")
}

// --- Dialects ---

@(test)
test_parse_postgres_dollar :: proc(t: ^testing.T) {
	src := `-- name: GetUser :one
-- arg: id i64
-- arg: min_age i64
SELECT id, name FROM users WHERE id = $1 AND age >= $2;`

	specs, perr := parse_queries(src, .Dollar)
	defer destroy_specs(specs)

	_, has := perr.?
	testing.expect(t, !has, "postgres dialect parses $N")
	testing.expect_value(t, len(specs), 1)
	testing.expect_value(t, len(specs[0].args), 2)
}

@(test)
test_parse_postgres_rejects_question :: proc(t: ^testing.T) {
	src := `-- name: Bad :one
-- arg: id i64
SELECT id FROM users WHERE id = ?;`

	specs, perr := parse_queries(src, .Dollar)
	defer destroy_specs(specs)

	_, has := perr.?
	testing.expect(t, has, "? is rejected under the postgres dialect")
}

@(test)
test_count_placeholders_dollar_uses_max_index :: proc(t: ^testing.T) {
	// $1 is reused; the parameter count is the highest index (2), not the
	// number of occurrences (3).
	n, bad := count_placeholders("SELECT * FROM t WHERE a = $1 AND b = $2 OR c = $1", .Dollar)
	testing.expect(t, !bad, "no unexpected placeholder")
	testing.expect_value(t, n, 2)
}

@(test)
test_parse_rejects_dollar_placeholder :: proc(t: ^testing.T) {
	src := `-- name: Bad :one
-- arg: id i64
SELECT id FROM users WHERE id = $1;`

	specs, perr := parse_queries(src)
	defer destroy_specs(specs)

	_, has := perr.?
	testing.expect(t, has, "expected error for $1 placeholder")
}

@(test)
test_count_placeholders_skips_literals_and_comments :: proc(t: ^testing.T) {
	// Only the final `?` is a real parameter; the others are inside a string
	// literal, a quoted identifier, a line comment and a block comment.
	n, bad := count_placeholders(
		"SELECT '?', \"a?b\" /* ? */ FROM t -- ?\nWHERE x = ?",
	)
	testing.expect(t, !bad, "no unsupported placeholder")
	testing.expect_value(t, n, 1)
}

// --- Describe + emit (end-to-end against an in-memory SQLite schema) ---

@(test)
test_describe_and_emit :: proc(t: ^testing.T) {
	db, oerr := sql.open(&sqlite.driver, ":memory:")
	testing.expect_value(t, oerr, nil)
	defer sql.close(db)
	sql.set_max_open_conns(db, 1)

	_, cerr := sql.exec(
		db,
		"CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, email TEXT, age INTEGER)",
	)
	testing.expect_value(t, cerr, nil)

	specs, perr := parse_queries(EXAMPLE_SQL)
	defer destroy_specs(specs)
	_, has := perr.?
	testing.expect(t, !has, "example parses cleanly")
	testing.expect_value(t, len(specs), 4)

	derr := describe(db, specs[:])
	testing.expect_value(t, derr, "")

	// GetUserByID :one → id i64, name string, email string
	get := specs[0]
	testing.expect_value(t, get.name, "GetUserByID")
	testing.expect_value(t, len(get.results), 3)
	testing.expect_value(t, get.results[0].name, "id")
	testing.expect_value(t, get.results[0].type, "i64")
	testing.expect_value(t, get.results[1].name, "name")
	testing.expect_value(t, get.results[1].type, "string")
	testing.expect_value(t, get.results[2].name, "email")
	testing.expect_value(t, get.results[2].type, "string")

	// :exec queries get no result columns.
	testing.expect_value(t, len(specs[2].results), 0)

	out := emit("myapp", specs[:])
	defer delete(out)

	want := []string {
		"// Code generated by tools/querygen. DO NOT EDIT.",
		"package myapp",
		"import sql \"database:sql\"",
		"GetUserByID_sql :: \"SELECT id, name, email FROM users WHERE id = ?\"",
		"GetUserByIDRow :: struct {",
		"GetUserByID :: proc(db: ^sql.DB, id: i64, loc := #caller_location) -> (GetUserByIDRow, sql.Error)",
		"row := sql.query_row(db, GetUserByID_sql, id, loc = loc)",
		"err := sql.scan(&row, &out.id, &out.name, &out.email)",
		"ListUsersByAge :: proc(db: ^sql.DB, min_age: i64, allocator := context.allocator, loc := #caller_location) -> ([]ListUsersByAgeRow, sql.Error)",
		"CreateUser :: proc(db: ^sql.DB, name: string, email: string, age: i64, loc := #caller_location) -> (sql.Result, sql.Error)",
		"return sql.exec(db, CreateUser_sql, name, email, age, loc = loc)",
	}
	for w in want {
		testing.expectf(t, strings.contains(out, w), "expected emitted code to contain:\n%s", w)
	}
}

@(test)
test_describe_errors_on_untyped_expression :: proc(t: ^testing.T) {
	db, oerr := sql.open(&sqlite.driver, ":memory:")
	testing.expect_value(t, oerr, nil)
	defer sql.close(db)
	sql.set_max_open_conns(db, 1)

	_, cerr := sql.exec(db, "CREATE TABLE users (id INTEGER)")
	testing.expect_value(t, cerr, nil)

	// COUNT(*) has no declared type in SQLite → describe must reject it.
	specs, perr := parse_queries("-- name: CountUsers :one\nSELECT count(*) FROM users;")
	defer destroy_specs(specs)
	_, has := perr.?
	testing.expect(t, !has, "parses ok")

	derr := describe(db, specs[:])
	testing.expect(t, derr != "", "describe should fail on an untyped expression column")
	testing.expect(t, strings.contains(derr, "cannot infer"), "explains the failure")
}
