// Code generated by tools/scangen. DO NOT EDIT.
package main

import "base:intrinsics"
import "core:strings"
import "core:time"
import sql "database:sql"

scan_User :: proc(rows: ^sql.Rows, dest: ^User, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1, ctx = {query = rows.query, loc = loc}}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "age":
			if v, ok := val.(i64); ok { dest.age = int(v) }
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		}
	}
	return nil
}

scan_User_row :: proc(row: ^sql.Row, dest: ^User, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_User(&row.rows, dest, loc)
}

scan :: proc{
	scan_User,
	scan_User_row,
	sql.scan_values,
	sql.row_scan_values,
	_scan_no_generated_scanner,
	_row_scan_no_generated_scanner,
}

@(private)
_scan_no_generated_scanner :: proc(rows: ^sql.Rows, dest: ^$T, loc := #caller_location) -> sql.Error
	where intrinsics.type_is_struct(T), T != time.Time, T != User {
	#assert(false, "no generated scanner for this struct — annotate it with //+sql:scan and re-run scangen, or call sql.scan_struct / sql.row_scan_struct for explicit reflection")
	return nil
}

@(private)
_row_scan_no_generated_scanner :: proc(row: ^sql.Row, dest: ^$T, loc := #caller_location) -> sql.Error
	where intrinsics.type_is_struct(T), T != time.Time, T != User {
	#assert(false, "no generated scanner for this struct — annotate it with //+sql:scan and re-run scangen, or call sql.scan_struct / sql.row_scan_struct for explicit reflection")
	return nil
}
