// Code generated by tools/schemagen. DO NOT EDIT.
package main

import "core:time"
import sb "database:sqlbuilder"

Users := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	name: sb.Column(string),
	age: sb.Column(int),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "users"},
	id = {base = {table = "users", name = "id", type_id = i64}},
	name = {base = {table = "users", name = "name", type_id = string}},
	age = {base = {table = "users", name = "age", type_id = int}},
	created_at = {base = {table = "users", name = "created_at", type_id = time.Time}},
}

