// Code generated by tools/querygen. DO NOT EDIT.
package queries

import sql "database:sql"

CreateUser_sql :: "INSERT INTO users (name, email, age) VALUES (?, ?, ?)"

CreateUser :: proc(db: ^sql.DB, name: string, email: string, age: i64, loc := #caller_location) -> (sql.Result, sql.Error) {
	return sql.exec(db, CreateUser_sql, name, email, age, loc = loc)
}

GetUserByID_sql :: "SELECT id, name, email, age FROM users WHERE id = ?"

GetUserByIDRow :: struct {
	id: i64,
	name: string,
	email: string,
	age: i64,
}

GetUserByID :: proc(db: ^sql.DB, id: i64, loc := #caller_location) -> (GetUserByIDRow, sql.Error) {
	row := sql.query_row(db, GetUserByID_sql, id, loc = loc)
	defer sql.close_row(&row)
	out: GetUserByIDRow
	err := sql.scan(&row, &out.id, &out.name, &out.email, &out.age)
	return out, err
}

ListUsersByMinAge_sql :: "SELECT id, name, age FROM users WHERE age >= ? ORDER BY name"

ListUsersByMinAgeRow :: struct {
	id: i64,
	name: string,
	age: i64,
}

ListUsersByMinAge :: proc(db: ^sql.DB, min_age: i64, allocator := context.allocator, loc := #caller_location) -> ([]ListUsersByMinAgeRow, sql.Error) {
	rows, qerr := sql.query(db, ListUsersByMinAge_sql, min_age, loc = loc)
	if qerr != nil {
		return nil, qerr
	}
	defer sql.rows_close(&rows)
	out := make([dynamic]ListUsersByMinAgeRow, allocator)
	for sql.next(&rows) {
		r: ListUsersByMinAgeRow
		if serr := sql.scan(&rows, &r.id, &r.name, &r.age); serr != nil {
			delete(out)
			return nil, serr
		}
		append(&out, r)
	}
	if rerr := sql.rows_err(&rows); rerr != nil {
		delete(out)
		return nil, rerr
	}
	return out[:], nil
}
