// ss — a smoke test for schemagen output against a real PostgreSQL database.
//
// schema.gen.odin / scan.gen.odin in this package were generated by
// introspecting a large production-shaped postgres schema. This program proves
// the generated descriptors actually drive a working query: it loads connection
// settings from ss/.env, opens the postgres driver, and runs a typed
// query-builder SELECT against the generated `Studies` descriptor, scanning rows
// into the generated `Study` struct.
//
// Setup:
//   cp examples/ss/.env.example examples/ss/.env   # then edit with your connection
// Run:
//   just run-ss   # or: odin run examples/ss -collection:database=. -out:bin/ss
//
// A mistyped column (e.g. Studies.naem) won't compile — that's the whole point.
package ss

import "core:fmt"
import "core:os"
import "core:strings"

import pg "database:drivers/postgres"
import sql "database:sql"
import sb "database:sqlbuilder"

// load_env reads a KEY=VALUE file (".env" style) into a map. Blank lines and
// lines beginning with '#' are skipped; surrounding quotes on the value are
// stripped. Returns an empty map if the file is missing. Allocated in the temp
// allocator — the keys/values borrow the file buffer, also temp-allocated.
load_env :: proc(path: string, allocator := context.temp_allocator) -> map[string]string {
	env := make(map[string]string, allocator)
	data, err := os.read_entire_file(path, allocator)
	if err != nil {
		return env
	}
	text := string(data)
	for line in strings.split_lines_iterator(&text) {
		trimmed := strings.trim_space(line)
		if trimmed == "" || strings.has_prefix(trimmed, "#") {
			continue
		}
		eq := strings.index_byte(trimmed, '=')
		if eq < 0 {
			continue
		}
		key := strings.trim_space(trimmed[:eq])
		val := strings.trim_space(trimmed[eq + 1:])
		val = strings.trim(val, "\"'")
		env[key] = val
	}
	return env
}

// get returns env[key], falling back to the process environment, then to def.
get :: proc(env: map[string]string, key, def: string) -> string {
	if v, ok := env[key]; ok && v != "" {
		return v
	}
	if v, ok := os.lookup_env(key, context.temp_allocator); ok && v != "" {
		return v
	}
	return def
}

// build_dsn returns DATABASE_URL verbatim if set, otherwise assembles a
// postgres:// URL from the individual PG* fields.
build_dsn :: proc(env: map[string]string) -> string {
	if url := get(env, "DATABASE_URL", ""); url != "" {
		return url
	}
	host := get(env, "PGHOST", "localhost")
	port := get(env, "PGPORT", "5432")
	user := get(env, "PGUSER", "postgres")
	pass := get(env, "PGPASSWORD", "postgres")
	db := get(env, "PGDATABASE", "postgres")
	mode := get(env, "PGSSLMODE", "disable")
	return fmt.tprintf("postgres://%s:%s@%s:%s/%s?sslmode=%s", user, pass, host, port, db, mode)
}

main :: proc() {
	env := load_env("examples/ss/.env")
	dsn := build_dsn(env)

	db, oerr := sql.open(&pg.driver, dsn)
	if oerr != nil {
		fmt.eprintfln("open postgres: %v", oerr)
		fmt.eprintln("  (check ss/.env — copy ss/.env.example and fill it in)")
		os.exit(1)
	}
	defer sql.close(db)

	if perr := sql.ping(db); perr != nil {
		fmt.eprintfln("ping: %v", perr)
		os.exit(1)
	}
	fmt.println("connected.")

	// Typed SELECT against the generated `Studies` descriptor. Columns are
	// checked at compile time; the `?` placeholder is translated to `$1` by the
	// postgres driver.
	b: sb.Builder
	sb.init(&b)
	defer sb.destroy(&b)

	sb.select(&b, Studies.id, Studies.name, Studies.url, Studies.rate_limit)
	sb.from(&b, Studies)
	sb.where_(&b, sb.is_not_null(Studies.name))
	sb.order_by(&b, sb.asc(Studies.name))
	// sb.limit(&b, 5)

	q, args := sb.to_query(&b)
	fmt.printfln("sql: %s", q)

	rows, qerr := sql.query(db, q, ..args)
	if qerr != nil {
		fmt.eprintfln("query: %v", qerr)
		os.exit(1)
	}
	defer sql.rows_close(&rows)

	n := 0
	for sql.next(&rows) {
		s: Study // generated row struct
		if serr := scan(&rows, &s); serr != nil { 	// concrete scan_Study from scangen
			fmt.eprintfln("scan: %v", serr)
			os.exit(1)
		}
		url := s.url.? or_else "(null)"
		rate := s.rate_limit.? or_else 0
		fmt.printfln("  id=%v  name=%q  url=%v  rate_limit=%v", s.id, s.name, url, rate)
		n += 1
	}
	// next() returns false for BOTH a clean end-of-rows and a mid-stream failure
	// (a dropped connection, a statement timeout, a server error on row N), so
	// check rows_err afterward — otherwise a truncated result looks complete.
	if rerr := sql.rows_err(&rows); rerr != nil {
		fmt.eprintfln("result truncated mid-stream after %d row(s): %v", n, rerr)
		os.exit(1)
	}
	fmt.printfln("%d row(s).", n)
}
