// Code generated by tools/scangen. DO NOT EDIT.
package ss

import "core:strings"
import "core:time"
import sql "database:sql"

scan_AlertRule :: proc(rows: ^sql.Rows, dest: ^AlertRule) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "task_version_id":
			if v, ok := val.(string); ok {
				dest.task_version_id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "logic":
			if v, ok := val.(string); ok {
				dest.logic = v if detached else strings.clone(v)
			}
		case "deleted_at":
			if v, ok := val.(time.Time); ok {dest.deleted_at = v}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "priority":
			if v, ok := val.(i64); ok {dest.priority = i64(v)}
		case "stop_on_match":
			#partial switch x in val {
			case bool:
				dest.stop_on_match = x
			case i64:
				dest.stop_on_match = x != 0
			}
		}
	}
	return nil
}

scan_Alert :: proc(rows: ^sql.Rows, dest: ^Alert) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "message":
			if v, ok := val.(string); ok {
				dest.message = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "rule_id":
			if v, ok := val.(string); ok {
				dest.rule_id = v if detached else strings.clone(v)
			}
		case "send_email":
			#partial switch x in val {
			case bool:
				dest.send_email = x
			case i64:
				dest.send_email = x != 0
			}
		}
	}
	return nil
}

scan_AvailablePlugin :: proc(rows: ^sql.Rows, dest: ^AvailablePlugin) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "default_config":
			if v, ok := val.(string); ok {
				dest.default_config = v if detached else strings.clone(v)
			}
		case "type":
			if v, ok := val.(string); ok {
				dest.type = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ContactPurpose_Row :: proc(rows: ^sql.Rows, dest: ^ContactPurpose_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_Device :: proc(rows: ^sql.Rows, dest: ^Device) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "metadata":
			if v, ok := val.(string); ok {
				dest.metadata = v if detached else strings.clone(v)
			}
		case "firebase_token":
			if v, ok := val.(string); ok {
				dest.firebase_token = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "device_id":
			if v, ok := val.(string); ok {
				dest.device_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_EventRule :: proc(rows: ^sql.Rows, dest: ^EventRule) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "logic":
			if v, ok := val.(string); ok {
				dest.logic = v if detached else strings.clone(v)
			}
		case "deleted_at":
			if v, ok := val.(time.Time); ok {dest.deleted_at = v}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "priority":
			if v, ok := val.(i64); ok {dest.priority = i64(v)}
		case "stop_on_match":
			#partial switch x in val {
			case bool:
				dest.stop_on_match = x
			case i64:
				dest.stop_on_match = x != 0
			}
		case "action":
			if v, ok := val.(string); ok {
				dest.action = v if detached else strings.clone(v)
			}
		case "wave_id":
			if v, ok := val.(string); ok {
				dest.wave_id = v if detached else strings.clone(v)
			}
		case "task_group_id":
			if v, ok := val.(string); ok {
				dest.task_group_id = v if detached else strings.clone(v)
			}
		case "participant_tag_id":
			if v, ok := val.(string); ok {
				dest.participant_tag_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_FeatureSet_Row :: proc(rows: ^sql.Rows, dest: ^FeatureSet_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		}
	}
	return nil
}

scan_Job :: proc(rows: ^sql.Rows, dest: ^Job) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "status":
			if v, ok := val.(string); ok {
				dest.status = v if detached else strings.clone(v)
			}
		case "progress":
			if v, ok := val.(i64); ok {dest.progress = i64(v)}
		case "payload":
			if v, ok := val.(string); ok {
				dest.payload = v if detached else strings.clone(v)
			}
		case "current_retry":
			if v, ok := val.(i64); ok {dest.current_retry = i64(v)}
		case "started_at":
			if v, ok := val.(time.Time); ok {dest.started_at = v}
		case "finished_at":
			if v, ok := val.(time.Time); ok {dest.finished_at = v}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "study_plugin_id":
			if v, ok := val.(string); ok {
				dest.study_plugin_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_LiveStudy :: proc(rows: ^sql.Rows, dest: ^LiveStudy) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		}
	}
	return nil
}

scan_ParticipantArchive_Row :: proc(rows: ^sql.Rows, dest: ^ParticipantArchive_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "archived_at":
			if v, ok := val.(time.Time); ok {dest.archived_at = v}
		case "archived_by":
			if v, ok := val.(string); ok {
				dest.archived_by = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		}
	}
	return nil
}

scan_ParticipantDevice :: proc(rows: ^sql.Rows, dest: ^ParticipantDevice) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "device_id":
			if v, ok := val.(string); ok {
				dest.device_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		}
	}
	return nil
}

scan_ParticipantLog_Row :: proc(rows: ^sql.Rows, dest: ^ParticipantLog_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "message":
			if v, ok := val.(string); ok {
				dest.message = v if detached else strings.clone(v)
			}
		case "tag":
			if v, ok := val.(string); ok {
				dest.tag = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		}
	}
	return nil
}

scan_ParticipantNotification :: proc(
	rows: ^sql.Rows,
	dest: ^ParticipantNotification,
) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "sent_by":
			if v, ok := val.(string); ok {
				dest.sent_by = v if detached else strings.clone(v)
			}
		case "message":
			if v, ok := val.(string); ok {
				dest.message = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "delivered_at":
			if v, ok := val.(time.Time); ok {dest.delivered_at = v}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "extra_data":
			if v, ok := val.(string); ok {
				dest.extra_data = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ParticipantPin :: proc(rows: ^sql.Rows, dest: ^ParticipantPin) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "pin":
			if v, ok := val.(string); ok {
				dest.pin = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		}
	}
	return nil
}

scan_ParticipantProgressShim_Row :: proc(
	rows: ^sql.Rows,
	dest: ^ParticipantProgressShim_Row,
) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "wave_order":
			if v, ok := val.(i64); ok {dest.wave_order = i64(v)}
		case "last_completed_response_date":
			if v, ok := val.(time.Time); ok {dest.last_completed_response_date = v}
		case "last_delivery_time":
			if v, ok := val.(time.Time); ok {dest.last_delivery_time = v}
		case "total_deliveries":
			if v, ok := val.(i64); ok {dest.total_deliveries = i64(v)}
		case "completed_deliveries":
			if v, ok := val.(i64); ok {dest.completed_deliveries = i64(v)}
		case "completed_streak":
			if v, ok := val.(i64); ok {dest.completed_streak = i64(v)}
		}
	}
	return nil
}

scan_ParticipantTag :: proc(rows: ^sql.Rows, dest: ^ParticipantTag) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "tag":
			if v, ok := val.(string); ok {
				dest.tag = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "color":
			if v, ok := val.(string); ok {
				dest.color = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ParticipantWaveOffset :: proc(rows: ^sql.Rows, dest: ^ParticipantWaveOffset) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "wave_id":
			if v, ok := val.(string); ok {
				dest.wave_id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "offset_days":
			if v, ok := val.(i64); ok {dest.offset_days = i64(v)}
		}
	}
	return nil
}

scan_Participant :: proc(rows: ^sql.Rows, dest: ^Participant) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "key":
			if v, ok := val.(string); ok {
				dest.key = v if detached else strings.clone(v)
			}
		case "participant_tag_id":
			if v, ok := val.(string); ok {
				dest.participant_tag_id = v if detached else strings.clone(v)
			}
		case "enrolled_at":
			if v, ok := val.(time.Time); ok {dest.enrolled_at = v}
		case "metadata":
			if v, ok := val.(string); ok {
				dest.metadata = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_PluginType :: proc(rows: ^sql.Rows, dest: ^PluginType) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ResponseJob :: proc(rows: ^sql.Rows, dest: ^ResponseJob) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "job_id":
			if v, ok := val.(string); ok {
				dest.job_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ResponseStatsShim_Row :: proc(rows: ^sql.Rows, dest: ^ResponseStatsShim_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "wave_id":
			if v, ok := val.(string); ok {
				dest.wave_id = v if detached else strings.clone(v)
			}
		case "task_group_id":
			if v, ok := val.(string); ok {
				dest.task_group_id = v if detached else strings.clone(v)
			}
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "completed":
			#partial switch x in val {
			case bool:
				dest.completed = x
			case i64:
				dest.completed = x != 0
			}
		case "completed_count":
			if v, ok := val.(i64); ok {dest.completed_count = i64(v)}
		case "missed_count":
			if v, ok := val.(i64); ok {dest.missed_count = i64(v)}
		case "total_count":
			if v, ok := val.(i64); ok {dest.total_count = i64(v)}
		case "streak":
			if v, ok := val.(i64); ok {dest.streak = i64(v)}
		}
	}
	return nil
}

scan_ResponseTranscription :: proc(rows: ^sql.Rows, dest: ^ResponseTranscription) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "question_id":
			if v, ok := val.(string); ok {
				dest.question_id = v if detached else strings.clone(v)
			}
		case "transcription":
			if v, ok := val.(string); ok {
				dest.transcription = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		}
	}
	return nil
}

scan_Respons :: proc(rows: ^sql.Rows, dest: ^Respons) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "delivery_id":
			if v, ok := val.(string); ok {
				dest.delivery_id = v if detached else strings.clone(v)
			}
		case "completed":
			#partial switch x in val {
			case bool:
				dest.completed = x
			case i64:
				dest.completed = x != 0
			}
		case "task_answers":
			if v, ok := val.([]byte); ok {
				if detached {
					dest.task_answers = v
				} else {
					cp := make([]byte, len(v));copy(cp, v);dest.task_answers = cp
				}
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "task_version_id":
			if v, ok := val.(string); ok {
				dest.task_version_id = v if detached else strings.clone(v)
			}
		case "answers":
			if v, ok := val.(string); ok {
				dest.answers = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_Role :: proc(rows: ^sql.Rows, dest: ^Role) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "parent_role_id":
			if v, ok := val.(string); ok {
				dest.parent_role_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		}
	}
	return nil
}

scan_Study :: proc(rows: ^sql.Rows, dest: ^Study) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "url":
			if v, ok := val.(string); ok {
				dest.url = v if detached else strings.clone(v)
			}
		case "banner_img_url":
			if v, ok := val.(string); ok {
				dest.banner_img_url = v if detached else strings.clone(v)
			}
		case "theme_color":
			if v, ok := val.(string); ok {
				dest.theme_color = v if detached else strings.clone(v)
			}
		case "icon_img_url":
			if v, ok := val.(string); ok {
				dest.icon_img_url = v if detached else strings.clone(v)
			}
		case "description":
			if v, ok := val.(string); ok {
				dest.description = v if detached else strings.clone(v)
			}
		case "rate_limit":
			if v, ok := val.(i64); ok {dest.rate_limit = i64(v)}
		case "api_secret":
			if v, ok := val.(string); ok {
				dest.api_secret = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "team_id":
			if v, ok := val.(string); ok {
				dest.team_id = v if detached else strings.clone(v)
			}
		case "use_pii_passphrase":
			#partial switch x in val {
			case bool:
				dest.use_pii_passphrase = x
			case i64:
				dest.use_pii_passphrase = x != 0
			}
		case "export_folder_id":
			if v, ok := val.(string); ok {
				dest.export_folder_id = v if detached else strings.clone(v)
			}
		case "theme_color_dark":
			if v, ok := val.(string); ok {
				dest.theme_color_dark = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyContact :: proc(rows: ^sql.Rows, dest: ^StudyContact) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "email":
			if v, ok := val.(string); ok {
				dest.email = v if detached else strings.clone(v)
			}
		case "purpose":
			if v, ok := val.(string); ok {
				dest.purpose = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyEncryptionsKey :: proc(rows: ^sql.Rows, dest: ^StudyEncryptionsKey) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "key":
			if v, ok := val.(string); ok {
				dest.key = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		}
	}
	return nil
}

scan_StudyExpectation :: proc(rows: ^sql.Rows, dest: ^StudyExpectation) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "icon":
			if v, ok := val.(string); ok {
				dest.icon = v if detached else strings.clone(v)
			}
		case "label":
			if v, ok := val.(string); ok {
				dest.label = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyPlugin :: proc(rows: ^sql.Rows, dest: ^StudyPlugin) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "plugin_type":
			if v, ok := val.(string); ok {
				dest.plugin_type = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "config":
			if v, ok := val.(string); ok {
				dest.config = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "private_config":
			if v, ok := val.(string); ok {
				dest.private_config = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyTranslation :: proc(rows: ^sql.Rows, dest: ^StudyTranslation) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "translations":
			if v, ok := val.(string); ok {
				dest.translations = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "locks":
			if v, ok := val.(string); ok {
				dest.locks = v if detached else strings.clone(v)
			}
		case "proper_nouns":
			if v, ok := val.(string); ok {
				dest.proper_nouns = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyUserFeature :: proc(rows: ^sql.Rows, dest: ^StudyUserFeature) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "feature_set":
			if v, ok := val.(string); ok {
				dest.feature_set = v if detached else strings.clone(v)
			}
		case "user_id":
			if v, ok := val.(string); ok {
				dest.user_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyUser :: proc(rows: ^sql.Rows, dest: ^StudyUser) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "user_id":
			if v, ok := val.(string); ok {
				dest.user_id = v if detached else strings.clone(v)
			}
		case "role_id":
			if v, ok := val.(string); ok {
				dest.role_id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_SurveyDailyCount :: proc(rows: ^sql.Rows, dest: ^SurveyDailyCount) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "day":
			if v, ok := val.(time.Time); ok {dest.day = v}
		case "participant_tag_id":
			if v, ok := val.(string); ok {
				dest.participant_tag_id = v if detached else strings.clone(v)
			}
		case "response_count":
			if v, ok := val.(i64); ok {dest.response_count = i64(v)}
		case "completed_count":
			if v, ok := val.(i64); ok {dest.completed_count = i64(v)}
		}
	}
	return nil
}

scan_TangoAccount_Row :: proc(rows: ^sql.Rows, dest: ^TangoAccount_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "customer_id":
			if v, ok := val.(string); ok {
				dest.customer_id = v if detached else strings.clone(v)
			}
		case "account_id":
			if v, ok := val.(string); ok {
				dest.account_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "balance":
			#partial switch v in val {
			case f64:
				dest.balance = v
			case i64:
				dest.balance = f64(v)
			}
		}
	}
	return nil
}

scan_TangoAccountFund :: proc(rows: ^sql.Rows, dest: ^TangoAccountFund) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "amount":
			#partial switch v in val {
			case f64:
				dest.amount = v
			case i64:
				dest.amount = f64(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "note":
			if v, ok := val.(string); ok {
				dest.note = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_TangoOrder_Row :: proc(rows: ^sql.Rows, dest: ^TangoOrder_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "tango_reference_order_id":
			if v, ok := val.(string); ok {
				dest.tango_reference_order_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "amount":
			#partial switch v in val {
			case f64:
				dest.amount = v
			case i64:
				dest.amount = f64(v)
			}
		case "redemption_url":
			if v, ok := val.(string); ok {
				dest.redemption_url = v if detached else strings.clone(v)
			}
		case "tango_details":
			if v, ok := val.(string); ok {
				dest.tango_details = v if detached else strings.clone(v)
			}
		case "is_redeemed":
			#partial switch x in val {
			case bool:
				dest.is_redeemed = x
			case i64:
				dest.is_redeemed = x != 0
			}
		case "redemption_history":
			if v, ok := val.(string); ok {
				dest.redemption_history = v if detached else strings.clone(v)
			}
		case "tango_account_id":
			if v, ok := val.(string); ok {
				dest.tango_account_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_TaskGroup :: proc(rows: ^sql.Rows, dest: ^TaskGroup) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "title":
			if v, ok := val.(string); ok {
				dest.title = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "task_type":
			if v, ok := val.(string); ok {
				dest.task_type = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_TaskVersion :: proc(rows: ^sql.Rows, dest: ^TaskVersion) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "task_data":
			if v, ok := val.(string); ok {
				dest.task_data = v if detached else strings.clone(v)
			}
		case "task_group_id":
			if v, ok := val.(string); ok {
				dest.task_group_id = v if detached else strings.clone(v)
			}
		case "note":
			if v, ok := val.(string); ok {
				dest.note = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "publish_at":
			if v, ok := val.(time.Time); ok {dest.publish_at = v}
		}
	}
	return nil
}

scan_TremendousOrder_Row :: proc(rows: ^sql.Rows, dest: ^TremendousOrder_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "payload":
			if v, ok := val.(string); ok {
				dest.payload = v if detached else strings.clone(v)
			}
		case "event_rule_id":
			if v, ok := val.(string); ok {
				dest.event_rule_id = v if detached else strings.clone(v)
			}
		case "manually_triggered_by":
			if v, ok := val.(string); ok {
				dest.manually_triggered_by = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "status":
			if v, ok := val.(string); ok {
				dest.status = v if detached else strings.clone(v)
			}
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "redeemed_at":
			if v, ok := val.(time.Time); ok {dest.redeemed_at = v}
		case "order_type":
			if v, ok := val.(string); ok {
				dest.order_type = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_TremendousOrg_Row :: proc(rows: ^sql.Rows, dest: ^TremendousOrg_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "status":
			if v, ok := val.(string); ok {
				dest.status = v if detached else strings.clone(v)
			}
		case "api_key":
			if v, ok := val.(string); ok {
				dest.api_key = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		}
	}
	return nil
}

scan_UserToken :: proc(rows: ^sql.Rows, dest: ^UserToken) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "email":
			if v, ok := val.(string); ok {
				dest.email = v if detached else strings.clone(v)
			}
		case "type":
			if v, ok := val.(string); ok {
				dest.type = v if detached else strings.clone(v)
			}
		case "token":
			if v, ok := val.(string); ok {
				dest.token = v if detached else strings.clone(v)
			}
		case "used":
			#partial switch x in val {
			case bool:
				dest.used = x
			case i64:
				dest.used = x != 0
			}
		case "expires":
			if v, ok := val.(time.Time); ok {dest.expires = v}
		}
	}
	return nil
}

scan_User :: proc(rows: ^sql.Rows, dest: ^User) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "first_name":
			if v, ok := val.(string); ok {
				dest.first_name = v if detached else strings.clone(v)
			}
		case "last_name":
			if v, ok := val.(string); ok {
				dest.last_name = v if detached else strings.clone(v)
			}
		case "email":
			if v, ok := val.(string); ok {
				dest.email = v if detached else strings.clone(v)
			}
		case "password":
			if v, ok := val.(string); ok {
				dest.password = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "admin":
			#partial switch x in val {
			case bool:
				dest.admin = x
			case i64:
				dest.admin = x != 0
			}
		case "verified":
			#partial switch x in val {
			case bool:
				dest.verified = x
			case i64:
				dest.verified = x != 0
			}
		}
	}
	return nil
}

scan_WaveTaskDelivery :: proc(rows: ^sql.Rows, dest: ^WaveTaskDelivery) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "wave_task_id":
			if v, ok := val.(string); ok {
				dest.wave_task_id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "delivery_time":
			if v, ok := val.(time.Time); ok {dest.delivery_time = v}
		case "start":
			if v, ok := val.(time.Time); ok {dest.start = v}
		case "end":
			if v, ok := val.(time.Time); ok {dest.end = v}
		case "wave_order":
			if v, ok := val.(i64); ok {dest.wave_order = i64(v)}
		case "delivery_order":
			if v, ok := val.(i64); ok {dest.delivery_order = i64(v)}
		case "deleted":
			#partial switch x in val {
			case bool:
				dest.deleted = x
			case i64:
				dest.deleted = x != 0
			}
		}
	}
	return nil
}

scan_WaveTask :: proc(rows: ^sql.Rows, dest: ^WaveTask) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "wave_id":
			if v, ok := val.(string); ok {
				dest.wave_id = v if detached else strings.clone(v)
			}
		case "task_group_id":
			if v, ok := val.(string); ok {
				dest.task_group_id = v if detached else strings.clone(v)
			}
		case "participant_tag_id":
			if v, ok := val.(string); ok {
				dest.participant_tag_id = v if detached else strings.clone(v)
			}
		case "rrule_string":
			if v, ok := val.(string); ok {
				dest.rrule_string = v if detached else strings.clone(v)
			}
		case "allow_multiple_submissions":
			#partial switch x in val {
			case bool:
				dest.allow_multiple_submissions = x
			case i64:
				dest.allow_multiple_submissions = x != 0
			}
		case "duration_minutes":
			if v, ok := val.(i64); ok {dest.duration_minutes = i64(v)}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "local_notifications":
			if v, ok := val.(string); ok {
				dest.local_notifications = v if detached else strings.clone(v)
			}
		case "day_offset":
			if v, ok := val.(i64); ok {dest.day_offset = i64(v)}
		}
	}
	return nil
}

scan_Wave :: proc(rows: ^sql.Rows, dest: ^Wave) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "duration_days":
			if v, ok := val.(i64); ok {dest.duration_days = i64(v)}
		case "order":
			if v, ok := val.(i64); ok {dest.order = i64(v)}
		case "rrule_string":
			if v, ok := val.(string); ok {
				dest.rrule_string = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok {dest.created_at = v}
		case "updated_at":
			if v, ok := val.(time.Time); ok {dest.updated_at = v}
		case "dynamic_start":
			#partial switch x in val {
			case bool:
				dest.dynamic_start = x
			case i64:
				dest.dynamic_start = x != 0
			}
		}
	}
	return nil
}

scan :: proc {
	scan_AlertRule,
	scan_Alert,
	scan_AvailablePlugin,
	scan_ContactPurpose_Row,
	scan_Device,
	scan_EventRule,
	scan_FeatureSet_Row,
	scan_Job,
	scan_LiveStudy,
	scan_ParticipantArchive_Row,
	scan_ParticipantDevice,
	scan_ParticipantLog_Row,
	scan_ParticipantNotification,
	scan_ParticipantPin,
	scan_ParticipantProgressShim_Row,
	scan_ParticipantTag,
	scan_ParticipantWaveOffset,
	scan_Participant,
	scan_PluginType,
	scan_ResponseJob,
	scan_ResponseStatsShim_Row,
	scan_ResponseTranscription,
	scan_Respons,
	scan_Role,
	scan_Study,
	scan_StudyContact,
	scan_StudyEncryptionsKey,
	scan_StudyExpectation,
	scan_StudyPlugin,
	scan_StudyTranslation,
	scan_StudyUserFeature,
	scan_StudyUser,
	scan_SurveyDailyCount,
	scan_TangoAccount_Row,
	scan_TangoAccountFund,
	scan_TangoOrder_Row,
	scan_TaskGroup,
	scan_TaskVersion,
	scan_TremendousOrder_Row,
	scan_TremendousOrg_Row,
	scan_UserToken,
	scan_User,
	scan_WaveTaskDelivery,
	scan_WaveTask,
	scan_Wave,
	sql.scan_struct,
	sql.scan_values,
	sql.row_scan_struct,
	sql.row_scan_values,
}
