// Code generated by tools/scangen. DO NOT EDIT.
package ss

import "base:intrinsics"
import "core:strings"
import "core:time"
import sql "database:sql"

scan_AlertRule :: proc(rows: ^sql.Rows, dest: ^AlertRule, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "task_version_id":
			if v, ok := val.(string); ok {
				dest.task_version_id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "logic":
			if v, ok := val.(string); ok {
				dest.logic = v if detached else strings.clone(v)
			}
		case "deleted_at":
			if v, ok := val.(time.Time); ok { dest.deleted_at = v }
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "priority":
			if v, ok := val.(i64); ok { dest.priority = i64(v) }
		case "stop_on_match":
			#partial switch x in val {
			case bool: dest.stop_on_match = x
			case i64:  dest.stop_on_match = x != 0
			}
		}
	}
	return nil
}

scan_AlertRule_row :: proc(row: ^sql.Row, dest: ^AlertRule, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_AlertRule(&row.rows, dest, loc)
}

scan_Alert :: proc(rows: ^sql.Rows, dest: ^Alert, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "message":
			if v, ok := val.(string); ok {
				dest.message = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "rule_id":
			if v, ok := val.(string); ok {
				dest.rule_id = v if detached else strings.clone(v)
			}
		case "send_email":
			#partial switch x in val {
			case bool: dest.send_email = x
			case i64:  dest.send_email = x != 0
			}
		}
	}
	return nil
}

scan_Alert_row :: proc(row: ^sql.Row, dest: ^Alert, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_Alert(&row.rows, dest, loc)
}

scan_AvailablePlugin :: proc(rows: ^sql.Rows, dest: ^AvailablePlugin, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "default_config":
			if v, ok := val.(string); ok {
				dest.default_config = v if detached else strings.clone(v)
			}
		case "type":
			if v, ok := val.(string); ok {
				dest.type = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_AvailablePlugin_row :: proc(row: ^sql.Row, dest: ^AvailablePlugin, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_AvailablePlugin(&row.rows, dest, loc)
}

scan_ContactPurpose_Row :: proc(rows: ^sql.Rows, dest: ^ContactPurpose_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ContactPurpose_Row_row :: proc(row: ^sql.Row, dest: ^ContactPurpose_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ContactPurpose_Row(&row.rows, dest, loc)
}

scan_Device :: proc(rows: ^sql.Rows, dest: ^Device, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "metadata":
			if v, ok := val.(string); ok {
				dest.metadata = v if detached else strings.clone(v)
			}
		case "firebase_token":
			if v, ok := val.(string); ok {
				dest.firebase_token = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "device_id":
			if v, ok := val.(string); ok {
				dest.device_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_Device_row :: proc(row: ^sql.Row, dest: ^Device, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_Device(&row.rows, dest, loc)
}

scan_EventRule :: proc(rows: ^sql.Rows, dest: ^EventRule, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "logic":
			if v, ok := val.(string); ok {
				dest.logic = v if detached else strings.clone(v)
			}
		case "deleted_at":
			if v, ok := val.(time.Time); ok { dest.deleted_at = v }
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "priority":
			if v, ok := val.(i64); ok { dest.priority = i64(v) }
		case "stop_on_match":
			#partial switch x in val {
			case bool: dest.stop_on_match = x
			case i64:  dest.stop_on_match = x != 0
			}
		case "action":
			if v, ok := val.(string); ok {
				dest.action = v if detached else strings.clone(v)
			}
		case "wave_id":
			if v, ok := val.(string); ok {
				dest.wave_id = v if detached else strings.clone(v)
			}
		case "task_group_id":
			if v, ok := val.(string); ok {
				dest.task_group_id = v if detached else strings.clone(v)
			}
		case "participant_tag_id":
			if v, ok := val.(string); ok {
				dest.participant_tag_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_EventRule_row :: proc(row: ^sql.Row, dest: ^EventRule, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_EventRule(&row.rows, dest, loc)
}

scan_FeatureSet_Row :: proc(rows: ^sql.Rows, dest: ^FeatureSet_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		}
	}
	return nil
}

scan_FeatureSet_Row_row :: proc(row: ^sql.Row, dest: ^FeatureSet_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_FeatureSet_Row(&row.rows, dest, loc)
}

scan_Job :: proc(rows: ^sql.Rows, dest: ^Job, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "status":
			if v, ok := val.(string); ok {
				dest.status = v if detached else strings.clone(v)
			}
		case "progress":
			if v, ok := val.(i64); ok { dest.progress = i64(v) }
		case "payload":
			if v, ok := val.(string); ok {
				dest.payload = v if detached else strings.clone(v)
			}
		case "current_retry":
			if v, ok := val.(i64); ok { dest.current_retry = i64(v) }
		case "started_at":
			if v, ok := val.(time.Time); ok { dest.started_at = v }
		case "finished_at":
			if v, ok := val.(time.Time); ok { dest.finished_at = v }
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "study_plugin_id":
			if v, ok := val.(string); ok {
				dest.study_plugin_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_Job_row :: proc(row: ^sql.Row, dest: ^Job, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_Job(&row.rows, dest, loc)
}

scan_LiveStudy :: proc(rows: ^sql.Rows, dest: ^LiveStudy, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		}
	}
	return nil
}

scan_LiveStudy_row :: proc(row: ^sql.Row, dest: ^LiveStudy, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_LiveStudy(&row.rows, dest, loc)
}

scan_ParticipantArchive_Row :: proc(rows: ^sql.Rows, dest: ^ParticipantArchive_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "archived_at":
			if v, ok := val.(time.Time); ok { dest.archived_at = v }
		case "archived_by":
			if v, ok := val.(string); ok {
				dest.archived_by = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "source":
			if v, ok := val.(string); ok {
				dest.source = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ParticipantArchive_Row_row :: proc(row: ^sql.Row, dest: ^ParticipantArchive_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ParticipantArchive_Row(&row.rows, dest, loc)
}

scan_ParticipantDevice :: proc(rows: ^sql.Rows, dest: ^ParticipantDevice, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "device_id":
			if v, ok := val.(string); ok {
				dest.device_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		}
	}
	return nil
}

scan_ParticipantDevice_row :: proc(row: ^sql.Row, dest: ^ParticipantDevice, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ParticipantDevice(&row.rows, dest, loc)
}

scan_ParticipantLog_Row :: proc(rows: ^sql.Rows, dest: ^ParticipantLog_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "message":
			if v, ok := val.(string); ok {
				dest.message = v if detached else strings.clone(v)
			}
		case "tag":
			if v, ok := val.(string); ok {
				dest.tag = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		}
	}
	return nil
}

scan_ParticipantLog_Row_row :: proc(row: ^sql.Row, dest: ^ParticipantLog_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ParticipantLog_Row(&row.rows, dest, loc)
}

scan_ParticipantNotification :: proc(rows: ^sql.Rows, dest: ^ParticipantNotification, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "sent_by":
			if v, ok := val.(string); ok {
				dest.sent_by = v if detached else strings.clone(v)
			}
		case "message":
			if v, ok := val.(string); ok {
				dest.message = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "delivered_at":
			if v, ok := val.(time.Time); ok { dest.delivered_at = v }
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "extra_data":
			if v, ok := val.(string); ok {
				dest.extra_data = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ParticipantNotification_row :: proc(row: ^sql.Row, dest: ^ParticipantNotification, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ParticipantNotification(&row.rows, dest, loc)
}

scan_ParticipantPin :: proc(rows: ^sql.Rows, dest: ^ParticipantPin, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "pin":
			if v, ok := val.(string); ok {
				dest.pin = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		}
	}
	return nil
}

scan_ParticipantPin_row :: proc(row: ^sql.Row, dest: ^ParticipantPin, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ParticipantPin(&row.rows, dest, loc)
}

scan_ParticipantProgressShim_Row :: proc(rows: ^sql.Rows, dest: ^ParticipantProgressShim_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "wave_order":
			if v, ok := val.(i64); ok { dest.wave_order = i64(v) }
		case "last_completed_response_date":
			if v, ok := val.(time.Time); ok { dest.last_completed_response_date = v }
		case "last_delivery_time":
			if v, ok := val.(time.Time); ok { dest.last_delivery_time = v }
		case "total_deliveries":
			if v, ok := val.(i64); ok { dest.total_deliveries = i64(v) }
		case "completed_deliveries":
			if v, ok := val.(i64); ok { dest.completed_deliveries = i64(v) }
		case "completed_streak":
			if v, ok := val.(i64); ok { dest.completed_streak = i64(v) }
		}
	}
	return nil
}

scan_ParticipantProgressShim_Row_row :: proc(row: ^sql.Row, dest: ^ParticipantProgressShim_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ParticipantProgressShim_Row(&row.rows, dest, loc)
}

scan_ParticipantTag :: proc(rows: ^sql.Rows, dest: ^ParticipantTag, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "tag":
			if v, ok := val.(string); ok {
				dest.tag = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "color":
			if v, ok := val.(string); ok {
				dest.color = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ParticipantTag_row :: proc(row: ^sql.Row, dest: ^ParticipantTag, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ParticipantTag(&row.rows, dest, loc)
}

scan_ParticipantWaveOffset :: proc(rows: ^sql.Rows, dest: ^ParticipantWaveOffset, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "wave_id":
			if v, ok := val.(string); ok {
				dest.wave_id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "offset_days":
			if v, ok := val.(i64); ok { dest.offset_days = i64(v) }
		}
	}
	return nil
}

scan_ParticipantWaveOffset_row :: proc(row: ^sql.Row, dest: ^ParticipantWaveOffset, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ParticipantWaveOffset(&row.rows, dest, loc)
}

scan_Participant :: proc(rows: ^sql.Rows, dest: ^Participant, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "key":
			if v, ok := val.(string); ok {
				dest.key = v if detached else strings.clone(v)
			}
		case "participant_tag_id":
			if v, ok := val.(string); ok {
				dest.participant_tag_id = v if detached else strings.clone(v)
			}
		case "enrolled_at":
			if v, ok := val.(time.Time); ok { dest.enrolled_at = v }
		case "metadata":
			if v, ok := val.(string); ok {
				dest.metadata = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_Participant_row :: proc(row: ^sql.Row, dest: ^Participant, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_Participant(&row.rows, dest, loc)
}

scan_PluginType :: proc(rows: ^sql.Rows, dest: ^PluginType, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_PluginType_row :: proc(row: ^sql.Row, dest: ^PluginType, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_PluginType(&row.rows, dest, loc)
}

scan_ResponseJob :: proc(rows: ^sql.Rows, dest: ^ResponseJob, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "job_id":
			if v, ok := val.(string); ok {
				dest.job_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_ResponseJob_row :: proc(row: ^sql.Row, dest: ^ResponseJob, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ResponseJob(&row.rows, dest, loc)
}

scan_ResponseStatsShim_Row :: proc(rows: ^sql.Rows, dest: ^ResponseStatsShim_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "wave_id":
			if v, ok := val.(string); ok {
				dest.wave_id = v if detached else strings.clone(v)
			}
		case "task_group_id":
			if v, ok := val.(string); ok {
				dest.task_group_id = v if detached else strings.clone(v)
			}
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "completed":
			#partial switch x in val {
			case bool: dest.completed = x
			case i64:  dest.completed = x != 0
			}
		case "completed_count":
			if v, ok := val.(i64); ok { dest.completed_count = i64(v) }
		case "missed_count":
			if v, ok := val.(i64); ok { dest.missed_count = i64(v) }
		case "total_count":
			if v, ok := val.(i64); ok { dest.total_count = i64(v) }
		case "streak":
			if v, ok := val.(i64); ok { dest.streak = i64(v) }
		}
	}
	return nil
}

scan_ResponseStatsShim_Row_row :: proc(row: ^sql.Row, dest: ^ResponseStatsShim_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ResponseStatsShim_Row(&row.rows, dest, loc)
}

scan_ResponseTranscription :: proc(rows: ^sql.Rows, dest: ^ResponseTranscription, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "question_id":
			if v, ok := val.(string); ok {
				dest.question_id = v if detached else strings.clone(v)
			}
		case "transcription":
			if v, ok := val.(string); ok {
				dest.transcription = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		}
	}
	return nil
}

scan_ResponseTranscription_row :: proc(row: ^sql.Row, dest: ^ResponseTranscription, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_ResponseTranscription(&row.rows, dest, loc)
}

scan_Respons :: proc(rows: ^sql.Rows, dest: ^Respons, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "delivery_id":
			if v, ok := val.(string); ok {
				dest.delivery_id = v if detached else strings.clone(v)
			}
		case "completed":
			#partial switch x in val {
			case bool: dest.completed = x
			case i64:  dest.completed = x != 0
			}
		case "task_answers":
			if v, ok := val.([]byte); ok {
				if detached {
					dest.task_answers = v
				} else {
					cp := make([]byte, len(v)); copy(cp, v); dest.task_answers = cp
				}
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "task_version_id":
			if v, ok := val.(string); ok {
				dest.task_version_id = v if detached else strings.clone(v)
			}
		case "answers":
			if v, ok := val.(string); ok {
				dest.answers = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_Respons_row :: proc(row: ^sql.Row, dest: ^Respons, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_Respons(&row.rows, dest, loc)
}

scan_Role :: proc(rows: ^sql.Rows, dest: ^Role, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "parent_role_id":
			if v, ok := val.(string); ok {
				dest.parent_role_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		}
	}
	return nil
}

scan_Role_row :: proc(row: ^sql.Row, dest: ^Role, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_Role(&row.rows, dest, loc)
}

scan_Study :: proc(rows: ^sql.Rows, dest: ^Study, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "url":
			if v, ok := val.(string); ok {
				dest.url = v if detached else strings.clone(v)
			}
		case "banner_img_url":
			if v, ok := val.(string); ok {
				dest.banner_img_url = v if detached else strings.clone(v)
			}
		case "theme_color":
			if v, ok := val.(string); ok {
				dest.theme_color = v if detached else strings.clone(v)
			}
		case "icon_img_url":
			if v, ok := val.(string); ok {
				dest.icon_img_url = v if detached else strings.clone(v)
			}
		case "description":
			if v, ok := val.(string); ok {
				dest.description = v if detached else strings.clone(v)
			}
		case "rate_limit":
			if v, ok := val.(i64); ok { dest.rate_limit = i64(v) }
		case "api_secret":
			if v, ok := val.(string); ok {
				dest.api_secret = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "team_id":
			if v, ok := val.(string); ok {
				dest.team_id = v if detached else strings.clone(v)
			}
		case "use_pii_passphrase":
			#partial switch x in val {
			case bool: dest.use_pii_passphrase = x
			case i64:  dest.use_pii_passphrase = x != 0
			}
		case "export_folder_id":
			if v, ok := val.(string); ok {
				dest.export_folder_id = v if detached else strings.clone(v)
			}
		case "theme_color_dark":
			if v, ok := val.(string); ok {
				dest.theme_color_dark = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_Study_row :: proc(row: ^sql.Row, dest: ^Study, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_Study(&row.rows, dest, loc)
}

scan_StudyContact :: proc(rows: ^sql.Rows, dest: ^StudyContact, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "email":
			if v, ok := val.(string); ok {
				dest.email = v if detached else strings.clone(v)
			}
		case "purpose":
			if v, ok := val.(string); ok {
				dest.purpose = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyContact_row :: proc(row: ^sql.Row, dest: ^StudyContact, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_StudyContact(&row.rows, dest, loc)
}

scan_StudyEncryptionsKey :: proc(rows: ^sql.Rows, dest: ^StudyEncryptionsKey, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "key":
			if v, ok := val.(string); ok {
				dest.key = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		}
	}
	return nil
}

scan_StudyEncryptionsKey_row :: proc(row: ^sql.Row, dest: ^StudyEncryptionsKey, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_StudyEncryptionsKey(&row.rows, dest, loc)
}

scan_StudyExpectation :: proc(rows: ^sql.Rows, dest: ^StudyExpectation, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "icon":
			if v, ok := val.(string); ok {
				dest.icon = v if detached else strings.clone(v)
			}
		case "label":
			if v, ok := val.(string); ok {
				dest.label = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyExpectation_row :: proc(row: ^sql.Row, dest: ^StudyExpectation, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_StudyExpectation(&row.rows, dest, loc)
}

scan_StudyPlugin :: proc(rows: ^sql.Rows, dest: ^StudyPlugin, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "plugin_type":
			if v, ok := val.(string); ok {
				dest.plugin_type = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "config":
			if v, ok := val.(string); ok {
				dest.config = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "private_config":
			if v, ok := val.(string); ok {
				dest.private_config = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyPlugin_row :: proc(row: ^sql.Row, dest: ^StudyPlugin, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_StudyPlugin(&row.rows, dest, loc)
}

scan_StudyTranslation :: proc(rows: ^sql.Rows, dest: ^StudyTranslation, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "translations":
			if v, ok := val.(string); ok {
				dest.translations = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "locks":
			if v, ok := val.(string); ok {
				dest.locks = v if detached else strings.clone(v)
			}
		case "proper_nouns":
			if v, ok := val.(string); ok {
				dest.proper_nouns = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyTranslation_row :: proc(row: ^sql.Row, dest: ^StudyTranslation, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_StudyTranslation(&row.rows, dest, loc)
}

scan_StudyUserFeature :: proc(rows: ^sql.Rows, dest: ^StudyUserFeature, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "feature_set":
			if v, ok := val.(string); ok {
				dest.feature_set = v if detached else strings.clone(v)
			}
		case "user_id":
			if v, ok := val.(string); ok {
				dest.user_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyUserFeature_row :: proc(row: ^sql.Row, dest: ^StudyUserFeature, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_StudyUserFeature(&row.rows, dest, loc)
}

scan_StudyUser :: proc(rows: ^sql.Rows, dest: ^StudyUser, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "user_id":
			if v, ok := val.(string); ok {
				dest.user_id = v if detached else strings.clone(v)
			}
		case "role_id":
			if v, ok := val.(string); ok {
				dest.role_id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_StudyUser_row :: proc(row: ^sql.Row, dest: ^StudyUser, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_StudyUser(&row.rows, dest, loc)
}

scan_SurveyDailyCount :: proc(rows: ^sql.Rows, dest: ^SurveyDailyCount, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "day":
			if v, ok := val.(time.Time); ok { dest.day = v }
		case "participant_tag_id":
			if v, ok := val.(string); ok {
				dest.participant_tag_id = v if detached else strings.clone(v)
			}
		case "response_count":
			if v, ok := val.(i64); ok { dest.response_count = i64(v) }
		case "completed_count":
			if v, ok := val.(i64); ok { dest.completed_count = i64(v) }
		}
	}
	return nil
}

scan_SurveyDailyCount_row :: proc(row: ^sql.Row, dest: ^SurveyDailyCount, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_SurveyDailyCount(&row.rows, dest, loc)
}

scan_TangoAccount_Row :: proc(rows: ^sql.Rows, dest: ^TangoAccount_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "customer_id":
			if v, ok := val.(string); ok {
				dest.customer_id = v if detached else strings.clone(v)
			}
		case "account_id":
			if v, ok := val.(string); ok {
				dest.account_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "balance":
			#partial switch v in val {
			case f64: dest.balance = v
			case i64: dest.balance = f64(v)
			}
		}
	}
	return nil
}

scan_TangoAccount_Row_row :: proc(row: ^sql.Row, dest: ^TangoAccount_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_TangoAccount_Row(&row.rows, dest, loc)
}

scan_TangoAccountFund :: proc(rows: ^sql.Rows, dest: ^TangoAccountFund, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "amount":
			#partial switch v in val {
			case f64: dest.amount = v
			case i64: dest.amount = f64(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "note":
			if v, ok := val.(string); ok {
				dest.note = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_TangoAccountFund_row :: proc(row: ^sql.Row, dest: ^TangoAccountFund, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_TangoAccountFund(&row.rows, dest, loc)
}

scan_TangoOrder_Row :: proc(rows: ^sql.Rows, dest: ^TangoOrder_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "tango_reference_order_id":
			if v, ok := val.(string); ok {
				dest.tango_reference_order_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "amount":
			#partial switch v in val {
			case f64: dest.amount = v
			case i64: dest.amount = f64(v)
			}
		case "redemption_url":
			if v, ok := val.(string); ok {
				dest.redemption_url = v if detached else strings.clone(v)
			}
		case "tango_details":
			if v, ok := val.(string); ok {
				dest.tango_details = v if detached else strings.clone(v)
			}
		case "is_redeemed":
			#partial switch x in val {
			case bool: dest.is_redeemed = x
			case i64:  dest.is_redeemed = x != 0
			}
		case "redemption_history":
			if v, ok := val.(string); ok {
				dest.redemption_history = v if detached else strings.clone(v)
			}
		case "tango_account_id":
			if v, ok := val.(string); ok {
				dest.tango_account_id = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_TangoOrder_Row_row :: proc(row: ^sql.Row, dest: ^TangoOrder_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_TangoOrder_Row(&row.rows, dest, loc)
}

scan_TaskGroup :: proc(rows: ^sql.Rows, dest: ^TaskGroup, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "title":
			if v, ok := val.(string); ok {
				dest.title = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "task_type":
			if v, ok := val.(string); ok {
				dest.task_type = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_TaskGroup_row :: proc(row: ^sql.Row, dest: ^TaskGroup, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_TaskGroup(&row.rows, dest, loc)
}

scan_TaskVersion :: proc(rows: ^sql.Rows, dest: ^TaskVersion, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "task_data":
			if v, ok := val.(string); ok {
				dest.task_data = v if detached else strings.clone(v)
			}
		case "task_group_id":
			if v, ok := val.(string); ok {
				dest.task_group_id = v if detached else strings.clone(v)
			}
		case "note":
			if v, ok := val.(string); ok {
				dest.note = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "publish_at":
			if v, ok := val.(time.Time); ok { dest.publish_at = v }
		}
	}
	return nil
}

scan_TaskVersion_row :: proc(row: ^sql.Row, dest: ^TaskVersion, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_TaskVersion(&row.rows, dest, loc)
}

scan_TremendousOrder_Row :: proc(rows: ^sql.Rows, dest: ^TremendousOrder_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "payload":
			if v, ok := val.(string); ok {
				dest.payload = v if detached else strings.clone(v)
			}
		case "event_rule_id":
			if v, ok := val.(string); ok {
				dest.event_rule_id = v if detached else strings.clone(v)
			}
		case "manually_triggered_by":
			if v, ok := val.(string); ok {
				dest.manually_triggered_by = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "status":
			if v, ok := val.(string); ok {
				dest.status = v if detached else strings.clone(v)
			}
		case "response_id":
			if v, ok := val.(string); ok {
				dest.response_id = v if detached else strings.clone(v)
			}
		case "redeemed_at":
			if v, ok := val.(time.Time); ok { dest.redeemed_at = v }
		case "order_type":
			if v, ok := val.(string); ok {
				dest.order_type = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_TremendousOrder_Row_row :: proc(row: ^sql.Row, dest: ^TremendousOrder_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_TremendousOrder_Row(&row.rows, dest, loc)
}

scan_TremendousOrg_Row :: proc(rows: ^sql.Rows, dest: ^TremendousOrg_Row, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "status":
			if v, ok := val.(string); ok {
				dest.status = v if detached else strings.clone(v)
			}
		case "api_key":
			if v, ok := val.(string); ok {
				dest.api_key = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		}
	}
	return nil
}

scan_TremendousOrg_Row_row :: proc(row: ^sql.Row, dest: ^TremendousOrg_Row, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_TremendousOrg_Row(&row.rows, dest, loc)
}

scan_UserToken :: proc(rows: ^sql.Rows, dest: ^UserToken, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "email":
			if v, ok := val.(string); ok {
				dest.email = v if detached else strings.clone(v)
			}
		case "type":
			if v, ok := val.(string); ok {
				dest.type = v if detached else strings.clone(v)
			}
		case "token":
			if v, ok := val.(string); ok {
				dest.token = v if detached else strings.clone(v)
			}
		case "used":
			#partial switch x in val {
			case bool: dest.used = x
			case i64:  dest.used = x != 0
			}
		case "expires":
			if v, ok := val.(time.Time); ok { dest.expires = v }
		}
	}
	return nil
}

scan_UserToken_row :: proc(row: ^sql.Row, dest: ^UserToken, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_UserToken(&row.rows, dest, loc)
}

scan_User :: proc(rows: ^sql.Rows, dest: ^User, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "first_name":
			if v, ok := val.(string); ok {
				dest.first_name = v if detached else strings.clone(v)
			}
		case "last_name":
			if v, ok := val.(string); ok {
				dest.last_name = v if detached else strings.clone(v)
			}
		case "email":
			if v, ok := val.(string); ok {
				dest.email = v if detached else strings.clone(v)
			}
		case "password":
			if v, ok := val.(string); ok {
				dest.password = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "admin":
			#partial switch x in val {
			case bool: dest.admin = x
			case i64:  dest.admin = x != 0
			}
		case "verified":
			#partial switch x in val {
			case bool: dest.verified = x
			case i64:  dest.verified = x != 0
			}
		}
	}
	return nil
}

scan_User_row :: proc(row: ^sql.Row, dest: ^User, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_User(&row.rows, dest, loc)
}

scan_WaveTaskDelivery :: proc(rows: ^sql.Rows, dest: ^WaveTaskDelivery, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "wave_task_id":
			if v, ok := val.(string); ok {
				dest.wave_task_id = v if detached else strings.clone(v)
			}
		case "participant_id":
			if v, ok := val.(string); ok {
				dest.participant_id = v if detached else strings.clone(v)
			}
		case "delivery_time":
			if v, ok := val.(time.Time); ok { dest.delivery_time = v }
		case "start":
			if v, ok := val.(time.Time); ok { dest.start = v }
		case "end":
			if v, ok := val.(time.Time); ok { dest.end = v }
		case "wave_order":
			if v, ok := val.(i64); ok { dest.wave_order = i64(v) }
		case "delivery_order":
			if v, ok := val.(i64); ok { dest.delivery_order = i64(v) }
		case "deleted":
			#partial switch x in val {
			case bool: dest.deleted = x
			case i64:  dest.deleted = x != 0
			}
		}
	}
	return nil
}

scan_WaveTaskDelivery_row :: proc(row: ^sql.Row, dest: ^WaveTaskDelivery, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_WaveTaskDelivery(&row.rows, dest, loc)
}

scan_WaveTask :: proc(rows: ^sql.Rows, dest: ^WaveTask, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "wave_id":
			if v, ok := val.(string); ok {
				dest.wave_id = v if detached else strings.clone(v)
			}
		case "task_group_id":
			if v, ok := val.(string); ok {
				dest.task_group_id = v if detached else strings.clone(v)
			}
		case "participant_tag_id":
			if v, ok := val.(string); ok {
				dest.participant_tag_id = v if detached else strings.clone(v)
			}
		case "rrule_string":
			if v, ok := val.(string); ok {
				dest.rrule_string = v if detached else strings.clone(v)
			}
		case "allow_multiple_submissions":
			#partial switch x in val {
			case bool: dest.allow_multiple_submissions = x
			case i64:  dest.allow_multiple_submissions = x != 0
			}
		case "duration_minutes":
			if v, ok := val.(i64); ok { dest.duration_minutes = i64(v) }
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "local_notifications":
			if v, ok := val.(string); ok {
				dest.local_notifications = v if detached else strings.clone(v)
			}
		case "day_offset":
			if v, ok := val.(i64); ok { dest.day_offset = i64(v) }
		}
	}
	return nil
}

scan_WaveTask_row :: proc(row: ^sql.Row, dest: ^WaveTask, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_WaveTask(&row.rows, dest, loc)
}

scan_Wave :: proc(rows: ^sql.Rows, dest: ^Wave, loc := #caller_location) -> sql.Error {
	if !rows.has_row {
		return sql.General_Error.No_Row
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "study_id":
			if v, ok := val.(string); ok {
				dest.study_id = v if detached else strings.clone(v)
			}
		case "duration_days":
			if v, ok := val.(i64); ok { dest.duration_days = i64(v) }
		case "order":
			if v, ok := val.(i64); ok { dest.order = i64(v) }
		case "rrule_string":
			if v, ok := val.(string); ok {
				dest.rrule_string = v if detached else strings.clone(v)
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		case "updated_at":
			if v, ok := val.(time.Time); ok { dest.updated_at = v }
		case "dynamic_start":
			#partial switch x in val {
			case bool: dest.dynamic_start = x
			case i64:  dest.dynamic_start = x != 0
			}
		}
	}
	return nil
}

scan_Wave_row :: proc(row: ^sql.Row, dest: ^Wave, loc := #caller_location) -> sql.Error {
	if row.err != nil {
		return row.err
	}
	return scan_Wave(&row.rows, dest, loc)
}

scan :: proc{
	scan_AlertRule,
	scan_AlertRule_row,
	scan_Alert,
	scan_Alert_row,
	scan_AvailablePlugin,
	scan_AvailablePlugin_row,
	scan_ContactPurpose_Row,
	scan_ContactPurpose_Row_row,
	scan_Device,
	scan_Device_row,
	scan_EventRule,
	scan_EventRule_row,
	scan_FeatureSet_Row,
	scan_FeatureSet_Row_row,
	scan_Job,
	scan_Job_row,
	scan_LiveStudy,
	scan_LiveStudy_row,
	scan_ParticipantArchive_Row,
	scan_ParticipantArchive_Row_row,
	scan_ParticipantDevice,
	scan_ParticipantDevice_row,
	scan_ParticipantLog_Row,
	scan_ParticipantLog_Row_row,
	scan_ParticipantNotification,
	scan_ParticipantNotification_row,
	scan_ParticipantPin,
	scan_ParticipantPin_row,
	scan_ParticipantProgressShim_Row,
	scan_ParticipantProgressShim_Row_row,
	scan_ParticipantTag,
	scan_ParticipantTag_row,
	scan_ParticipantWaveOffset,
	scan_ParticipantWaveOffset_row,
	scan_Participant,
	scan_Participant_row,
	scan_PluginType,
	scan_PluginType_row,
	scan_ResponseJob,
	scan_ResponseJob_row,
	scan_ResponseStatsShim_Row,
	scan_ResponseStatsShim_Row_row,
	scan_ResponseTranscription,
	scan_ResponseTranscription_row,
	scan_Respons,
	scan_Respons_row,
	scan_Role,
	scan_Role_row,
	scan_Study,
	scan_Study_row,
	scan_StudyContact,
	scan_StudyContact_row,
	scan_StudyEncryptionsKey,
	scan_StudyEncryptionsKey_row,
	scan_StudyExpectation,
	scan_StudyExpectation_row,
	scan_StudyPlugin,
	scan_StudyPlugin_row,
	scan_StudyTranslation,
	scan_StudyTranslation_row,
	scan_StudyUserFeature,
	scan_StudyUserFeature_row,
	scan_StudyUser,
	scan_StudyUser_row,
	scan_SurveyDailyCount,
	scan_SurveyDailyCount_row,
	scan_TangoAccount_Row,
	scan_TangoAccount_Row_row,
	scan_TangoAccountFund,
	scan_TangoAccountFund_row,
	scan_TangoOrder_Row,
	scan_TangoOrder_Row_row,
	scan_TaskGroup,
	scan_TaskGroup_row,
	scan_TaskVersion,
	scan_TaskVersion_row,
	scan_TremendousOrder_Row,
	scan_TremendousOrder_Row_row,
	scan_TremendousOrg_Row,
	scan_TremendousOrg_Row_row,
	scan_UserToken,
	scan_UserToken_row,
	scan_User,
	scan_User_row,
	scan_WaveTaskDelivery,
	scan_WaveTaskDelivery_row,
	scan_WaveTask,
	scan_WaveTask_row,
	scan_Wave,
	scan_Wave_row,
	sql.scan_values,
	sql.row_scan_values,
	_scan_no_generated_scanner,
	_row_scan_no_generated_scanner,
}

@(private)
_scan_no_generated_scanner :: proc(rows: ^sql.Rows, dest: ^$T, loc := #caller_location) -> sql.Error
	where intrinsics.type_is_struct(T), T != time.Time, T != AlertRule, T != Alert, T != AvailablePlugin, T != ContactPurpose_Row, T != Device, T != EventRule, T != FeatureSet_Row, T != Job, T != LiveStudy, T != ParticipantArchive_Row, T != ParticipantDevice, T != ParticipantLog_Row, T != ParticipantNotification, T != ParticipantPin, T != ParticipantProgressShim_Row, T != ParticipantTag, T != ParticipantWaveOffset, T != Participant, T != PluginType, T != ResponseJob, T != ResponseStatsShim_Row, T != ResponseTranscription, T != Respons, T != Role, T != Study, T != StudyContact, T != StudyEncryptionsKey, T != StudyExpectation, T != StudyPlugin, T != StudyTranslation, T != StudyUserFeature, T != StudyUser, T != SurveyDailyCount, T != TangoAccount_Row, T != TangoAccountFund, T != TangoOrder_Row, T != TaskGroup, T != TaskVersion, T != TremendousOrder_Row, T != TremendousOrg_Row, T != UserToken, T != User, T != WaveTaskDelivery, T != WaveTask, T != Wave {
	#assert(false, "no generated scanner for this struct — annotate it with //+sql:scan and re-run scangen, or call sql.scan_struct / sql.row_scan_struct for explicit reflection")
	return nil
}

@(private)
_row_scan_no_generated_scanner :: proc(row: ^sql.Row, dest: ^$T, loc := #caller_location) -> sql.Error
	where intrinsics.type_is_struct(T), T != time.Time, T != AlertRule, T != Alert, T != AvailablePlugin, T != ContactPurpose_Row, T != Device, T != EventRule, T != FeatureSet_Row, T != Job, T != LiveStudy, T != ParticipantArchive_Row, T != ParticipantDevice, T != ParticipantLog_Row, T != ParticipantNotification, T != ParticipantPin, T != ParticipantProgressShim_Row, T != ParticipantTag, T != ParticipantWaveOffset, T != Participant, T != PluginType, T != ResponseJob, T != ResponseStatsShim_Row, T != ResponseTranscription, T != Respons, T != Role, T != Study, T != StudyContact, T != StudyEncryptionsKey, T != StudyExpectation, T != StudyPlugin, T != StudyTranslation, T != StudyUserFeature, T != StudyUser, T != SurveyDailyCount, T != TangoAccount_Row, T != TangoAccountFund, T != TangoOrder_Row, T != TaskGroup, T != TaskVersion, T != TremendousOrder_Row, T != TremendousOrg_Row, T != UserToken, T != User, T != WaveTaskDelivery, T != WaveTask, T != Wave {
	#assert(false, "no generated scanner for this struct — annotate it with //+sql:scan and re-run scangen, or call sql.scan_struct / sql.row_scan_struct for explicit reflection")
	return nil
}
