// Code generated by tools/schemagen. DO NOT EDIT.
package ss

import "core:time"
import sb "database:sqlbuilder"

//+sql:scan
AlertRule :: struct {
	id: string,
	task_version_id: string,
	name: string,
	logic: string,
	deleted_at: Maybe(time.Time),
	created_at: time.Time,
	priority: i64,
	stop_on_match: bool,
}

//+sql:scan
Alert :: struct {
	id: string,
	study_id: string,
	response_id: string,
	message: string,
	created_at: Maybe(time.Time),
	rule_id: string,
	send_email: Maybe(bool),
}

//+sql:scan
AvailablePlugin :: struct {
	name: string,
	default_config: string,
	type: string,
}

//+sql:scan
ContactPurpose_Row :: struct {
	name: string,
}

//+sql:scan
Device :: struct {
	id: string,
	name: string,
	metadata: string,
	firebase_token: string,
	created_at: Maybe(time.Time),
	updated_at: Maybe(time.Time),
	device_id: Maybe(string),
}

//+sql:scan
EventRule :: struct {
	id: string,
	study_id: string,
	name: string,
	logic: string,
	deleted_at: Maybe(time.Time),
	created_at: time.Time,
	priority: i64,
	stop_on_match: bool,
	action: string,
	wave_id: Maybe(string),
	task_group_id: Maybe(string),
	participant_tag_id: Maybe(string),
}

//+sql:scan
FeatureSet_Row :: struct {
	name: string,
	created_at: time.Time,
}

//+sql:scan
Job :: struct {
	id: string,
	status: string,
	progress: i64,
	payload: string,
	current_retry: i64,
	started_at: Maybe(time.Time),
	finished_at: Maybe(time.Time),
	created_at: time.Time,
	updated_at: time.Time,
	name: string,
	study_plugin_id: string,
}

//+sql:scan
LiveStudy :: struct {
	study_id: string,
	created_at: time.Time,
}

//+sql:scan
ParticipantArchive_Row :: struct {
	id: string,
	participant_id: string,
	archived_at: Maybe(time.Time),
	archived_by: string,
	created_at: Maybe(time.Time),
}

//+sql:scan
ParticipantDevice :: struct {
	id: string,
	participant_id: string,
	device_id: string,
	created_at: Maybe(time.Time),
}

//+sql:scan
ParticipantLog_Row :: struct {
	id: string,
	participant_id: string,
	message: string,
	tag: string,
	created_at: Maybe(time.Time),
}

//+sql:scan
ParticipantNotification :: struct {
	id: string,
	sent_by: Maybe(string),
	message: string,
	created_at: time.Time,
	delivered_at: Maybe(time.Time),
	participant_id: string,
	extra_data: Maybe(string),
}

//+sql:scan
ParticipantPin :: struct {
	pin: string,
	participant_id: string,
	study_id: string,
	created_at: time.Time,
}

//+sql:scan
ParticipantProgressShim_Row :: struct {
	study_id: Maybe(string),
	participant_id: Maybe(string),
	wave_order: Maybe(i64),
	last_completed_response_date: Maybe(time.Time),
	last_delivery_time: Maybe(time.Time),
	total_deliveries: Maybe(i64),
	completed_deliveries: Maybe(i64),
	completed_streak: Maybe(i64),
}

//+sql:scan
ParticipantTag :: struct {
	id: string,
	study_id: string,
	tag: string,
	created_at: Maybe(time.Time),
	updated_at: Maybe(time.Time),
	color: Maybe(string),
}

//+sql:scan
ParticipantWaveOffset :: struct {
	id: string,
	wave_id: string,
	participant_id: string,
	offset_days: i64,
}

//+sql:scan
Participant :: struct {
	id: string,
	study_id: string,
	key: string,
	participant_tag_id: Maybe(string),
	enrolled_at: Maybe(time.Time),
	metadata: string,
}

//+sql:scan
PluginType :: struct {
	name: string,
}

//+sql:scan
ResponseJob :: struct {
	response_id: string,
	job_id: string,
}

//+sql:scan
ResponseStatsShim_Row :: struct {
	participant_id: Maybe(string),
	wave_id: Maybe(string),
	task_group_id: Maybe(string),
	response_id: Maybe(string),
	completed: Maybe(bool),
	completed_count: Maybe(i64),
	missed_count: Maybe(i64),
	total_count: Maybe(i64),
	streak: Maybe(i64),
}

//+sql:scan
ResponseTranscription :: struct {
	response_id: string,
	question_id: string,
	transcription: string,
	created_at: Maybe(time.Time),
	updated_at: Maybe(time.Time),
}

//+sql:scan
Respons :: struct {
	id: string,
	delivery_id: string,
	completed: Maybe(bool),
	task_answers: Maybe([]byte),
	created_at: Maybe(time.Time),
	updated_at: Maybe(time.Time),
	task_version_id: string,
	answers: string,
}

//+sql:scan
Role :: struct {
	id: string,
	parent_role_id: Maybe(string),
	created_at: time.Time,
	updated_at: time.Time,
}

//+sql:scan
Study :: struct {
	id: string,
	name: string,
	url: Maybe(string),
	banner_img_url: Maybe(string),
	theme_color: Maybe(string),
	icon_img_url: Maybe(string),
	description: Maybe(string),
	rate_limit: Maybe(i64),
	api_secret: string,
	created_at: Maybe(time.Time),
	updated_at: Maybe(time.Time),
	team_id: Maybe(string),
	use_pii_passphrase: Maybe(bool),
	export_folder_id: Maybe(string),
	theme_color_dark: Maybe(string),
}

//+sql:scan
StudyContact :: struct {
	id: string,
	study_id: string,
	email: string,
	purpose: string,
}

//+sql:scan
StudyEncryptionsKey :: struct {
	id: string,
	study_id: string,
	key: string,
	created_at: time.Time,
}

//+sql:scan
StudyExpectation :: struct {
	id: string,
	icon: string,
	label: string,
	study_id: string,
}

//+sql:scan
StudyPlugin :: struct {
	id: string,
	plugin_type: string,
	study_id: string,
	config: string,
	created_at: time.Time,
	updated_at: time.Time,
	name: string,
	private_config: string,
}

//+sql:scan
StudyTranslation :: struct {
	study_id: string,
	translations: string,
	created_at: time.Time,
	updated_at: time.Time,
	locks: string,
	proper_nouns: string,
}

//+sql:scan
StudyUserFeature :: struct {
	study_id: string,
	feature_set: string,
	user_id: string,
}

//+sql:scan
StudyUser :: struct {
	id: string,
	user_id: string,
	role_id: string,
	study_id: string,
}

//+sql:scan
SurveyDailyCount :: struct {
	study_id: Maybe(string),
	day: Maybe(time.Time),
	participant_tag_id: Maybe(string),
	response_count: Maybe(i64),
	completed_count: Maybe(i64),
}

//+sql:scan
TangoAccount_Row :: struct {
	id: string,
	study_id: string,
	customer_id: string,
	account_id: string,
	created_at: time.Time,
	updated_at: time.Time,
	balance: f64,
}

//+sql:scan
TangoAccountFund :: struct {
	id: string,
	study_id: string,
	amount: f64,
	created_at: time.Time,
	updated_at: time.Time,
	note: Maybe(string),
}

//+sql:scan
TangoOrder_Row :: struct {
	id: string,
	participant_id: string,
	tango_reference_order_id: Maybe(string),
	created_at: time.Time,
	updated_at: time.Time,
	amount: f64,
	redemption_url: Maybe(string),
	tango_details: Maybe(string),
	is_redeemed: bool,
	redemption_history: Maybe(string),
	tango_account_id: string,
}

//+sql:scan
TaskGroup :: struct {
	id: string,
	title: string,
	study_id: string,
	created_at: Maybe(time.Time),
	updated_at: Maybe(time.Time),
	task_type: string,
}

//+sql:scan
TaskVersion :: struct {
	id: string,
	task_data: string,
	task_group_id: string,
	note: string,
	created_at: Maybe(time.Time),
	publish_at: Maybe(time.Time),
}

//+sql:scan
TremendousOrder_Row :: struct {
	id: string,
	participant_id: string,
	payload: string,
	event_rule_id: Maybe(string),
	manually_triggered_by: Maybe(string),
	created_at: time.Time,
	updated_at: time.Time,
	status: string,
	response_id: Maybe(string),
	redeemed_at: Maybe(time.Time),
	order_type: string,
}

//+sql:scan
TremendousOrg_Row :: struct {
	id: Maybe(string),
	status: string,
	api_key: string,
	study_id: string,
	created_at: time.Time,
	updated_at: time.Time,
}

//+sql:scan
UserToken :: struct {
	email: string,
	type: string,
	token: string,
	used: bool,
	expires: time.Time,
}

//+sql:scan
User :: struct {
	id: string,
	first_name: string,
	last_name: string,
	email: string,
	password: string,
	created_at: time.Time,
	updated_at: time.Time,
	admin: bool,
	verified: bool,
}

//+sql:scan
WaveTaskDelivery :: struct {
	id: string,
	wave_task_id: string,
	participant_id: string,
	delivery_time: Maybe(time.Time),
	start: time.Time,
	end: time.Time,
	wave_order: i64,
	delivery_order: i64,
	deleted: bool,
}

//+sql:scan
WaveTask :: struct {
	id: string,
	wave_id: string,
	task_group_id: string,
	participant_tag_id: Maybe(string),
	rrule_string: string,
	allow_multiple_submissions: Maybe(bool),
	duration_minutes: Maybe(i64),
	created_at: Maybe(time.Time),
	local_notifications: Maybe(string),
	day_offset: Maybe(i64),
}

//+sql:scan
Wave :: struct {
	id: string,
	name: string,
	study_id: string,
	duration_days: i64,
	order: Maybe(i64),
	rrule_string: string,
	created_at: Maybe(time.Time),
	updated_at: Maybe(time.Time),
	dynamic_start: bool,
}

AlertRules := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	task_version_id: sb.Column(string),
	name: sb.Column(string),
	logic: sb.Column(string),
	deleted_at: sb.Column(time.Time),
	created_at: sb.Column(time.Time),
	priority: sb.Column(i64),
	stop_on_match: sb.Column(bool),
}{
	_info = {name = "alert_rules"},
	id = {base = {table = "alert_rules", name = "id", type_id = string}},
	task_version_id = {base = {table = "alert_rules", name = "task_version_id", type_id = string}},
	name = {base = {table = "alert_rules", name = "name", type_id = string}},
	logic = {base = {table = "alert_rules", name = "logic", type_id = string}},
	deleted_at = {base = {table = "alert_rules", name = "deleted_at", type_id = time.Time, nullable = true}},
	created_at = {base = {table = "alert_rules", name = "created_at", type_id = time.Time}},
	priority = {base = {table = "alert_rules", name = "priority", type_id = i64}},
	stop_on_match = {base = {table = "alert_rules", name = "stop_on_match", type_id = bool}},
}

Alerts := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	study_id: sb.Column(string),
	response_id: sb.Column(string),
	message: sb.Column(string),
	created_at: sb.Column(time.Time),
	rule_id: sb.Column(string),
	send_email: sb.Column(bool),
}{
	_info = {name = "alerts"},
	id = {base = {table = "alerts", name = "id", type_id = string}},
	study_id = {base = {table = "alerts", name = "study_id", type_id = string}},
	response_id = {base = {table = "alerts", name = "response_id", type_id = string}},
	message = {base = {table = "alerts", name = "message", type_id = string}},
	created_at = {base = {table = "alerts", name = "created_at", type_id = time.Time, nullable = true}},
	rule_id = {base = {table = "alerts", name = "rule_id", type_id = string}},
	send_email = {base = {table = "alerts", name = "send_email", type_id = bool, nullable = true}},
}

AvailablePlugins := struct {
	_info: sb.Table_Info,
	name: sb.Column(string),
	default_config: sb.Column(string),
	type: sb.Column(string),
}{
	_info = {name = "available_plugins"},
	name = {base = {table = "available_plugins", name = "name", type_id = string}},
	default_config = {base = {table = "available_plugins", name = "default_config", type_id = string}},
	type = {base = {table = "available_plugins", name = "type", type_id = string}},
}

ContactPurpose := struct {
	_info: sb.Table_Info,
	name: sb.Column(string),
}{
	_info = {name = "contact_purpose"},
	name = {base = {table = "contact_purpose", name = "name", type_id = string}},
}

Devices := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	name: sb.Column(string),
	metadata: sb.Column(string),
	firebase_token: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	device_id: sb.Column(string),
}{
	_info = {name = "devices"},
	id = {base = {table = "devices", name = "id", type_id = string}},
	name = {base = {table = "devices", name = "name", type_id = string}},
	metadata = {base = {table = "devices", name = "metadata", type_id = string}},
	firebase_token = {base = {table = "devices", name = "firebase_token", type_id = string}},
	created_at = {base = {table = "devices", name = "created_at", type_id = time.Time, nullable = true}},
	updated_at = {base = {table = "devices", name = "updated_at", type_id = time.Time, nullable = true}},
	device_id = {base = {table = "devices", name = "device_id", type_id = string, nullable = true}},
}

EventRules := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	study_id: sb.Column(string),
	name: sb.Column(string),
	logic: sb.Column(string),
	deleted_at: sb.Column(time.Time),
	created_at: sb.Column(time.Time),
	priority: sb.Column(i64),
	stop_on_match: sb.Column(bool),
	action: sb.Column(string),
	wave_id: sb.Column(string),
	task_group_id: sb.Column(string),
	participant_tag_id: sb.Column(string),
}{
	_info = {name = "event_rules"},
	id = {base = {table = "event_rules", name = "id", type_id = string}},
	study_id = {base = {table = "event_rules", name = "study_id", type_id = string}},
	name = {base = {table = "event_rules", name = "name", type_id = string}},
	logic = {base = {table = "event_rules", name = "logic", type_id = string}},
	deleted_at = {base = {table = "event_rules", name = "deleted_at", type_id = time.Time, nullable = true}},
	created_at = {base = {table = "event_rules", name = "created_at", type_id = time.Time}},
	priority = {base = {table = "event_rules", name = "priority", type_id = i64}},
	stop_on_match = {base = {table = "event_rules", name = "stop_on_match", type_id = bool}},
	action = {base = {table = "event_rules", name = "action", type_id = string}},
	wave_id = {base = {table = "event_rules", name = "wave_id", type_id = string, nullable = true}},
	task_group_id = {base = {table = "event_rules", name = "task_group_id", type_id = string, nullable = true}},
	participant_tag_id = {base = {table = "event_rules", name = "participant_tag_id", type_id = string, nullable = true}},
}

FeatureSet := struct {
	_info: sb.Table_Info,
	name: sb.Column(string),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "feature_set"},
	name = {base = {table = "feature_set", name = "name", type_id = string}},
	created_at = {base = {table = "feature_set", name = "created_at", type_id = time.Time}},
}

Jobs := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	status: sb.Column(string),
	progress: sb.Column(i64),
	payload: sb.Column(string),
	current_retry: sb.Column(i64),
	started_at: sb.Column(time.Time),
	finished_at: sb.Column(time.Time),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	name: sb.Column(string),
	study_plugin_id: sb.Column(string),
}{
	_info = {name = "jobs"},
	id = {base = {table = "jobs", name = "id", type_id = string}},
	status = {base = {table = "jobs", name = "status", type_id = string}},
	progress = {base = {table = "jobs", name = "progress", type_id = i64}},
	payload = {base = {table = "jobs", name = "payload", type_id = string}},
	current_retry = {base = {table = "jobs", name = "current_retry", type_id = i64}},
	started_at = {base = {table = "jobs", name = "started_at", type_id = time.Time, nullable = true}},
	finished_at = {base = {table = "jobs", name = "finished_at", type_id = time.Time, nullable = true}},
	created_at = {base = {table = "jobs", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "jobs", name = "updated_at", type_id = time.Time}},
	name = {base = {table = "jobs", name = "name", type_id = string}},
	study_plugin_id = {base = {table = "jobs", name = "study_plugin_id", type_id = string}},
}

LiveStudies := struct {
	_info: sb.Table_Info,
	study_id: sb.Column(string),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "live_studies"},
	study_id = {base = {table = "live_studies", name = "study_id", type_id = string}},
	created_at = {base = {table = "live_studies", name = "created_at", type_id = time.Time}},
}

ParticipantArchive := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	participant_id: sb.Column(string),
	archived_at: sb.Column(time.Time),
	archived_by: sb.Column(string),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "participant_archive"},
	id = {base = {table = "participant_archive", name = "id", type_id = string}},
	participant_id = {base = {table = "participant_archive", name = "participant_id", type_id = string}},
	archived_at = {base = {table = "participant_archive", name = "archived_at", type_id = time.Time, nullable = true}},
	archived_by = {base = {table = "participant_archive", name = "archived_by", type_id = string}},
	created_at = {base = {table = "participant_archive", name = "created_at", type_id = time.Time, nullable = true}},
}

ParticipantDevices := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	participant_id: sb.Column(string),
	device_id: sb.Column(string),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "participant_devices"},
	id = {base = {table = "participant_devices", name = "id", type_id = string}},
	participant_id = {base = {table = "participant_devices", name = "participant_id", type_id = string}},
	device_id = {base = {table = "participant_devices", name = "device_id", type_id = string}},
	created_at = {base = {table = "participant_devices", name = "created_at", type_id = time.Time, nullable = true}},
}

ParticipantLog := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	participant_id: sb.Column(string),
	message: sb.Column(string),
	tag: sb.Column(string),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "participant_log"},
	id = {base = {table = "participant_log", name = "id", type_id = string}},
	participant_id = {base = {table = "participant_log", name = "participant_id", type_id = string}},
	message = {base = {table = "participant_log", name = "message", type_id = string}},
	tag = {base = {table = "participant_log", name = "tag", type_id = string}},
	created_at = {base = {table = "participant_log", name = "created_at", type_id = time.Time, nullable = true}},
}

ParticipantNotifications := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	sent_by: sb.Column(string),
	message: sb.Column(string),
	created_at: sb.Column(time.Time),
	delivered_at: sb.Column(time.Time),
	participant_id: sb.Column(string),
	extra_data: sb.Column(string),
}{
	_info = {name = "participant_notifications"},
	id = {base = {table = "participant_notifications", name = "id", type_id = string}},
	sent_by = {base = {table = "participant_notifications", name = "sent_by", type_id = string, nullable = true}},
	message = {base = {table = "participant_notifications", name = "message", type_id = string}},
	created_at = {base = {table = "participant_notifications", name = "created_at", type_id = time.Time}},
	delivered_at = {base = {table = "participant_notifications", name = "delivered_at", type_id = time.Time, nullable = true}},
	participant_id = {base = {table = "participant_notifications", name = "participant_id", type_id = string}},
	extra_data = {base = {table = "participant_notifications", name = "extra_data", type_id = string, nullable = true}},
}

ParticipantPins := struct {
	_info: sb.Table_Info,
	pin: sb.Column(string),
	participant_id: sb.Column(string),
	study_id: sb.Column(string),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "participant_pins"},
	pin = {base = {table = "participant_pins", name = "pin", type_id = string}},
	participant_id = {base = {table = "participant_pins", name = "participant_id", type_id = string}},
	study_id = {base = {table = "participant_pins", name = "study_id", type_id = string}},
	created_at = {base = {table = "participant_pins", name = "created_at", type_id = time.Time}},
}

ParticipantProgressShim := struct {
	_info: sb.Table_Info,
	study_id: sb.Column(string),
	participant_id: sb.Column(string),
	wave_order: sb.Column(i64),
	last_completed_response_date: sb.Column(time.Time),
	last_delivery_time: sb.Column(time.Time),
	total_deliveries: sb.Column(i64),
	completed_deliveries: sb.Column(i64),
	completed_streak: sb.Column(i64),
}{
	_info = {name = "participant_progress_shim"},
	study_id = {base = {table = "participant_progress_shim", name = "study_id", type_id = string, nullable = true}},
	participant_id = {base = {table = "participant_progress_shim", name = "participant_id", type_id = string, nullable = true}},
	wave_order = {base = {table = "participant_progress_shim", name = "wave_order", type_id = i64, nullable = true}},
	last_completed_response_date = {base = {table = "participant_progress_shim", name = "last_completed_response_date", type_id = time.Time, nullable = true}},
	last_delivery_time = {base = {table = "participant_progress_shim", name = "last_delivery_time", type_id = time.Time, nullable = true}},
	total_deliveries = {base = {table = "participant_progress_shim", name = "total_deliveries", type_id = i64, nullable = true}},
	completed_deliveries = {base = {table = "participant_progress_shim", name = "completed_deliveries", type_id = i64, nullable = true}},
	completed_streak = {base = {table = "participant_progress_shim", name = "completed_streak", type_id = i64, nullable = true}},
}

ParticipantTags := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	study_id: sb.Column(string),
	tag: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	color: sb.Column(string),
}{
	_info = {name = "participant_tags"},
	id = {base = {table = "participant_tags", name = "id", type_id = string}},
	study_id = {base = {table = "participant_tags", name = "study_id", type_id = string}},
	tag = {base = {table = "participant_tags", name = "tag", type_id = string}},
	created_at = {base = {table = "participant_tags", name = "created_at", type_id = time.Time, nullable = true}},
	updated_at = {base = {table = "participant_tags", name = "updated_at", type_id = time.Time, nullable = true}},
	color = {base = {table = "participant_tags", name = "color", type_id = string, nullable = true}},
}

ParticipantWaveOffsets := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	wave_id: sb.Column(string),
	participant_id: sb.Column(string),
	offset_days: sb.Column(i64),
}{
	_info = {name = "participant_wave_offsets"},
	id = {base = {table = "participant_wave_offsets", name = "id", type_id = string}},
	wave_id = {base = {table = "participant_wave_offsets", name = "wave_id", type_id = string}},
	participant_id = {base = {table = "participant_wave_offsets", name = "participant_id", type_id = string}},
	offset_days = {base = {table = "participant_wave_offsets", name = "offset_days", type_id = i64}},
}

Participants := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	study_id: sb.Column(string),
	key: sb.Column(string),
	participant_tag_id: sb.Column(string),
	enrolled_at: sb.Column(time.Time),
	metadata: sb.Column(string),
}{
	_info = {name = "participants"},
	id = {base = {table = "participants", name = "id", type_id = string}},
	study_id = {base = {table = "participants", name = "study_id", type_id = string}},
	key = {base = {table = "participants", name = "key", type_id = string}},
	participant_tag_id = {base = {table = "participants", name = "participant_tag_id", type_id = string, nullable = true}},
	enrolled_at = {base = {table = "participants", name = "enrolled_at", type_id = time.Time, nullable = true}},
	metadata = {base = {table = "participants", name = "metadata", type_id = string}},
}

PluginTypes := struct {
	_info: sb.Table_Info,
	name: sb.Column(string),
}{
	_info = {name = "plugin_types"},
	name = {base = {table = "plugin_types", name = "name", type_id = string}},
}

ResponseJobs := struct {
	_info: sb.Table_Info,
	response_id: sb.Column(string),
	job_id: sb.Column(string),
}{
	_info = {name = "response_jobs"},
	response_id = {base = {table = "response_jobs", name = "response_id", type_id = string}},
	job_id = {base = {table = "response_jobs", name = "job_id", type_id = string}},
}

ResponseStatsShim := struct {
	_info: sb.Table_Info,
	participant_id: sb.Column(string),
	wave_id: sb.Column(string),
	task_group_id: sb.Column(string),
	response_id: sb.Column(string),
	completed: sb.Column(bool),
	completed_count: sb.Column(i64),
	missed_count: sb.Column(i64),
	total_count: sb.Column(i64),
	streak: sb.Column(i64),
}{
	_info = {name = "response_stats_shim"},
	participant_id = {base = {table = "response_stats_shim", name = "participant_id", type_id = string, nullable = true}},
	wave_id = {base = {table = "response_stats_shim", name = "wave_id", type_id = string, nullable = true}},
	task_group_id = {base = {table = "response_stats_shim", name = "task_group_id", type_id = string, nullable = true}},
	response_id = {base = {table = "response_stats_shim", name = "response_id", type_id = string, nullable = true}},
	completed = {base = {table = "response_stats_shim", name = "completed", type_id = bool, nullable = true}},
	completed_count = {base = {table = "response_stats_shim", name = "completed_count", type_id = i64, nullable = true}},
	missed_count = {base = {table = "response_stats_shim", name = "missed_count", type_id = i64, nullable = true}},
	total_count = {base = {table = "response_stats_shim", name = "total_count", type_id = i64, nullable = true}},
	streak = {base = {table = "response_stats_shim", name = "streak", type_id = i64, nullable = true}},
}

ResponseTranscriptions := struct {
	_info: sb.Table_Info,
	response_id: sb.Column(string),
	question_id: sb.Column(string),
	transcription: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
}{
	_info = {name = "response_transcriptions"},
	response_id = {base = {table = "response_transcriptions", name = "response_id", type_id = string}},
	question_id = {base = {table = "response_transcriptions", name = "question_id", type_id = string}},
	transcription = {base = {table = "response_transcriptions", name = "transcription", type_id = string}},
	created_at = {base = {table = "response_transcriptions", name = "created_at", type_id = time.Time, nullable = true}},
	updated_at = {base = {table = "response_transcriptions", name = "updated_at", type_id = time.Time, nullable = true}},
}

Responses := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	delivery_id: sb.Column(string),
	completed: sb.Column(bool),
	task_answers: sb.Column([]byte),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	task_version_id: sb.Column(string),
	answers: sb.Column(string),
}{
	_info = {name = "responses"},
	id = {base = {table = "responses", name = "id", type_id = string}},
	delivery_id = {base = {table = "responses", name = "delivery_id", type_id = string}},
	completed = {base = {table = "responses", name = "completed", type_id = bool, nullable = true}},
	task_answers = {base = {table = "responses", name = "task_answers", type_id = []byte, nullable = true}},
	created_at = {base = {table = "responses", name = "created_at", type_id = time.Time, nullable = true}},
	updated_at = {base = {table = "responses", name = "updated_at", type_id = time.Time, nullable = true}},
	task_version_id = {base = {table = "responses", name = "task_version_id", type_id = string}},
	answers = {base = {table = "responses", name = "answers", type_id = string}},
}

Roles := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	parent_role_id: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
}{
	_info = {name = "roles"},
	id = {base = {table = "roles", name = "id", type_id = string}},
	parent_role_id = {base = {table = "roles", name = "parent_role_id", type_id = string, nullable = true}},
	created_at = {base = {table = "roles", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "roles", name = "updated_at", type_id = time.Time}},
}

Studies := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	name: sb.Column(string),
	url: sb.Column(string),
	banner_img_url: sb.Column(string),
	theme_color: sb.Column(string),
	icon_img_url: sb.Column(string),
	description: sb.Column(string),
	rate_limit: sb.Column(i64),
	api_secret: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	team_id: sb.Column(string),
	use_pii_passphrase: sb.Column(bool),
	export_folder_id: sb.Column(string),
	theme_color_dark: sb.Column(string),
}{
	_info = {name = "studies"},
	id = {base = {table = "studies", name = "id", type_id = string}},
	name = {base = {table = "studies", name = "name", type_id = string}},
	url = {base = {table = "studies", name = "url", type_id = string, nullable = true}},
	banner_img_url = {base = {table = "studies", name = "banner_img_url", type_id = string, nullable = true}},
	theme_color = {base = {table = "studies", name = "theme_color", type_id = string, nullable = true}},
	icon_img_url = {base = {table = "studies", name = "icon_img_url", type_id = string, nullable = true}},
	description = {base = {table = "studies", name = "description", type_id = string, nullable = true}},
	rate_limit = {base = {table = "studies", name = "rate_limit", type_id = i64, nullable = true}},
	api_secret = {base = {table = "studies", name = "api_secret", type_id = string}},
	created_at = {base = {table = "studies", name = "created_at", type_id = time.Time, nullable = true}},
	updated_at = {base = {table = "studies", name = "updated_at", type_id = time.Time, nullable = true}},
	team_id = {base = {table = "studies", name = "team_id", type_id = string, nullable = true}},
	use_pii_passphrase = {base = {table = "studies", name = "use_pii_passphrase", type_id = bool, nullable = true}},
	export_folder_id = {base = {table = "studies", name = "export_folder_id", type_id = string, nullable = true}},
	theme_color_dark = {base = {table = "studies", name = "theme_color_dark", type_id = string, nullable = true}},
}

StudyContacts := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	study_id: sb.Column(string),
	email: sb.Column(string),
	purpose: sb.Column(string),
}{
	_info = {name = "study_contacts"},
	id = {base = {table = "study_contacts", name = "id", type_id = string}},
	study_id = {base = {table = "study_contacts", name = "study_id", type_id = string}},
	email = {base = {table = "study_contacts", name = "email", type_id = string}},
	purpose = {base = {table = "study_contacts", name = "purpose", type_id = string}},
}

StudyEncryptionsKeys := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	study_id: sb.Column(string),
	key: sb.Column(string),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "study_encryptions_keys"},
	id = {base = {table = "study_encryptions_keys", name = "id", type_id = string}},
	study_id = {base = {table = "study_encryptions_keys", name = "study_id", type_id = string}},
	key = {base = {table = "study_encryptions_keys", name = "key", type_id = string}},
	created_at = {base = {table = "study_encryptions_keys", name = "created_at", type_id = time.Time}},
}

StudyExpectations := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	icon: sb.Column(string),
	label: sb.Column(string),
	study_id: sb.Column(string),
}{
	_info = {name = "study_expectations"},
	id = {base = {table = "study_expectations", name = "id", type_id = string}},
	icon = {base = {table = "study_expectations", name = "icon", type_id = string}},
	label = {base = {table = "study_expectations", name = "label", type_id = string}},
	study_id = {base = {table = "study_expectations", name = "study_id", type_id = string}},
}

StudyPlugins := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	plugin_type: sb.Column(string),
	study_id: sb.Column(string),
	config: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	name: sb.Column(string),
	private_config: sb.Column(string),
}{
	_info = {name = "study_plugins"},
	id = {base = {table = "study_plugins", name = "id", type_id = string}},
	plugin_type = {base = {table = "study_plugins", name = "plugin_type", type_id = string}},
	study_id = {base = {table = "study_plugins", name = "study_id", type_id = string}},
	config = {base = {table = "study_plugins", name = "config", type_id = string}},
	created_at = {base = {table = "study_plugins", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "study_plugins", name = "updated_at", type_id = time.Time}},
	name = {base = {table = "study_plugins", name = "name", type_id = string}},
	private_config = {base = {table = "study_plugins", name = "private_config", type_id = string}},
}

StudyTranslations := struct {
	_info: sb.Table_Info,
	study_id: sb.Column(string),
	translations: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	locks: sb.Column(string),
	proper_nouns: sb.Column(string),
}{
	_info = {name = "study_translations"},
	study_id = {base = {table = "study_translations", name = "study_id", type_id = string}},
	translations = {base = {table = "study_translations", name = "translations", type_id = string}},
	created_at = {base = {table = "study_translations", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "study_translations", name = "updated_at", type_id = time.Time}},
	locks = {base = {table = "study_translations", name = "locks", type_id = string}},
	proper_nouns = {base = {table = "study_translations", name = "proper_nouns", type_id = string}},
}

StudyUserFeatures := struct {
	_info: sb.Table_Info,
	study_id: sb.Column(string),
	feature_set: sb.Column(string),
	user_id: sb.Column(string),
}{
	_info = {name = "study_user_features"},
	study_id = {base = {table = "study_user_features", name = "study_id", type_id = string}},
	feature_set = {base = {table = "study_user_features", name = "feature_set", type_id = string}},
	user_id = {base = {table = "study_user_features", name = "user_id", type_id = string}},
}

StudyUsers := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	user_id: sb.Column(string),
	role_id: sb.Column(string),
	study_id: sb.Column(string),
}{
	_info = {name = "study_users"},
	id = {base = {table = "study_users", name = "id", type_id = string}},
	user_id = {base = {table = "study_users", name = "user_id", type_id = string}},
	role_id = {base = {table = "study_users", name = "role_id", type_id = string}},
	study_id = {base = {table = "study_users", name = "study_id", type_id = string}},
}

SurveyDailyCounts := struct {
	_info: sb.Table_Info,
	study_id: sb.Column(string),
	day: sb.Column(time.Time),
	participant_tag_id: sb.Column(string),
	response_count: sb.Column(i64),
	completed_count: sb.Column(i64),
}{
	_info = {name = "survey_daily_counts"},
	study_id = {base = {table = "survey_daily_counts", name = "study_id", type_id = string, nullable = true}},
	day = {base = {table = "survey_daily_counts", name = "day", type_id = time.Time, nullable = true}},
	participant_tag_id = {base = {table = "survey_daily_counts", name = "participant_tag_id", type_id = string, nullable = true}},
	response_count = {base = {table = "survey_daily_counts", name = "response_count", type_id = i64, nullable = true}},
	completed_count = {base = {table = "survey_daily_counts", name = "completed_count", type_id = i64, nullable = true}},
}

TangoAccount := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	study_id: sb.Column(string),
	customer_id: sb.Column(string),
	account_id: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	balance: sb.Column(f64),
}{
	_info = {name = "tango_account"},
	id = {base = {table = "tango_account", name = "id", type_id = string}},
	study_id = {base = {table = "tango_account", name = "study_id", type_id = string}},
	customer_id = {base = {table = "tango_account", name = "customer_id", type_id = string}},
	account_id = {base = {table = "tango_account", name = "account_id", type_id = string}},
	created_at = {base = {table = "tango_account", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "tango_account", name = "updated_at", type_id = time.Time}},
	balance = {base = {table = "tango_account", name = "balance", type_id = f64}},
}

TangoAccountFunds := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	study_id: sb.Column(string),
	amount: sb.Column(f64),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	note: sb.Column(string),
}{
	_info = {name = "tango_account_funds"},
	id = {base = {table = "tango_account_funds", name = "id", type_id = string}},
	study_id = {base = {table = "tango_account_funds", name = "study_id", type_id = string}},
	amount = {base = {table = "tango_account_funds", name = "amount", type_id = f64}},
	created_at = {base = {table = "tango_account_funds", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "tango_account_funds", name = "updated_at", type_id = time.Time}},
	note = {base = {table = "tango_account_funds", name = "note", type_id = string, nullable = true}},
}

TangoOrder := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	participant_id: sb.Column(string),
	tango_reference_order_id: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	amount: sb.Column(f64),
	redemption_url: sb.Column(string),
	tango_details: sb.Column(string),
	is_redeemed: sb.Column(bool),
	redemption_history: sb.Column(string),
	tango_account_id: sb.Column(string),
}{
	_info = {name = "tango_order"},
	id = {base = {table = "tango_order", name = "id", type_id = string}},
	participant_id = {base = {table = "tango_order", name = "participant_id", type_id = string}},
	tango_reference_order_id = {base = {table = "tango_order", name = "tango_reference_order_id", type_id = string, nullable = true}},
	created_at = {base = {table = "tango_order", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "tango_order", name = "updated_at", type_id = time.Time}},
	amount = {base = {table = "tango_order", name = "amount", type_id = f64}},
	redemption_url = {base = {table = "tango_order", name = "redemption_url", type_id = string, nullable = true}},
	tango_details = {base = {table = "tango_order", name = "tango_details", type_id = string, nullable = true}},
	is_redeemed = {base = {table = "tango_order", name = "is_redeemed", type_id = bool}},
	redemption_history = {base = {table = "tango_order", name = "redemption_history", type_id = string, nullable = true}},
	tango_account_id = {base = {table = "tango_order", name = "tango_account_id", type_id = string}},
}

TaskGroups := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	title: sb.Column(string),
	study_id: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	task_type: sb.Column(string),
}{
	_info = {name = "task_groups"},
	id = {base = {table = "task_groups", name = "id", type_id = string}},
	title = {base = {table = "task_groups", name = "title", type_id = string}},
	study_id = {base = {table = "task_groups", name = "study_id", type_id = string}},
	created_at = {base = {table = "task_groups", name = "created_at", type_id = time.Time, nullable = true}},
	updated_at = {base = {table = "task_groups", name = "updated_at", type_id = time.Time, nullable = true}},
	task_type = {base = {table = "task_groups", name = "task_type", type_id = string}},
}

TaskVersions := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	task_data: sb.Column(string),
	task_group_id: sb.Column(string),
	note: sb.Column(string),
	created_at: sb.Column(time.Time),
	publish_at: sb.Column(time.Time),
}{
	_info = {name = "task_versions"},
	id = {base = {table = "task_versions", name = "id", type_id = string}},
	task_data = {base = {table = "task_versions", name = "task_data", type_id = string}},
	task_group_id = {base = {table = "task_versions", name = "task_group_id", type_id = string}},
	note = {base = {table = "task_versions", name = "note", type_id = string}},
	created_at = {base = {table = "task_versions", name = "created_at", type_id = time.Time, nullable = true}},
	publish_at = {base = {table = "task_versions", name = "publish_at", type_id = time.Time, nullable = true}},
}

TremendousOrder := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	participant_id: sb.Column(string),
	payload: sb.Column(string),
	event_rule_id: sb.Column(string),
	manually_triggered_by: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	status: sb.Column(string),
	response_id: sb.Column(string),
	redeemed_at: sb.Column(time.Time),
	order_type: sb.Column(string),
}{
	_info = {name = "tremendous_order"},
	id = {base = {table = "tremendous_order", name = "id", type_id = string}},
	participant_id = {base = {table = "tremendous_order", name = "participant_id", type_id = string}},
	payload = {base = {table = "tremendous_order", name = "payload", type_id = string}},
	event_rule_id = {base = {table = "tremendous_order", name = "event_rule_id", type_id = string, nullable = true}},
	manually_triggered_by = {base = {table = "tremendous_order", name = "manually_triggered_by", type_id = string, nullable = true}},
	created_at = {base = {table = "tremendous_order", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "tremendous_order", name = "updated_at", type_id = time.Time}},
	status = {base = {table = "tremendous_order", name = "status", type_id = string}},
	response_id = {base = {table = "tremendous_order", name = "response_id", type_id = string, nullable = true}},
	redeemed_at = {base = {table = "tremendous_order", name = "redeemed_at", type_id = time.Time, nullable = true}},
	order_type = {base = {table = "tremendous_order", name = "order_type", type_id = string}},
}

TremendousOrg := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	status: sb.Column(string),
	api_key: sb.Column(string),
	study_id: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
}{
	_info = {name = "tremendous_org"},
	id = {base = {table = "tremendous_org", name = "id", type_id = string, nullable = true}},
	status = {base = {table = "tremendous_org", name = "status", type_id = string}},
	api_key = {base = {table = "tremendous_org", name = "api_key", type_id = string}},
	study_id = {base = {table = "tremendous_org", name = "study_id", type_id = string}},
	created_at = {base = {table = "tremendous_org", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "tremendous_org", name = "updated_at", type_id = time.Time}},
}

UserTokens := struct {
	_info: sb.Table_Info,
	email: sb.Column(string),
	type: sb.Column(string),
	token: sb.Column(string),
	used: sb.Column(bool),
	expires: sb.Column(time.Time),
}{
	_info = {name = "user_tokens"},
	email = {base = {table = "user_tokens", name = "email", type_id = string}},
	type = {base = {table = "user_tokens", name = "type", type_id = string}},
	token = {base = {table = "user_tokens", name = "token", type_id = string}},
	used = {base = {table = "user_tokens", name = "used", type_id = bool}},
	expires = {base = {table = "user_tokens", name = "expires", type_id = time.Time}},
}

Users := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	first_name: sb.Column(string),
	last_name: sb.Column(string),
	email: sb.Column(string),
	password: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	admin: sb.Column(bool),
	verified: sb.Column(bool),
}{
	_info = {name = "users"},
	id = {base = {table = "users", name = "id", type_id = string}},
	first_name = {base = {table = "users", name = "first_name", type_id = string}},
	last_name = {base = {table = "users", name = "last_name", type_id = string}},
	email = {base = {table = "users", name = "email", type_id = string}},
	password = {base = {table = "users", name = "password", type_id = string}},
	created_at = {base = {table = "users", name = "created_at", type_id = time.Time}},
	updated_at = {base = {table = "users", name = "updated_at", type_id = time.Time}},
	admin = {base = {table = "users", name = "admin", type_id = bool}},
	verified = {base = {table = "users", name = "verified", type_id = bool}},
}

WaveTaskDeliveries := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	wave_task_id: sb.Column(string),
	participant_id: sb.Column(string),
	delivery_time: sb.Column(time.Time),
	start: sb.Column(time.Time),
	end: sb.Column(time.Time),
	wave_order: sb.Column(i64),
	delivery_order: sb.Column(i64),
	deleted: sb.Column(bool),
}{
	_info = {name = "wave_task_deliveries"},
	id = {base = {table = "wave_task_deliveries", name = "id", type_id = string}},
	wave_task_id = {base = {table = "wave_task_deliveries", name = "wave_task_id", type_id = string}},
	participant_id = {base = {table = "wave_task_deliveries", name = "participant_id", type_id = string}},
	delivery_time = {base = {table = "wave_task_deliveries", name = "delivery_time", type_id = time.Time, nullable = true}},
	start = {base = {table = "wave_task_deliveries", name = "start", type_id = time.Time}},
	end = {base = {table = "wave_task_deliveries", name = "end", type_id = time.Time}},
	wave_order = {base = {table = "wave_task_deliveries", name = "wave_order", type_id = i64}},
	delivery_order = {base = {table = "wave_task_deliveries", name = "delivery_order", type_id = i64}},
	deleted = {base = {table = "wave_task_deliveries", name = "deleted", type_id = bool}},
}

WaveTasks := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	wave_id: sb.Column(string),
	task_group_id: sb.Column(string),
	participant_tag_id: sb.Column(string),
	rrule_string: sb.Column(string),
	allow_multiple_submissions: sb.Column(bool),
	duration_minutes: sb.Column(i64),
	created_at: sb.Column(time.Time),
	local_notifications: sb.Column(string),
	day_offset: sb.Column(i64),
}{
	_info = {name = "wave_tasks"},
	id = {base = {table = "wave_tasks", name = "id", type_id = string}},
	wave_id = {base = {table = "wave_tasks", name = "wave_id", type_id = string}},
	task_group_id = {base = {table = "wave_tasks", name = "task_group_id", type_id = string}},
	participant_tag_id = {base = {table = "wave_tasks", name = "participant_tag_id", type_id = string, nullable = true}},
	rrule_string = {base = {table = "wave_tasks", name = "rrule_string", type_id = string}},
	allow_multiple_submissions = {base = {table = "wave_tasks", name = "allow_multiple_submissions", type_id = bool, nullable = true}},
	duration_minutes = {base = {table = "wave_tasks", name = "duration_minutes", type_id = i64, nullable = true}},
	created_at = {base = {table = "wave_tasks", name = "created_at", type_id = time.Time, nullable = true}},
	local_notifications = {base = {table = "wave_tasks", name = "local_notifications", type_id = string, nullable = true}},
	day_offset = {base = {table = "wave_tasks", name = "day_offset", type_id = i64, nullable = true}},
}

Waves := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	name: sb.Column(string),
	study_id: sb.Column(string),
	duration_days: sb.Column(i64),
	order: sb.Column(i64),
	rrule_string: sb.Column(string),
	created_at: sb.Column(time.Time),
	updated_at: sb.Column(time.Time),
	dynamic_start: sb.Column(bool),
}{
	_info = {name = "waves"},
	id = {base = {table = "waves", name = "id", type_id = string}},
	name = {base = {table = "waves", name = "name", type_id = string}},
	study_id = {base = {table = "waves", name = "study_id", type_id = string}},
	duration_days = {base = {table = "waves", name = "duration_days", type_id = i64}},
	order = {base = {table = "waves", name = "order", type_id = i64, nullable = true}},
	rrule_string = {base = {table = "waves", name = "rrule_string", type_id = string}},
	created_at = {base = {table = "waves", name = "created_at", type_id = time.Time, nullable = true}},
	updated_at = {base = {table = "waves", name = "updated_at", type_id = time.Time, nullable = true}},
	dynamic_start = {base = {table = "waves", name = "dynamic_start", type_id = bool}},
}

