// Code generated by tools/schemagen. DO NOT EDIT.
package query_builder

import sb "database:sqlbuilder"

Users := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	name: sb.Column(string),
	age: sb.Column(int),
}{
	_info = {name = "users"},
	id = {base = {table = "users", name = "id", type_id = i64}},
	name = {base = {table = "users", name = "name", type_id = string}},
	age = {base = {table = "users", name = "age", type_id = int}},
}

Posts := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	user_id: sb.Column(i64),
	title: sb.Column(string),
}{
	_info = {name = "posts"},
	id = {base = {table = "posts", name = "id", type_id = i64}},
	user_id = {base = {table = "posts", name = "user_id", type_id = i64}},
	title = {base = {table = "posts", name = "title", type_id = string}},
}

