// Code generated by tools/scangen. DO NOT EDIT.
package main

import "core:strings"
import "core:time"
import sql "database:sql"

scan_CatchmentBoundary :: proc(rows: ^sql.Rows, dest: ^CatchmentBoundary) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "hydro_source_id":
			if v, ok := val.(i64); ok { dest.hydro_source_id = i64(v) }
		case "geometry":
			if v, ok := val.(string); ok {
				dest.geometry = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_CatchmentCalibration :: proc(rows: ^sql.Rows, dest: ^CatchmentCalibration) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "meta":
			if v, ok := val.(string); ok {
				dest.meta = v if detached else strings.clone(v)
			}
		case "awc":
			#partial switch v in val {
			case f64: dest.awc = v
			case i64: dest.awc = f64(v)
			}
		case "summer_rcoeff":
			#partial switch v in val {
			case f64: dest.summer_rcoeff = v
			case i64: dest.summer_rcoeff = f64(v)
			}
		case "seepage":
			#partial switch v in val {
			case f64: dest.seepage = v
			case i64: dest.seepage = f64(v)
			}
		case "grow_start_month":
			if v, ok := val.(i64); ok { dest.grow_start_month = i64(v) }
		case "grow_end_month":
			if v, ok := val.(i64); ok { dest.grow_end_month = i64(v) }
		case "grow_cover_factor":
			#partial switch v in val {
			case f64: dest.grow_cover_factor = v
			case i64: dest.grow_cover_factor = f64(v)
			}
		case "dormant_cover_factor":
			#partial switch v in val {
			case f64: dest.dormant_cover_factor = v
			case i64: dest.dormant_cover_factor = f64(v)
			}
		case "winter_rcoeff":
			#partial switch v in val {
			case f64: dest.winter_rcoeff = v
			case i64: dest.winter_rcoeff = f64(v)
			}
		case "winter_start":
			if v, ok := val.(i64); ok { dest.winter_start = i64(v) }
		case "winter_end":
			if v, ok := val.(i64); ok { dest.winter_end = i64(v) }
		case "curve_number":
			#partial switch v in val {
			case f64: dest.curve_number = v
			case i64: dest.curve_number = f64(v)
			}
		case "kusle":
			#partial switch v in val {
			case f64: dest.kusle = v
			case i64: dest.kusle = f64(v)
			}
		case "cusle":
			#partial switch v in val {
			case f64: dest.cusle = v
			case i64: dest.cusle = f64(v)
			}
		case "pusle":
			#partial switch v in val {
			case f64: dest.pusle = v
			case i64: dest.pusle = f64(v)
			}
		case "lsusle":
			#partial switch v in val {
			case f64: dest.lsusle = v
			case i64: dest.lsusle = f64(v)
			}
		case "cfrg":
			#partial switch v in val {
			case f64: dest.cfrg = v
			case i64: dest.cfrg = f64(v)
			}
		case "temp_threshold":
			#partial switch v in val {
			case f64: dest.temp_threshold = v
			case i64: dest.temp_threshold = f64(v)
			}
		case "melt_factor":
			#partial switch v in val {
			case f64: dest.melt_factor = v
			case i64: dest.melt_factor = f64(v)
			}
		case "water_et_factor":
			#partial switch v in val {
			case f64: dest.water_et_factor = v
			case i64: dest.water_et_factor = f64(v)
			}
		case "tss_gw_conc_mult":
			#partial switch v in val {
			case f64: dest.tss_gw_conc_mult = v
			case i64: dest.tss_gw_conc_mult = f64(v)
			}
		case "nitr_gw_conc_mult":
			#partial switch v in val {
			case f64: dest.nitr_gw_conc_mult = v
			case i64: dest.nitr_gw_conc_mult = f64(v)
			}
		case "phos_gw_conc_mult":
			#partial switch v in val {
			case f64: dest.phos_gw_conc_mult = v
			case i64: dest.phos_gw_conc_mult = f64(v)
			}
		case "mavel":
			#partial switch v in val {
			case f64: dest.mavel = v
			case i64: dest.mavel = f64(v)
			}
		case "infil_rate":
			#partial switch v in val {
			case f64: dest.infil_rate = v
			case i64: dest.infil_rate = f64(v)
			}
		case "recession_delay":
			#partial switch v in val {
			case f64: dest.recession_delay = v
			case i64: dest.recession_delay = f64(v)
			}
		}
	}
	return nil
}

scan_CatchmentFlowline :: proc(rows: ^sql.Rows, dest: ^CatchmentFlowline) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "hydro_source_id":
			if v, ok := val.(i64); ok { dest.hydro_source_id = i64(v) }
		case "geometry":
			if v, ok := val.(string); ok {
				dest.geometry = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_CatchmentMetGrid :: proc(rows: ^sql.Rows, dest: ^CatchmentMetGrid) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "source_id":
			if v, ok := val.(i64); ok { dest.source_id = i64(v) }
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "weight":
			#partial switch v in val {
			case f64: dest.weight = v
			case i64: dest.weight = f64(v)
			}
		}
	}
	return nil
}

scan_CatchmentMetObservation :: proc(rows: ^sql.Rows, dest: ^CatchmentMetObservation) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "hydro_source_id":
			if v, ok := val.(i64); ok { dest.hydro_source_id = i64(v) }
		case "met_source_id":
			if v, ok := val.(i64); ok { dest.met_source_id = i64(v) }
		case "measured_date":
			if v, ok := val.(time.Time); ok { dest.measured_date = v }
		case "avg_precip_cm":
			#partial switch v in val {
			case f64: dest.avg_precip_cm = v
			case i64: dest.avg_precip_cm = f64(v)
			}
		case "avg_temp_c":
			#partial switch v in val {
			case f64: dest.avg_temp_c = v
			case i64: dest.avg_temp_c = f64(v)
			}
		}
	}
	return nil
}

scan_CatchmentNavigation_Row :: proc(rows: ^sql.Rows, dest: ^CatchmentNavigation_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "fromcomid":
			if v, ok := val.(i64); ok { dest.fromcomid = i64(v) }
		case "tocomid":
			if v, ok := val.(i64); ok { dest.tocomid = i64(v) }
		case "hydro_source_id":
			if v, ok := val.(i64); ok { dest.hydro_source_id = i64(v) }
		}
	}
	return nil
}

scan_CatchmentSoilValue :: proc(rows: ^sql.Rows, dest: ^CatchmentSoilValue) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "hydro_source_id":
			if v, ok := val.(i64); ok { dest.hydro_source_id = i64(v) }
		case "landuse_id":
			if v, ok := val.(i64); ok { dest.landuse_id = i64(v) }
		case "landuse_source_id":
			if v, ok := val.(i64); ok { dest.landuse_source_id = i64(v) }
		case "curve_number":
			#partial switch v in val {
			case f64: dest.curve_number = v
			case i64: dest.curve_number = f64(v)
			}
		case "area":
			#partial switch v in val {
			case f64: dest.area = v
			case i64: dest.area = f64(v)
			}
		case "kffact":
			#partial switch v in val {
			case f64: dest.kffact = v
			case i64: dest.kffact = f64(v)
			}
		case "sand":
			#partial switch v in val {
			case f64: dest.sand = v
			case i64: dest.sand = f64(v)
			}
		case "silt":
			#partial switch v in val {
			case f64: dest.silt = v
			case i64: dest.silt = f64(v)
			}
		case "clay":
			#partial switch v in val {
			case f64: dest.clay = v
			case i64: dest.clay = f64(v)
			}
		case "slopeR":
			#partial switch v in val {
			case f64: dest.slopeR = v
			case i64: dest.slopeR = f64(v)
			}
		case "length":
			#partial switch v in val {
			case f64: dest.length = v
			case i64: dest.length = f64(v)
			}
		case "lsFactor":
			#partial switch v in val {
			case f64: dest.lsFactor = v
			case i64: dest.lsFactor = f64(v)
			}
		case "klscp":
			#partial switch v in val {
			case f64: dest.klscp = v
			case i64: dest.klscp = f64(v)
			}
		case "c":
			#partial switch v in val {
			case f64: dest.c = v
			case i64: dest.c = f64(v)
			}
		case "p":
			#partial switch v in val {
			case f64: dest.p = v
			case i64: dest.p = f64(v)
			}
		case "hydgrp":
			if v, ok := val.(string); ok {
				dest.hydgrp = v if detached else strings.clone(v)
			}
		case "wthirdbarR":
			#partial switch v in val {
			case f64: dest.wthirdbarR = v
			case i64: dest.wthirdbarR = f64(v)
			}
		case "wsatiatedR":
			#partial switch v in val {
			case f64: dest.wsatiatedR = v
			case i64: dest.wsatiatedR = f64(v)
			}
		case "cfrg":
			#partial switch v in val {
			case f64: dest.cfrg = v
			case i64: dest.cfrg = f64(v)
			}
		case "max_depth":
			#partial switch v in val {
			case f64: dest.max_depth = v
			case i64: dest.max_depth = f64(v)
			}
		}
	}
	return nil
}

scan_Catchment :: proc(rows: ^sql.Rows, dest: ^Catchment) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "source_id":
			if v, ok := val.(i64); ok { dest.source_id = i64(v) }
		case "awc_cm":
			#partial switch v in val {
			case f64: dest.awc_cm = v
			case i64: dest.awc_cm = f64(v)
			}
		case "seepage":
			#partial switch v in val {
			case f64: dest.seepage = v
			case i64: dest.seepage = f64(v)
			}
		case "rcfs":
			#partial switch v in val {
			case f64: dest.rcfs = v
			case i64: dest.rcfs = f64(v)
			}
		case "total_area":
			#partial switch v in val {
			case f64: dest.total_area = v
			case i64: dest.total_area = f64(v)
			}
		case "rfactor":
			#partial switch v in val {
			case f64: dest.rfactor = v
			case i64: dest.rfactor = f64(v)
			}
		case "grow_season_et_cover":
			#partial switch v in val {
			case f64: dest.grow_season_et_cover = v
			case i64: dest.grow_season_et_cover = f64(v)
			}
		case "dormant_season_et_cover":
			#partial switch v in val {
			case f64: dest.dormant_season_et_cover = v
			case i64: dest.dormant_season_et_cover = f64(v)
			}
		case "latitude":
			#partial switch v in val {
			case f64: dest.latitude = v
			case i64: dest.latitude = f64(v)
			}
		case "longitude":
			#partial switch v in val {
			case f64: dest.longitude = v
			case i64: dest.longitude = f64(v)
			}
		case "channel_length":
			#partial switch v in val {
			case f64: dest.channel_length = v
			case i64: dest.channel_length = f64(v)
			}
		case "mavel":
			#partial switch v in val {
			case f64: dest.mavel = v
			case i64: dest.mavel = f64(v)
			}
		case "bankfull_vol":
			#partial switch v in val {
			case f64: dest.bankfull_vol = v
			case i64: dest.bankfull_vol = f64(v)
			}
		}
	}
	return nil
}

scan_CurrentCatchmentNutrient :: proc(rows: ^sql.Rows, dest: ^CurrentCatchmentNutrient) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "SepticCount":
			if v, ok := val.(i64); ok { dest.SepticCount = i64(v) }
		case "EroClass":
			if v, ok := val.(string); ok {
				dest.EroClass = v if detached else strings.clone(v)
			}
		case "EroFlowThreshold":
			#partial switch v in val {
			case f64: dest.EroFlowThreshold = v
			case i64: dest.EroFlowThreshold = f64(v)
			}
		case "ChannelEroPortion":
			#partial switch v in val {
			case f64: dest.ChannelEroPortion = v
			case i64: dest.ChannelEroPortion = f64(v)
			}
		case "DailyManureNitr":
			#partial switch v in val {
			case f64: dest.DailyManureNitr = v
			case i64: dest.DailyManureNitr = f64(v)
			}
		case "DailyManurePhos":
			#partial switch v in val {
			case f64: dest.DailyManurePhos = v
			case i64: dest.DailyManurePhos = f64(v)
			}
		}
	}
	return nil
}

scan_CurrentWaterQuality_Row :: proc(rows: ^sql.Rows, dest: ^CurrentWaterQuality_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "landuse_id":
			if v, ok := val.(i64); ok { dest.landuse_id = i64(v) }
		case "CombinedDescription":
			if v, ok := val.(string); ok {
				dest.CombinedDescription = v if detached else strings.clone(v)
			}
		case "Type":
			if v, ok := val.(string); ok {
				dest.Type = v if detached else strings.clone(v)
			}
		case "disssed_mgl":
			#partial switch v in val {
			case f64: dest.disssed_mgl = v
			case i64: dest.disssed_mgl = f64(v)
			}
		case "dissn_mgl":
			#partial switch v in val {
			case f64: dest.dissn_mgl = v
			case i64: dest.dissn_mgl = f64(v)
			}
		case "solidn_mgkg":
			#partial switch v in val {
			case f64: dest.solidn_mgkg = v
			case i64: dest.solidn_mgkg = f64(v)
			}
		case "dissp_mgl":
			#partial switch v in val {
			case f64: dest.dissp_mgl = v
			case i64: dest.dissp_mgl = f64(v)
			}
		case "solidp_mgkg":
			#partial switch v in val {
			case f64: dest.solidp_mgkg = v
			case i64: dest.solidp_mgkg = f64(v)
			}
		case "tssaccumrate":
			#partial switch v in val {
			case f64: dest.tssaccumrate = v
			case i64: dest.tssaccumrate = f64(v)
			}
		case "naccumrate":
			#partial switch v in val {
			case f64: dest.naccumrate = v
			case i64: dest.naccumrate = f64(v)
			}
		case "paccumrate":
			#partial switch v in val {
			case f64: dest.paccumrate = v
			case i64: dest.paccumrate = f64(v)
			}
		case "sed_efficiency":
			#partial switch v in val {
			case f64: dest.sed_efficiency = v
			case i64: dest.sed_efficiency = f64(v)
			}
		case "phos_efficiency":
			#partial switch v in val {
			case f64: dest.phos_efficiency = v
			case i64: dest.phos_efficiency = f64(v)
			}
		case "nitr_efficiency":
			#partial switch v in val {
			case f64: dest.nitr_efficiency = v
			case i64: dest.nitr_efficiency = f64(v)
			}
		case "p_settling":
			#partial switch v in val {
			case f64: dest.p_settling = v
			case i64: dest.p_settling = f64(v)
			}
		case "n_settling":
			#partial switch v in val {
			case f64: dest.n_settling = v
			case i64: dest.n_settling = f64(v)
			}
		case "sed_settling":
			#partial switch v in val {
			case f64: dest.sed_settling = v
			case i64: dest.sed_settling = f64(v)
			}
		}
	}
	return nil
}

scan_FuturehighCatchmentNutrient :: proc(rows: ^sql.Rows, dest: ^FuturehighCatchmentNutrient) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "SepticCount":
			if v, ok := val.(i64); ok { dest.SepticCount = i64(v) }
		case "EroClass":
			if v, ok := val.(string); ok {
				dest.EroClass = v if detached else strings.clone(v)
			}
		case "EroFlowThreshold":
			#partial switch v in val {
			case f64: dest.EroFlowThreshold = v
			case i64: dest.EroFlowThreshold = f64(v)
			}
		case "ChannelEroPortion":
			#partial switch v in val {
			case f64: dest.ChannelEroPortion = v
			case i64: dest.ChannelEroPortion = f64(v)
			}
		case "DailyManureNitr":
			#partial switch v in val {
			case f64: dest.DailyManureNitr = v
			case i64: dest.DailyManureNitr = f64(v)
			}
		case "DailyManurePhos":
			#partial switch v in val {
			case f64: dest.DailyManurePhos = v
			case i64: dest.DailyManurePhos = f64(v)
			}
		}
	}
	return nil
}

scan_FuturehighWaterQuality_Row :: proc(rows: ^sql.Rows, dest: ^FuturehighWaterQuality_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "landuse_id":
			if v, ok := val.(i64); ok { dest.landuse_id = i64(v) }
		case "CombinedDescription":
			if v, ok := val.(string); ok {
				dest.CombinedDescription = v if detached else strings.clone(v)
			}
		case "Type":
			if v, ok := val.(string); ok {
				dest.Type = v if detached else strings.clone(v)
			}
		case "disssed_mgl":
			#partial switch v in val {
			case f64: dest.disssed_mgl = v
			case i64: dest.disssed_mgl = f64(v)
			}
		case "dissn_mgl":
			#partial switch v in val {
			case f64: dest.dissn_mgl = v
			case i64: dest.dissn_mgl = f64(v)
			}
		case "solidn_mgkg":
			#partial switch v in val {
			case f64: dest.solidn_mgkg = v
			case i64: dest.solidn_mgkg = f64(v)
			}
		case "dissp_mgl":
			#partial switch v in val {
			case f64: dest.dissp_mgl = v
			case i64: dest.dissp_mgl = f64(v)
			}
		case "solidp_mgkg":
			#partial switch v in val {
			case f64: dest.solidp_mgkg = v
			case i64: dest.solidp_mgkg = f64(v)
			}
		case "tssaccumrate":
			#partial switch v in val {
			case f64: dest.tssaccumrate = v
			case i64: dest.tssaccumrate = f64(v)
			}
		case "naccumrate":
			#partial switch v in val {
			case f64: dest.naccumrate = v
			case i64: dest.naccumrate = f64(v)
			}
		case "paccumrate":
			#partial switch v in val {
			case f64: dest.paccumrate = v
			case i64: dest.paccumrate = f64(v)
			}
		case "sed_efficiency":
			#partial switch v in val {
			case f64: dest.sed_efficiency = v
			case i64: dest.sed_efficiency = f64(v)
			}
		case "phos_efficiency":
			#partial switch v in val {
			case f64: dest.phos_efficiency = v
			case i64: dest.phos_efficiency = f64(v)
			}
		case "nitr_efficiency":
			#partial switch v in val {
			case f64: dest.nitr_efficiency = v
			case i64: dest.nitr_efficiency = f64(v)
			}
		case "p_settling":
			#partial switch v in val {
			case f64: dest.p_settling = v
			case i64: dest.p_settling = f64(v)
			}
		case "n_settling":
			#partial switch v in val {
			case f64: dest.n_settling = v
			case i64: dest.n_settling = f64(v)
			}
		case "sed_settling":
			#partial switch v in val {
			case f64: dest.sed_settling = v
			case i64: dest.sed_settling = f64(v)
			}
		}
	}
	return nil
}

scan_FuturelowCatchmentNutrient :: proc(rows: ^sql.Rows, dest: ^FuturelowCatchmentNutrient) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "SepticCount":
			if v, ok := val.(i64); ok { dest.SepticCount = i64(v) }
		case "EroClass":
			if v, ok := val.(string); ok {
				dest.EroClass = v if detached else strings.clone(v)
			}
		case "EroFlowThreshold":
			#partial switch v in val {
			case f64: dest.EroFlowThreshold = v
			case i64: dest.EroFlowThreshold = f64(v)
			}
		case "ChannelEroPortion":
			#partial switch v in val {
			case f64: dest.ChannelEroPortion = v
			case i64: dest.ChannelEroPortion = f64(v)
			}
		case "DailyManureNitr":
			#partial switch v in val {
			case f64: dest.DailyManureNitr = v
			case i64: dest.DailyManureNitr = f64(v)
			}
		case "DailyManurePhos":
			#partial switch v in val {
			case f64: dest.DailyManurePhos = v
			case i64: dest.DailyManurePhos = f64(v)
			}
		}
	}
	return nil
}

scan_FuturelowWaterQuality_Row :: proc(rows: ^sql.Rows, dest: ^FuturelowWaterQuality_Row) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "landuse_id":
			if v, ok := val.(i64); ok { dest.landuse_id = i64(v) }
		case "CombinedDescription":
			if v, ok := val.(string); ok {
				dest.CombinedDescription = v if detached else strings.clone(v)
			}
		case "Type":
			if v, ok := val.(string); ok {
				dest.Type = v if detached else strings.clone(v)
			}
		case "disssed_mgl":
			#partial switch v in val {
			case f64: dest.disssed_mgl = v
			case i64: dest.disssed_mgl = f64(v)
			}
		case "dissn_mgl":
			#partial switch v in val {
			case f64: dest.dissn_mgl = v
			case i64: dest.dissn_mgl = f64(v)
			}
		case "solidn_mgkg":
			#partial switch v in val {
			case f64: dest.solidn_mgkg = v
			case i64: dest.solidn_mgkg = f64(v)
			}
		case "dissp_mgl":
			#partial switch v in val {
			case f64: dest.dissp_mgl = v
			case i64: dest.dissp_mgl = f64(v)
			}
		case "solidp_mgkg":
			#partial switch v in val {
			case f64: dest.solidp_mgkg = v
			case i64: dest.solidp_mgkg = f64(v)
			}
		case "tssaccumrate":
			#partial switch v in val {
			case f64: dest.tssaccumrate = v
			case i64: dest.tssaccumrate = f64(v)
			}
		case "naccumrate":
			#partial switch v in val {
			case f64: dest.naccumrate = v
			case i64: dest.naccumrate = f64(v)
			}
		case "paccumrate":
			#partial switch v in val {
			case f64: dest.paccumrate = v
			case i64: dest.paccumrate = f64(v)
			}
		case "sed_efficiency":
			#partial switch v in val {
			case f64: dest.sed_efficiency = v
			case i64: dest.sed_efficiency = f64(v)
			}
		case "phos_efficiency":
			#partial switch v in val {
			case f64: dest.phos_efficiency = v
			case i64: dest.phos_efficiency = f64(v)
			}
		case "nitr_efficiency":
			#partial switch v in val {
			case f64: dest.nitr_efficiency = v
			case i64: dest.nitr_efficiency = f64(v)
			}
		case "p_settling":
			#partial switch v in val {
			case f64: dest.p_settling = v
			case i64: dest.p_settling = f64(v)
			}
		case "n_settling":
			#partial switch v in val {
			case f64: dest.n_settling = v
			case i64: dest.n_settling = f64(v)
			}
		case "sed_settling":
			#partial switch v in val {
			case f64: dest.sed_settling = v
			case i64: dest.sed_settling = f64(v)
			}
		}
	}
	return nil
}

scan_GpkgContent :: proc(rows: ^sql.Rows, dest: ^GpkgContent) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "table_name":
			if v, ok := val.(string); ok {
				dest.table_name = v if detached else strings.clone(v)
			}
		case "data_type":
			if v, ok := val.(string); ok {
				dest.data_type = v if detached else strings.clone(v)
			}
		case "identifier":
			if v, ok := val.(string); ok {
				dest.identifier = v if detached else strings.clone(v)
			}
		case "description":
			if v, ok := val.(string); ok {
				dest.description = v if detached else strings.clone(v)
			}
		case "last_change":
			if v, ok := val.(time.Time); ok { dest.last_change = v }
		case "min_x":
			#partial switch v in val {
			case f64: dest.min_x = v
			case i64: dest.min_x = f64(v)
			}
		case "min_y":
			#partial switch v in val {
			case f64: dest.min_y = v
			case i64: dest.min_y = f64(v)
			}
		case "max_x":
			#partial switch v in val {
			case f64: dest.max_x = v
			case i64: dest.max_x = f64(v)
			}
		case "max_y":
			#partial switch v in val {
			case f64: dest.max_y = v
			case i64: dest.max_y = f64(v)
			}
		case "srs_id":
			if v, ok := val.(i64); ok { dest.srs_id = i64(v) }
		}
	}
	return nil
}

scan_GpkgExtension :: proc(rows: ^sql.Rows, dest: ^GpkgExtension) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "table_name":
			if v, ok := val.(string); ok {
				dest.table_name = v if detached else strings.clone(v)
			}
		case "column_name":
			if v, ok := val.(string); ok {
				dest.column_name = v if detached else strings.clone(v)
			}
		case "extension_name":
			if v, ok := val.(string); ok {
				dest.extension_name = v if detached else strings.clone(v)
			}
		case "definition":
			if v, ok := val.(string); ok {
				dest.definition = v if detached else strings.clone(v)
			}
		case "scope":
			if v, ok := val.(string); ok {
				dest.scope = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_GpkgGeometryColumn :: proc(rows: ^sql.Rows, dest: ^GpkgGeometryColumn) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "table_name":
			if v, ok := val.(string); ok {
				dest.table_name = v if detached else strings.clone(v)
			}
		case "column_name":
			if v, ok := val.(string); ok {
				dest.column_name = v if detached else strings.clone(v)
			}
		case "geometry_type_name":
			if v, ok := val.(string); ok {
				dest.geometry_type_name = v if detached else strings.clone(v)
			}
		case "srs_id":
			if v, ok := val.(i64); ok { dest.srs_id = i64(v) }
		case "z":
			if v, ok := val.(i64); ok { dest.z = i64(v) }
		case "m":
			if v, ok := val.(i64); ok { dest.m = i64(v) }
		}
	}
	return nil
}

scan_GpkgSpatialRefSy :: proc(rows: ^sql.Rows, dest: ^GpkgSpatialRefSy) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "srs_name":
			if v, ok := val.(string); ok {
				dest.srs_name = v if detached else strings.clone(v)
			}
		case "srs_id":
			if v, ok := val.(i64); ok { dest.srs_id = i64(v) }
		case "organization":
			if v, ok := val.(string); ok {
				dest.organization = v if detached else strings.clone(v)
			}
		case "organization_coordsys_id":
			if v, ok := val.(i64); ok { dest.organization_coordsys_id = i64(v) }
		case "definition":
			if v, ok := val.(string); ok {
				dest.definition = v if detached else strings.clone(v)
			}
		case "description":
			if v, ok := val.(string); ok {
				dest.description = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_LanduseType :: proc(rows: ^sql.Rows, dest: ^LanduseType) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "source_id":
			if v, ok := val.(i64); ok { dest.source_id = i64(v) }
		case "description":
			if v, ok := val.(string); ok {
				dest.description = v if detached else strings.clone(v)
			}
		case "is_land":
			#partial switch x in val {
			case bool: dest.is_land = x
			case i64:  dest.is_land = x != 0
			}
		case "category":
			if v, ok := val.(string); ok {
				dest.category = v if detached else strings.clone(v)
			}
		case "is_riparian":
			#partial switch x in val {
			case bool: dest.is_riparian = x
			case i64:  dest.is_riparian = x != 0
			}
		case "is_mgmt":
			#partial switch x in val {
			case bool: dest.is_mgmt = x
			case i64:  dest.is_mgmt = x != 0
			}
		case "c":
			#partial switch v in val {
			case f64: dest.c = v
			case i64: dest.c = f64(v)
			}
		case "p":
			#partial switch v in val {
			case f64: dest.p = v
			case i64: dest.p = f64(v)
			}
		case "cn_a":
			#partial switch v in val {
			case f64: dest.cn_a = v
			case i64: dest.cn_a = f64(v)
			}
		case "cn_b":
			#partial switch v in val {
			case f64: dest.cn_b = v
			case i64: dest.cn_b = f64(v)
			}
		case "cn_c":
			#partial switch v in val {
			case f64: dest.cn_c = v
			case i64: dest.cn_c = f64(v)
			}
		case "cn_d":
			#partial switch v in val {
			case f64: dest.cn_d = v
			case i64: dest.cn_d = f64(v)
			}
		}
	}
	return nil
}

scan_MetGridObservation :: proc(rows: ^sql.Rows, dest: ^MetGridObservation) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "source_id":
			if v, ok := val.(i64); ok { dest.source_id = i64(v) }
		case "measured_date":
			if v, ok := val.(time.Time); ok { dest.measured_date = v }
		case "avg_precip_cm":
			#partial switch v in val {
			case f64: dest.avg_precip_cm = v
			case i64: dest.avg_precip_cm = f64(v)
			}
		case "avg_temp_c":
			#partial switch v in val {
			case f64: dest.avg_temp_c = v
			case i64: dest.avg_temp_c = f64(v)
			}
		}
	}
	return nil
}

scan_Migration :: proc(rows: ^sql.Rows, dest: ^Migration) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(string); ok {
				dest.id = v if detached else strings.clone(v)
			}
		case "applied_at":
			if v, ok := val.(time.Time); ok { dest.applied_at = v }
		}
	}
	return nil
}

scan_RunCatchment :: proc(rows: ^sql.Rows, dest: ^RunCatchment) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "run_id":
			if v, ok := val.(i64); ok { dest.run_id = i64(v) }
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		}
	}
	return nil
}

scan_RunResult :: proc(rows: ^sql.Rows, dest: ^RunResult) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "run_id":
			if v, ok := val.(string); ok {
				dest.run_id = v if detached else strings.clone(v)
			}
		case "comid":
			if v, ok := val.(i64); ok { dest.comid = i64(v) }
		case "date":
			if v, ok := val.(time.Time); ok { dest.date = v }
		case "flow":
			#partial switch v in val {
			case f64: dest.flow = v
			case i64: dest.flow = f64(v)
			}
		case "flowin":
			#partial switch v in val {
			case f64: dest.flowin = v
			case i64: dest.flowin = f64(v)
			}
		case "flowout":
			#partial switch v in val {
			case f64: dest.flowout = v
			case i64: dest.flowout = f64(v)
			}
		case "runoff":
			#partial switch v in val {
			case f64: dest.runoff = v
			case i64: dest.runoff = f64(v)
			}
		case "water_runoff":
			#partial switch v in val {
			case f64: dest.water_runoff = v
			case i64: dest.water_runoff = f64(v)
			}
		case "temp":
			#partial switch v in val {
			case f64: dest.temp = v
			case i64: dest.temp = f64(v)
			}
		case "precip":
			#partial switch v in val {
			case f64: dest.precip = v
			case i64: dest.precip = f64(v)
			}
		case "et":
			#partial switch v in val {
			case f64: dest.et = v
			case i64: dest.et = f64(v)
			}
		case "pet":
			#partial switch v in val {
			case f64: dest.pet = v
			case i64: dest.pet = f64(v)
			}
		case "deep_seepage":
			#partial switch v in val {
			case f64: dest.deep_seepage = v
			case i64: dest.deep_seepage = f64(v)
			}
		case "unsat_stor":
			#partial switch v in val {
			case f64: dest.unsat_stor = v
			case i64: dest.unsat_stor = f64(v)
			}
		case "sat_stor":
			#partial switch v in val {
			case f64: dest.sat_stor = v
			case i64: dest.sat_stor = f64(v)
			}
		case "generated_sediment":
			#partial switch v in val {
			case f64: dest.generated_sediment = v
			case i64: dest.generated_sediment = f64(v)
			}
		case "routed_sediment":
			#partial switch v in val {
			case f64: dest.routed_sediment = v
			case i64: dest.routed_sediment = f64(v)
			}
		case "gw_sediment":
			#partial switch v in val {
			case f64: dest.gw_sediment = v
			case i64: dest.gw_sediment = f64(v)
			}
		case "generated_nitrogen":
			#partial switch v in val {
			case f64: dest.generated_nitrogen = v
			case i64: dest.generated_nitrogen = f64(v)
			}
		case "routed_nitrogen":
			#partial switch v in val {
			case f64: dest.routed_nitrogen = v
			case i64: dest.routed_nitrogen = f64(v)
			}
		case "septic_nitrogen":
			#partial switch v in val {
			case f64: dest.septic_nitrogen = v
			case i64: dest.septic_nitrogen = f64(v)
			}
		case "gw_nitrogen":
			#partial switch v in val {
			case f64: dest.gw_nitrogen = v
			case i64: dest.gw_nitrogen = f64(v)
			}
		case "generated_phosphorus":
			#partial switch v in val {
			case f64: dest.generated_phosphorus = v
			case i64: dest.generated_phosphorus = f64(v)
			}
		case "routed_phosphorus":
			#partial switch v in val {
			case f64: dest.routed_phosphorus = v
			case i64: dest.routed_phosphorus = f64(v)
			}
		case "gw_phosphorus":
			#partial switch v in val {
			case f64: dest.gw_phosphorus = v
			case i64: dest.gw_phosphorus = f64(v)
			}
		}
	}
	return nil
}

scan_Run :: proc(rows: ^sql.Rows, dest: ^Run) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "uid":
			if v, ok := val.(string); ok {
				dest.uid = v if detached else strings.clone(v)
			}
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "start_date":
			if v, ok := val.(time.Time); ok { dest.start_date = v }
		case "end_date":
			if v, ok := val.(time.Time); ok { dest.end_date = v }
		case "outlet":
			if v, ok := val.(i64); ok { dest.outlet = i64(v) }
		case "hydro_source_id":
			if v, ok := val.(i64); ok { dest.hydro_source_id = i64(v) }
		case "land_source_id":
			if v, ok := val.(i64); ok { dest.land_source_id = i64(v) }
		case "met_source_id":
			if v, ok := val.(i64); ok { dest.met_source_id = i64(v) }
		case "run_config":
			if v, ok := val.(string); ok {
				dest.run_config = v if detached else strings.clone(v)
			}
		case "ran_at":
			if v, ok := val.(time.Time); ok { dest.ran_at = v }
		}
	}
	return nil
}

scan_SourceType :: proc(rows: ^sql.Rows, dest: ^SourceType) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan_Source :: proc(rows: ^sql.Rows, dest: ^Source) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "source_type_id":
			if v, ok := val.(i64); ok { dest.source_type_id = i64(v) }
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		}
	}
	return nil
}

scan :: proc{
	scan_CatchmentBoundary,
	scan_CatchmentCalibration,
	scan_CatchmentFlowline,
	scan_CatchmentMetGrid,
	scan_CatchmentMetObservation,
	scan_CatchmentNavigation_Row,
	scan_CatchmentSoilValue,
	scan_Catchment,
	scan_CurrentCatchmentNutrient,
	scan_CurrentWaterQuality_Row,
	scan_FuturehighCatchmentNutrient,
	scan_FuturehighWaterQuality_Row,
	scan_FuturelowCatchmentNutrient,
	scan_FuturelowWaterQuality_Row,
	scan_GpkgContent,
	scan_GpkgExtension,
	scan_GpkgGeometryColumn,
	scan_GpkgSpatialRefSy,
	scan_LanduseType,
	scan_MetGridObservation,
	scan_Migration,
	scan_RunCatchment,
	scan_RunResult,
	scan_Run,
	scan_SourceType,
	scan_Source,
	sql.scan_struct,
	sql.scan_values,
	sql.row_scan_struct,
	sql.row_scan_values,
}
