// Code generated by tools/schemagen. DO NOT EDIT.
package main

import "core:time"
import sb "database:sqlbuilder"

//+sql:scan
CatchmentBoundary :: struct {
	id: i64,
	comid: i64,
	hydro_source_id: i64,
	geometry: Maybe(string),
}

//+sql:scan
CatchmentCalibration :: struct {
	comid: i64,
	meta: string,
	awc: Maybe(f64),
	summer_rcoeff: Maybe(f64),
	seepage: Maybe(f64),
	grow_start_month: Maybe(i64),
	grow_end_month: Maybe(i64),
	grow_cover_factor: Maybe(f64),
	dormant_cover_factor: Maybe(f64),
	winter_rcoeff: Maybe(f64),
	winter_start: Maybe(i64),
	winter_end: Maybe(i64),
	curve_number: Maybe(f64),
	kusle: Maybe(f64),
	cusle: Maybe(f64),
	pusle: Maybe(f64),
	lsusle: Maybe(f64),
	cfrg: Maybe(f64),
	temp_threshold: Maybe(f64),
	melt_factor: Maybe(f64),
	water_et_factor: Maybe(f64),
	tss_gw_conc_mult: Maybe(f64),
	nitr_gw_conc_mult: Maybe(f64),
	phos_gw_conc_mult: Maybe(f64),
	mavel: Maybe(f64),
	infil_rate: Maybe(f64),
	recession_delay: Maybe(f64),
}

//+sql:scan
CatchmentFlowline :: struct {
	id: i64,
	comid: i64,
	hydro_source_id: i64,
	geometry: Maybe(string),
}

//+sql:scan
CatchmentMetGrid :: struct {
	id: i64,
	source_id: i64,
	comid: i64,
	weight: f64,
}

//+sql:scan
CatchmentMetObservation :: struct {
	comid: i64,
	hydro_source_id: i64,
	met_source_id: i64,
	measured_date: time.Time,
	avg_precip_cm: f64,
	avg_temp_c: f64,
}

//+sql:scan
CatchmentNavigation_Row :: struct {
	fromcomid: Maybe(i64),
	tocomid: i64,
	hydro_source_id: i64,
}

//+sql:scan
CatchmentSoilValue :: struct {
	comid: i64,
	hydro_source_id: i64,
	landuse_id: i64,
	landuse_source_id: i64,
	curve_number: Maybe(f64),
	area: Maybe(f64),
	kffact: Maybe(f64),
	sand: Maybe(f64),
	silt: Maybe(f64),
	clay: Maybe(f64),
	slopeR: Maybe(f64),
	length: Maybe(f64),
	lsFactor: Maybe(f64),
	klscp: Maybe(f64),
	c: Maybe(f64),
	p: Maybe(f64),
	hydgrp: Maybe(string),
	wthirdbarR: Maybe(f64),
	wsatiatedR: Maybe(f64),
	cfrg: Maybe(f64),
	max_depth: Maybe(f64),
}

//+sql:scan
Catchment :: struct {
	comid: i64,
	source_id: i64,
	awc_cm: Maybe(f64),
	seepage: Maybe(f64),
	rcfs: Maybe(f64),
	total_area: Maybe(f64),
	rfactor: Maybe(f64),
	grow_season_et_cover: Maybe(f64),
	dormant_season_et_cover: Maybe(f64),
	latitude: Maybe(f64),
	longitude: Maybe(f64),
	channel_length: Maybe(f64),
	mavel: Maybe(f64),
	bankfull_vol: Maybe(f64),
}

//+sql:scan
CurrentCatchmentNutrient :: struct {
	comid: Maybe(i64),
	SepticCount: Maybe(i64),
	EroClass: Maybe(string),
	EroFlowThreshold: Maybe(f64),
	ChannelEroPortion: Maybe(f64),
	DailyManureNitr: Maybe(f64),
	DailyManurePhos: Maybe(f64),
}

//+sql:scan
CurrentWaterQuality_Row :: struct {
	landuse_id: Maybe(i64),
	CombinedDescription: Maybe(string),
	Type: Maybe(string),
	disssed_mgl: Maybe(f64),
	dissn_mgl: Maybe(f64),
	solidn_mgkg: Maybe(f64),
	dissp_mgl: Maybe(f64),
	solidp_mgkg: Maybe(f64),
	tssaccumrate: Maybe(f64),
	naccumrate: Maybe(f64),
	paccumrate: Maybe(f64),
	sed_efficiency: Maybe(f64),
	phos_efficiency: Maybe(f64),
	nitr_efficiency: Maybe(f64),
	p_settling: Maybe(f64),
	n_settling: Maybe(f64),
	sed_settling: Maybe(f64),
}

//+sql:scan
FuturehighCatchmentNutrient :: struct {
	comid: Maybe(i64),
	SepticCount: Maybe(i64),
	EroClass: Maybe(string),
	EroFlowThreshold: Maybe(f64),
	ChannelEroPortion: Maybe(f64),
	DailyManureNitr: Maybe(f64),
	DailyManurePhos: Maybe(f64),
}

//+sql:scan
FuturehighWaterQuality_Row :: struct {
	landuse_id: Maybe(i64),
	CombinedDescription: Maybe(string),
	Type: Maybe(string),
	disssed_mgl: Maybe(f64),
	dissn_mgl: Maybe(f64),
	solidn_mgkg: Maybe(f64),
	dissp_mgl: Maybe(f64),
	solidp_mgkg: Maybe(f64),
	tssaccumrate: Maybe(f64),
	naccumrate: Maybe(f64),
	paccumrate: Maybe(f64),
	sed_efficiency: Maybe(f64),
	phos_efficiency: Maybe(f64),
	nitr_efficiency: Maybe(f64),
	p_settling: Maybe(f64),
	n_settling: Maybe(f64),
	sed_settling: Maybe(f64),
}

//+sql:scan
FuturelowCatchmentNutrient :: struct {
	comid: Maybe(i64),
	SepticCount: Maybe(i64),
	EroClass: Maybe(string),
	EroFlowThreshold: Maybe(f64),
	ChannelEroPortion: Maybe(f64),
	DailyManureNitr: Maybe(f64),
	DailyManurePhos: Maybe(f64),
}

//+sql:scan
FuturelowWaterQuality_Row :: struct {
	landuse_id: Maybe(i64),
	CombinedDescription: Maybe(string),
	Type: Maybe(string),
	disssed_mgl: Maybe(f64),
	dissn_mgl: Maybe(f64),
	solidn_mgkg: Maybe(f64),
	dissp_mgl: Maybe(f64),
	solidp_mgkg: Maybe(f64),
	tssaccumrate: Maybe(f64),
	naccumrate: Maybe(f64),
	paccumrate: Maybe(f64),
	sed_efficiency: Maybe(f64),
	phos_efficiency: Maybe(f64),
	nitr_efficiency: Maybe(f64),
	p_settling: Maybe(f64),
	n_settling: Maybe(f64),
	sed_settling: Maybe(f64),
}

//+sql:scan
GpkgContent :: struct {
	table_name: string,
	data_type: string,
	identifier: Maybe(string),
	description: Maybe(string),
	last_change: time.Time,
	min_x: Maybe(f64),
	min_y: Maybe(f64),
	max_x: Maybe(f64),
	max_y: Maybe(f64),
	srs_id: Maybe(i64),
}

//+sql:scan
GpkgExtension :: struct {
	table_name: Maybe(string),
	column_name: Maybe(string),
	extension_name: string,
	definition: string,
	scope: string,
}

//+sql:scan
GpkgGeometryColumn :: struct {
	table_name: string,
	column_name: string,
	geometry_type_name: string,
	srs_id: i64,
	z: i64,
	m: i64,
}

//+sql:scan
GpkgSpatialRefSy :: struct {
	srs_name: string,
	srs_id: i64,
	organization: string,
	organization_coordsys_id: i64,
	definition: string,
	description: Maybe(string),
}

//+sql:scan
LanduseType :: struct {
	id: i64,
	source_id: i64,
	description: Maybe(string),
	is_land: Maybe(bool),
	category: Maybe(string),
	is_riparian: Maybe(bool),
	is_mgmt: Maybe(bool),
	c: Maybe(f64),
	p: Maybe(f64),
	cn_a: Maybe(f64),
	cn_b: Maybe(f64),
	cn_c: Maybe(f64),
	cn_d: Maybe(f64),
}

//+sql:scan
MetGridObservation :: struct {
	id: i64,
	source_id: i64,
	measured_date: time.Time,
	avg_precip_cm: f64,
	avg_temp_c: f64,
}

//+sql:scan
Migration :: struct {
	id: string,
	applied_at: Maybe(time.Time),
}

//+sql:scan
RunCatchment :: struct {
	run_id: i64,
	comid: i64,
}

//+sql:scan
RunResult :: struct {
	run_id: string,
	comid: i64,
	date: time.Time,
	flow: Maybe(f64),
	flowin: Maybe(f64),
	flowout: Maybe(f64),
	runoff: Maybe(f64),
	water_runoff: Maybe(f64),
	temp: Maybe(f64),
	precip: Maybe(f64),
	et: Maybe(f64),
	pet: Maybe(f64),
	deep_seepage: Maybe(f64),
	unsat_stor: Maybe(f64),
	sat_stor: Maybe(f64),
	generated_sediment: Maybe(f64),
	routed_sediment: Maybe(f64),
	gw_sediment: Maybe(f64),
	generated_nitrogen: Maybe(f64),
	routed_nitrogen: Maybe(f64),
	septic_nitrogen: Maybe(f64),
	gw_nitrogen: Maybe(f64),
	generated_phosphorus: Maybe(f64),
	routed_phosphorus: Maybe(f64),
	gw_phosphorus: Maybe(f64),
}

//+sql:scan
Run :: struct {
	id: i64,
	uid: string,
	name: string,
	start_date: time.Time,
	end_date: time.Time,
	outlet: i64,
	hydro_source_id: i64,
	land_source_id: i64,
	met_source_id: i64,
	run_config: Maybe(string),
	ran_at: Maybe(time.Time),
}

//+sql:scan
SourceType :: struct {
	id: i64,
	name: string,
}

//+sql:scan
Source :: struct {
	id: i64,
	source_type_id: i64,
	name: string,
}

CatchmentBoundaries := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	comid: sb.Column(i64),
	hydro_source_id: sb.Column(i64),
	geometry: sb.Column(string),
}{
	_info = {name = "catchment_boundaries"},
	id = {base = {table = "catchment_boundaries", name = "id", type_id = i64}},
	comid = {base = {table = "catchment_boundaries", name = "comid", type_id = i64}},
	hydro_source_id = {base = {table = "catchment_boundaries", name = "hydro_source_id", type_id = i64}},
	geometry = {base = {table = "catchment_boundaries", name = "geometry", type_id = string, nullable = true}},
}

CatchmentCalibrations := struct {
	_info: sb.Table_Info,
	comid: sb.Column(i64),
	meta: sb.Column(string),
	awc: sb.Column(f64),
	summer_rcoeff: sb.Column(f64),
	seepage: sb.Column(f64),
	grow_start_month: sb.Column(i64),
	grow_end_month: sb.Column(i64),
	grow_cover_factor: sb.Column(f64),
	dormant_cover_factor: sb.Column(f64),
	winter_rcoeff: sb.Column(f64),
	winter_start: sb.Column(i64),
	winter_end: sb.Column(i64),
	curve_number: sb.Column(f64),
	kusle: sb.Column(f64),
	cusle: sb.Column(f64),
	pusle: sb.Column(f64),
	lsusle: sb.Column(f64),
	cfrg: sb.Column(f64),
	temp_threshold: sb.Column(f64),
	melt_factor: sb.Column(f64),
	water_et_factor: sb.Column(f64),
	tss_gw_conc_mult: sb.Column(f64),
	nitr_gw_conc_mult: sb.Column(f64),
	phos_gw_conc_mult: sb.Column(f64),
	mavel: sb.Column(f64),
	infil_rate: sb.Column(f64),
	recession_delay: sb.Column(f64),
}{
	_info = {name = "catchment_calibrations"},
	comid = {base = {table = "catchment_calibrations", name = "comid", type_id = i64}},
	meta = {base = {table = "catchment_calibrations", name = "meta", type_id = string}},
	awc = {base = {table = "catchment_calibrations", name = "awc", type_id = f64, nullable = true}},
	summer_rcoeff = {base = {table = "catchment_calibrations", name = "summer_rcoeff", type_id = f64, nullable = true}},
	seepage = {base = {table = "catchment_calibrations", name = "seepage", type_id = f64, nullable = true}},
	grow_start_month = {base = {table = "catchment_calibrations", name = "grow_start_month", type_id = i64, nullable = true}},
	grow_end_month = {base = {table = "catchment_calibrations", name = "grow_end_month", type_id = i64, nullable = true}},
	grow_cover_factor = {base = {table = "catchment_calibrations", name = "grow_cover_factor", type_id = f64, nullable = true}},
	dormant_cover_factor = {base = {table = "catchment_calibrations", name = "dormant_cover_factor", type_id = f64, nullable = true}},
	winter_rcoeff = {base = {table = "catchment_calibrations", name = "winter_rcoeff", type_id = f64, nullable = true}},
	winter_start = {base = {table = "catchment_calibrations", name = "winter_start", type_id = i64, nullable = true}},
	winter_end = {base = {table = "catchment_calibrations", name = "winter_end", type_id = i64, nullable = true}},
	curve_number = {base = {table = "catchment_calibrations", name = "curve_number", type_id = f64, nullable = true}},
	kusle = {base = {table = "catchment_calibrations", name = "kusle", type_id = f64, nullable = true}},
	cusle = {base = {table = "catchment_calibrations", name = "cusle", type_id = f64, nullable = true}},
	pusle = {base = {table = "catchment_calibrations", name = "pusle", type_id = f64, nullable = true}},
	lsusle = {base = {table = "catchment_calibrations", name = "lsusle", type_id = f64, nullable = true}},
	cfrg = {base = {table = "catchment_calibrations", name = "cfrg", type_id = f64, nullable = true}},
	temp_threshold = {base = {table = "catchment_calibrations", name = "temp_threshold", type_id = f64, nullable = true}},
	melt_factor = {base = {table = "catchment_calibrations", name = "melt_factor", type_id = f64, nullable = true}},
	water_et_factor = {base = {table = "catchment_calibrations", name = "water_et_factor", type_id = f64, nullable = true}},
	tss_gw_conc_mult = {base = {table = "catchment_calibrations", name = "tss_gw_conc_mult", type_id = f64, nullable = true}},
	nitr_gw_conc_mult = {base = {table = "catchment_calibrations", name = "nitr_gw_conc_mult", type_id = f64, nullable = true}},
	phos_gw_conc_mult = {base = {table = "catchment_calibrations", name = "phos_gw_conc_mult", type_id = f64, nullable = true}},
	mavel = {base = {table = "catchment_calibrations", name = "mavel", type_id = f64, nullable = true}},
	infil_rate = {base = {table = "catchment_calibrations", name = "infil_rate", type_id = f64, nullable = true}},
	recession_delay = {base = {table = "catchment_calibrations", name = "recession_delay", type_id = f64, nullable = true}},
}

CatchmentFlowlines := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	comid: sb.Column(i64),
	hydro_source_id: sb.Column(i64),
	geometry: sb.Column(string),
}{
	_info = {name = "catchment_flowlines"},
	id = {base = {table = "catchment_flowlines", name = "id", type_id = i64}},
	comid = {base = {table = "catchment_flowlines", name = "comid", type_id = i64}},
	hydro_source_id = {base = {table = "catchment_flowlines", name = "hydro_source_id", type_id = i64}},
	geometry = {base = {table = "catchment_flowlines", name = "geometry", type_id = string, nullable = true}},
}

CatchmentMetGrids := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	source_id: sb.Column(i64),
	comid: sb.Column(i64),
	weight: sb.Column(f64),
}{
	_info = {name = "catchment_met_grids"},
	id = {base = {table = "catchment_met_grids", name = "id", type_id = i64}},
	source_id = {base = {table = "catchment_met_grids", name = "source_id", type_id = i64}},
	comid = {base = {table = "catchment_met_grids", name = "comid", type_id = i64}},
	weight = {base = {table = "catchment_met_grids", name = "weight", type_id = f64}},
}

CatchmentMetObservations := struct {
	_info: sb.Table_Info,
	comid: sb.Column(i64),
	hydro_source_id: sb.Column(i64),
	met_source_id: sb.Column(i64),
	measured_date: sb.Column(time.Time),
	avg_precip_cm: sb.Column(f64),
	avg_temp_c: sb.Column(f64),
}{
	_info = {name = "catchment_met_observations"},
	comid = {base = {table = "catchment_met_observations", name = "comid", type_id = i64}},
	hydro_source_id = {base = {table = "catchment_met_observations", name = "hydro_source_id", type_id = i64}},
	met_source_id = {base = {table = "catchment_met_observations", name = "met_source_id", type_id = i64}},
	measured_date = {base = {table = "catchment_met_observations", name = "measured_date", type_id = time.Time}},
	avg_precip_cm = {base = {table = "catchment_met_observations", name = "avg_precip_cm", type_id = f64}},
	avg_temp_c = {base = {table = "catchment_met_observations", name = "avg_temp_c", type_id = f64}},
}

CatchmentNavigation := struct {
	_info: sb.Table_Info,
	fromcomid: sb.Column(i64),
	tocomid: sb.Column(i64),
	hydro_source_id: sb.Column(i64),
}{
	_info = {name = "catchment_navigation"},
	fromcomid = {base = {table = "catchment_navigation", name = "fromcomid", type_id = i64, nullable = true}},
	tocomid = {base = {table = "catchment_navigation", name = "tocomid", type_id = i64}},
	hydro_source_id = {base = {table = "catchment_navigation", name = "hydro_source_id", type_id = i64}},
}

CatchmentSoilValues := struct {
	_info: sb.Table_Info,
	comid: sb.Column(i64),
	hydro_source_id: sb.Column(i64),
	landuse_id: sb.Column(i64),
	landuse_source_id: sb.Column(i64),
	curve_number: sb.Column(f64),
	area: sb.Column(f64),
	kffact: sb.Column(f64),
	sand: sb.Column(f64),
	silt: sb.Column(f64),
	clay: sb.Column(f64),
	slopeR: sb.Column(f64),
	length: sb.Column(f64),
	lsFactor: sb.Column(f64),
	klscp: sb.Column(f64),
	c: sb.Column(f64),
	p: sb.Column(f64),
	hydgrp: sb.Column(string),
	wthirdbarR: sb.Column(f64),
	wsatiatedR: sb.Column(f64),
	cfrg: sb.Column(f64),
	max_depth: sb.Column(f64),
}{
	_info = {name = "catchment_soil_values"},
	comid = {base = {table = "catchment_soil_values", name = "comid", type_id = i64}},
	hydro_source_id = {base = {table = "catchment_soil_values", name = "hydro_source_id", type_id = i64}},
	landuse_id = {base = {table = "catchment_soil_values", name = "landuse_id", type_id = i64}},
	landuse_source_id = {base = {table = "catchment_soil_values", name = "landuse_source_id", type_id = i64}},
	curve_number = {base = {table = "catchment_soil_values", name = "curve_number", type_id = f64, nullable = true}},
	area = {base = {table = "catchment_soil_values", name = "area", type_id = f64, nullable = true}},
	kffact = {base = {table = "catchment_soil_values", name = "kffact", type_id = f64, nullable = true}},
	sand = {base = {table = "catchment_soil_values", name = "sand", type_id = f64, nullable = true}},
	silt = {base = {table = "catchment_soil_values", name = "silt", type_id = f64, nullable = true}},
	clay = {base = {table = "catchment_soil_values", name = "clay", type_id = f64, nullable = true}},
	slopeR = {base = {table = "catchment_soil_values", name = "slopeR", type_id = f64, nullable = true}},
	length = {base = {table = "catchment_soil_values", name = "length", type_id = f64, nullable = true}},
	lsFactor = {base = {table = "catchment_soil_values", name = "lsFactor", type_id = f64, nullable = true}},
	klscp = {base = {table = "catchment_soil_values", name = "klscp", type_id = f64, nullable = true}},
	c = {base = {table = "catchment_soil_values", name = "c", type_id = f64, nullable = true}},
	p = {base = {table = "catchment_soil_values", name = "p", type_id = f64, nullable = true}},
	hydgrp = {base = {table = "catchment_soil_values", name = "hydgrp", type_id = string, nullable = true}},
	wthirdbarR = {base = {table = "catchment_soil_values", name = "wthirdbarR", type_id = f64, nullable = true}},
	wsatiatedR = {base = {table = "catchment_soil_values", name = "wsatiatedR", type_id = f64, nullable = true}},
	cfrg = {base = {table = "catchment_soil_values", name = "cfrg", type_id = f64, nullable = true}},
	max_depth = {base = {table = "catchment_soil_values", name = "max_depth", type_id = f64, nullable = true}},
}

Catchments := struct {
	_info: sb.Table_Info,
	comid: sb.Column(i64),
	source_id: sb.Column(i64),
	awc_cm: sb.Column(f64),
	seepage: sb.Column(f64),
	rcfs: sb.Column(f64),
	total_area: sb.Column(f64),
	rfactor: sb.Column(f64),
	grow_season_et_cover: sb.Column(f64),
	dormant_season_et_cover: sb.Column(f64),
	latitude: sb.Column(f64),
	longitude: sb.Column(f64),
	channel_length: sb.Column(f64),
	mavel: sb.Column(f64),
	bankfull_vol: sb.Column(f64),
}{
	_info = {name = "catchments"},
	comid = {base = {table = "catchments", name = "comid", type_id = i64}},
	source_id = {base = {table = "catchments", name = "source_id", type_id = i64}},
	awc_cm = {base = {table = "catchments", name = "awc_cm", type_id = f64, nullable = true}},
	seepage = {base = {table = "catchments", name = "seepage", type_id = f64, nullable = true}},
	rcfs = {base = {table = "catchments", name = "rcfs", type_id = f64, nullable = true}},
	total_area = {base = {table = "catchments", name = "total_area", type_id = f64, nullable = true}},
	rfactor = {base = {table = "catchments", name = "rfactor", type_id = f64, nullable = true}},
	grow_season_et_cover = {base = {table = "catchments", name = "grow_season_et_cover", type_id = f64, nullable = true}},
	dormant_season_et_cover = {base = {table = "catchments", name = "dormant_season_et_cover", type_id = f64, nullable = true}},
	latitude = {base = {table = "catchments", name = "latitude", type_id = f64, nullable = true}},
	longitude = {base = {table = "catchments", name = "longitude", type_id = f64, nullable = true}},
	channel_length = {base = {table = "catchments", name = "channel_length", type_id = f64, nullable = true}},
	mavel = {base = {table = "catchments", name = "mavel", type_id = f64, nullable = true}},
	bankfull_vol = {base = {table = "catchments", name = "bankfull_vol", type_id = f64, nullable = true}},
}

CurrentCatchmentNutrients := struct {
	_info: sb.Table_Info,
	comid: sb.Column(i64),
	SepticCount: sb.Column(i64),
	EroClass: sb.Column(string),
	EroFlowThreshold: sb.Column(f64),
	ChannelEroPortion: sb.Column(f64),
	DailyManureNitr: sb.Column(f64),
	DailyManurePhos: sb.Column(f64),
}{
	_info = {name = "current_catchment_nutrients"},
	comid = {base = {table = "current_catchment_nutrients", name = "comid", type_id = i64, nullable = true}},
	SepticCount = {base = {table = "current_catchment_nutrients", name = "SepticCount", type_id = i64, nullable = true}},
	EroClass = {base = {table = "current_catchment_nutrients", name = "EroClass", type_id = string, nullable = true}},
	EroFlowThreshold = {base = {table = "current_catchment_nutrients", name = "EroFlowThreshold", type_id = f64, nullable = true}},
	ChannelEroPortion = {base = {table = "current_catchment_nutrients", name = "ChannelEroPortion", type_id = f64, nullable = true}},
	DailyManureNitr = {base = {table = "current_catchment_nutrients", name = "DailyManureNitr", type_id = f64, nullable = true}},
	DailyManurePhos = {base = {table = "current_catchment_nutrients", name = "DailyManurePhos", type_id = f64, nullable = true}},
}

CurrentWaterQuality := struct {
	_info: sb.Table_Info,
	landuse_id: sb.Column(i64),
	CombinedDescription: sb.Column(string),
	Type: sb.Column(string),
	disssed_mgl: sb.Column(f64),
	dissn_mgl: sb.Column(f64),
	solidn_mgkg: sb.Column(f64),
	dissp_mgl: sb.Column(f64),
	solidp_mgkg: sb.Column(f64),
	tssaccumrate: sb.Column(f64),
	naccumrate: sb.Column(f64),
	paccumrate: sb.Column(f64),
	sed_efficiency: sb.Column(f64),
	phos_efficiency: sb.Column(f64),
	nitr_efficiency: sb.Column(f64),
	p_settling: sb.Column(f64),
	n_settling: sb.Column(f64),
	sed_settling: sb.Column(f64),
}{
	_info = {name = "current_water_quality"},
	landuse_id = {base = {table = "current_water_quality", name = "landuse_id", type_id = i64, nullable = true}},
	CombinedDescription = {base = {table = "current_water_quality", name = "CombinedDescription", type_id = string, nullable = true}},
	Type = {base = {table = "current_water_quality", name = "Type", type_id = string, nullable = true}},
	disssed_mgl = {base = {table = "current_water_quality", name = "disssed_mgl", type_id = f64, nullable = true}},
	dissn_mgl = {base = {table = "current_water_quality", name = "dissn_mgl", type_id = f64, nullable = true}},
	solidn_mgkg = {base = {table = "current_water_quality", name = "solidn_mgkg", type_id = f64, nullable = true}},
	dissp_mgl = {base = {table = "current_water_quality", name = "dissp_mgl", type_id = f64, nullable = true}},
	solidp_mgkg = {base = {table = "current_water_quality", name = "solidp_mgkg", type_id = f64, nullable = true}},
	tssaccumrate = {base = {table = "current_water_quality", name = "tssaccumrate", type_id = f64, nullable = true}},
	naccumrate = {base = {table = "current_water_quality", name = "naccumrate", type_id = f64, nullable = true}},
	paccumrate = {base = {table = "current_water_quality", name = "paccumrate", type_id = f64, nullable = true}},
	sed_efficiency = {base = {table = "current_water_quality", name = "sed_efficiency", type_id = f64, nullable = true}},
	phos_efficiency = {base = {table = "current_water_quality", name = "phos_efficiency", type_id = f64, nullable = true}},
	nitr_efficiency = {base = {table = "current_water_quality", name = "nitr_efficiency", type_id = f64, nullable = true}},
	p_settling = {base = {table = "current_water_quality", name = "p_settling", type_id = f64, nullable = true}},
	n_settling = {base = {table = "current_water_quality", name = "n_settling", type_id = f64, nullable = true}},
	sed_settling = {base = {table = "current_water_quality", name = "sed_settling", type_id = f64, nullable = true}},
}

FuturehighCatchmentNutrients := struct {
	_info: sb.Table_Info,
	comid: sb.Column(i64),
	SepticCount: sb.Column(i64),
	EroClass: sb.Column(string),
	EroFlowThreshold: sb.Column(f64),
	ChannelEroPortion: sb.Column(f64),
	DailyManureNitr: sb.Column(f64),
	DailyManurePhos: sb.Column(f64),
}{
	_info = {name = "futurehigh_catchment_nutrients"},
	comid = {base = {table = "futurehigh_catchment_nutrients", name = "comid", type_id = i64, nullable = true}},
	SepticCount = {base = {table = "futurehigh_catchment_nutrients", name = "SepticCount", type_id = i64, nullable = true}},
	EroClass = {base = {table = "futurehigh_catchment_nutrients", name = "EroClass", type_id = string, nullable = true}},
	EroFlowThreshold = {base = {table = "futurehigh_catchment_nutrients", name = "EroFlowThreshold", type_id = f64, nullable = true}},
	ChannelEroPortion = {base = {table = "futurehigh_catchment_nutrients", name = "ChannelEroPortion", type_id = f64, nullable = true}},
	DailyManureNitr = {base = {table = "futurehigh_catchment_nutrients", name = "DailyManureNitr", type_id = f64, nullable = true}},
	DailyManurePhos = {base = {table = "futurehigh_catchment_nutrients", name = "DailyManurePhos", type_id = f64, nullable = true}},
}

FuturehighWaterQuality := struct {
	_info: sb.Table_Info,
	landuse_id: sb.Column(i64),
	CombinedDescription: sb.Column(string),
	Type: sb.Column(string),
	disssed_mgl: sb.Column(f64),
	dissn_mgl: sb.Column(f64),
	solidn_mgkg: sb.Column(f64),
	dissp_mgl: sb.Column(f64),
	solidp_mgkg: sb.Column(f64),
	tssaccumrate: sb.Column(f64),
	naccumrate: sb.Column(f64),
	paccumrate: sb.Column(f64),
	sed_efficiency: sb.Column(f64),
	phos_efficiency: sb.Column(f64),
	nitr_efficiency: sb.Column(f64),
	p_settling: sb.Column(f64),
	n_settling: sb.Column(f64),
	sed_settling: sb.Column(f64),
}{
	_info = {name = "futurehigh_water_quality"},
	landuse_id = {base = {table = "futurehigh_water_quality", name = "landuse_id", type_id = i64, nullable = true}},
	CombinedDescription = {base = {table = "futurehigh_water_quality", name = "CombinedDescription", type_id = string, nullable = true}},
	Type = {base = {table = "futurehigh_water_quality", name = "Type", type_id = string, nullable = true}},
	disssed_mgl = {base = {table = "futurehigh_water_quality", name = "disssed_mgl", type_id = f64, nullable = true}},
	dissn_mgl = {base = {table = "futurehigh_water_quality", name = "dissn_mgl", type_id = f64, nullable = true}},
	solidn_mgkg = {base = {table = "futurehigh_water_quality", name = "solidn_mgkg", type_id = f64, nullable = true}},
	dissp_mgl = {base = {table = "futurehigh_water_quality", name = "dissp_mgl", type_id = f64, nullable = true}},
	solidp_mgkg = {base = {table = "futurehigh_water_quality", name = "solidp_mgkg", type_id = f64, nullable = true}},
	tssaccumrate = {base = {table = "futurehigh_water_quality", name = "tssaccumrate", type_id = f64, nullable = true}},
	naccumrate = {base = {table = "futurehigh_water_quality", name = "naccumrate", type_id = f64, nullable = true}},
	paccumrate = {base = {table = "futurehigh_water_quality", name = "paccumrate", type_id = f64, nullable = true}},
	sed_efficiency = {base = {table = "futurehigh_water_quality", name = "sed_efficiency", type_id = f64, nullable = true}},
	phos_efficiency = {base = {table = "futurehigh_water_quality", name = "phos_efficiency", type_id = f64, nullable = true}},
	nitr_efficiency = {base = {table = "futurehigh_water_quality", name = "nitr_efficiency", type_id = f64, nullable = true}},
	p_settling = {base = {table = "futurehigh_water_quality", name = "p_settling", type_id = f64, nullable = true}},
	n_settling = {base = {table = "futurehigh_water_quality", name = "n_settling", type_id = f64, nullable = true}},
	sed_settling = {base = {table = "futurehigh_water_quality", name = "sed_settling", type_id = f64, nullable = true}},
}

FuturelowCatchmentNutrients := struct {
	_info: sb.Table_Info,
	comid: sb.Column(i64),
	SepticCount: sb.Column(i64),
	EroClass: sb.Column(string),
	EroFlowThreshold: sb.Column(f64),
	ChannelEroPortion: sb.Column(f64),
	DailyManureNitr: sb.Column(f64),
	DailyManurePhos: sb.Column(f64),
}{
	_info = {name = "futurelow_catchment_nutrients"},
	comid = {base = {table = "futurelow_catchment_nutrients", name = "comid", type_id = i64, nullable = true}},
	SepticCount = {base = {table = "futurelow_catchment_nutrients", name = "SepticCount", type_id = i64, nullable = true}},
	EroClass = {base = {table = "futurelow_catchment_nutrients", name = "EroClass", type_id = string, nullable = true}},
	EroFlowThreshold = {base = {table = "futurelow_catchment_nutrients", name = "EroFlowThreshold", type_id = f64, nullable = true}},
	ChannelEroPortion = {base = {table = "futurelow_catchment_nutrients", name = "ChannelEroPortion", type_id = f64, nullable = true}},
	DailyManureNitr = {base = {table = "futurelow_catchment_nutrients", name = "DailyManureNitr", type_id = f64, nullable = true}},
	DailyManurePhos = {base = {table = "futurelow_catchment_nutrients", name = "DailyManurePhos", type_id = f64, nullable = true}},
}

FuturelowWaterQuality := struct {
	_info: sb.Table_Info,
	landuse_id: sb.Column(i64),
	CombinedDescription: sb.Column(string),
	Type: sb.Column(string),
	disssed_mgl: sb.Column(f64),
	dissn_mgl: sb.Column(f64),
	solidn_mgkg: sb.Column(f64),
	dissp_mgl: sb.Column(f64),
	solidp_mgkg: sb.Column(f64),
	tssaccumrate: sb.Column(f64),
	naccumrate: sb.Column(f64),
	paccumrate: sb.Column(f64),
	sed_efficiency: sb.Column(f64),
	phos_efficiency: sb.Column(f64),
	nitr_efficiency: sb.Column(f64),
	p_settling: sb.Column(f64),
	n_settling: sb.Column(f64),
	sed_settling: sb.Column(f64),
}{
	_info = {name = "futurelow_water_quality"},
	landuse_id = {base = {table = "futurelow_water_quality", name = "landuse_id", type_id = i64, nullable = true}},
	CombinedDescription = {base = {table = "futurelow_water_quality", name = "CombinedDescription", type_id = string, nullable = true}},
	Type = {base = {table = "futurelow_water_quality", name = "Type", type_id = string, nullable = true}},
	disssed_mgl = {base = {table = "futurelow_water_quality", name = "disssed_mgl", type_id = f64, nullable = true}},
	dissn_mgl = {base = {table = "futurelow_water_quality", name = "dissn_mgl", type_id = f64, nullable = true}},
	solidn_mgkg = {base = {table = "futurelow_water_quality", name = "solidn_mgkg", type_id = f64, nullable = true}},
	dissp_mgl = {base = {table = "futurelow_water_quality", name = "dissp_mgl", type_id = f64, nullable = true}},
	solidp_mgkg = {base = {table = "futurelow_water_quality", name = "solidp_mgkg", type_id = f64, nullable = true}},
	tssaccumrate = {base = {table = "futurelow_water_quality", name = "tssaccumrate", type_id = f64, nullable = true}},
	naccumrate = {base = {table = "futurelow_water_quality", name = "naccumrate", type_id = f64, nullable = true}},
	paccumrate = {base = {table = "futurelow_water_quality", name = "paccumrate", type_id = f64, nullable = true}},
	sed_efficiency = {base = {table = "futurelow_water_quality", name = "sed_efficiency", type_id = f64, nullable = true}},
	phos_efficiency = {base = {table = "futurelow_water_quality", name = "phos_efficiency", type_id = f64, nullable = true}},
	nitr_efficiency = {base = {table = "futurelow_water_quality", name = "nitr_efficiency", type_id = f64, nullable = true}},
	p_settling = {base = {table = "futurelow_water_quality", name = "p_settling", type_id = f64, nullable = true}},
	n_settling = {base = {table = "futurelow_water_quality", name = "n_settling", type_id = f64, nullable = true}},
	sed_settling = {base = {table = "futurelow_water_quality", name = "sed_settling", type_id = f64, nullable = true}},
}

GpkgContents := struct {
	_info: sb.Table_Info,
	table_name: sb.Column(string),
	data_type: sb.Column(string),
	identifier: sb.Column(string),
	description: sb.Column(string),
	last_change: sb.Column(time.Time),
	min_x: sb.Column(f64),
	min_y: sb.Column(f64),
	max_x: sb.Column(f64),
	max_y: sb.Column(f64),
	srs_id: sb.Column(i64),
}{
	_info = {name = "gpkg_contents"},
	table_name = {base = {table = "gpkg_contents", name = "table_name", type_id = string}},
	data_type = {base = {table = "gpkg_contents", name = "data_type", type_id = string}},
	identifier = {base = {table = "gpkg_contents", name = "identifier", type_id = string, nullable = true}},
	description = {base = {table = "gpkg_contents", name = "description", type_id = string, nullable = true}},
	last_change = {base = {table = "gpkg_contents", name = "last_change", type_id = time.Time}},
	min_x = {base = {table = "gpkg_contents", name = "min_x", type_id = f64, nullable = true}},
	min_y = {base = {table = "gpkg_contents", name = "min_y", type_id = f64, nullable = true}},
	max_x = {base = {table = "gpkg_contents", name = "max_x", type_id = f64, nullable = true}},
	max_y = {base = {table = "gpkg_contents", name = "max_y", type_id = f64, nullable = true}},
	srs_id = {base = {table = "gpkg_contents", name = "srs_id", type_id = i64, nullable = true}},
}

GpkgExtensions := struct {
	_info: sb.Table_Info,
	table_name: sb.Column(string),
	column_name: sb.Column(string),
	extension_name: sb.Column(string),
	definition: sb.Column(string),
	scope: sb.Column(string),
}{
	_info = {name = "gpkg_extensions"},
	table_name = {base = {table = "gpkg_extensions", name = "table_name", type_id = string, nullable = true}},
	column_name = {base = {table = "gpkg_extensions", name = "column_name", type_id = string, nullable = true}},
	extension_name = {base = {table = "gpkg_extensions", name = "extension_name", type_id = string}},
	definition = {base = {table = "gpkg_extensions", name = "definition", type_id = string}},
	scope = {base = {table = "gpkg_extensions", name = "scope", type_id = string}},
}

GpkgGeometryColumns := struct {
	_info: sb.Table_Info,
	table_name: sb.Column(string),
	column_name: sb.Column(string),
	geometry_type_name: sb.Column(string),
	srs_id: sb.Column(i64),
	z: sb.Column(i64),
	m: sb.Column(i64),
}{
	_info = {name = "gpkg_geometry_columns"},
	table_name = {base = {table = "gpkg_geometry_columns", name = "table_name", type_id = string}},
	column_name = {base = {table = "gpkg_geometry_columns", name = "column_name", type_id = string}},
	geometry_type_name = {base = {table = "gpkg_geometry_columns", name = "geometry_type_name", type_id = string}},
	srs_id = {base = {table = "gpkg_geometry_columns", name = "srs_id", type_id = i64}},
	z = {base = {table = "gpkg_geometry_columns", name = "z", type_id = i64}},
	m = {base = {table = "gpkg_geometry_columns", name = "m", type_id = i64}},
}

GpkgSpatialRefSys := struct {
	_info: sb.Table_Info,
	srs_name: sb.Column(string),
	srs_id: sb.Column(i64),
	organization: sb.Column(string),
	organization_coordsys_id: sb.Column(i64),
	definition: sb.Column(string),
	description: sb.Column(string),
}{
	_info = {name = "gpkg_spatial_ref_sys"},
	srs_name = {base = {table = "gpkg_spatial_ref_sys", name = "srs_name", type_id = string}},
	srs_id = {base = {table = "gpkg_spatial_ref_sys", name = "srs_id", type_id = i64}},
	organization = {base = {table = "gpkg_spatial_ref_sys", name = "organization", type_id = string}},
	organization_coordsys_id = {base = {table = "gpkg_spatial_ref_sys", name = "organization_coordsys_id", type_id = i64}},
	definition = {base = {table = "gpkg_spatial_ref_sys", name = "definition", type_id = string}},
	description = {base = {table = "gpkg_spatial_ref_sys", name = "description", type_id = string, nullable = true}},
}

LanduseTypes := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	source_id: sb.Column(i64),
	description: sb.Column(string),
	is_land: sb.Column(bool),
	category: sb.Column(string),
	is_riparian: sb.Column(bool),
	is_mgmt: sb.Column(bool),
	c: sb.Column(f64),
	p: sb.Column(f64),
	cn_a: sb.Column(f64),
	cn_b: sb.Column(f64),
	cn_c: sb.Column(f64),
	cn_d: sb.Column(f64),
}{
	_info = {name = "landuse_types"},
	id = {base = {table = "landuse_types", name = "id", type_id = i64}},
	source_id = {base = {table = "landuse_types", name = "source_id", type_id = i64}},
	description = {base = {table = "landuse_types", name = "description", type_id = string, nullable = true}},
	is_land = {base = {table = "landuse_types", name = "is_land", type_id = bool, nullable = true}},
	category = {base = {table = "landuse_types", name = "category", type_id = string, nullable = true}},
	is_riparian = {base = {table = "landuse_types", name = "is_riparian", type_id = bool, nullable = true}},
	is_mgmt = {base = {table = "landuse_types", name = "is_mgmt", type_id = bool, nullable = true}},
	c = {base = {table = "landuse_types", name = "c", type_id = f64, nullable = true}},
	p = {base = {table = "landuse_types", name = "p", type_id = f64, nullable = true}},
	cn_a = {base = {table = "landuse_types", name = "cn_a", type_id = f64, nullable = true}},
	cn_b = {base = {table = "landuse_types", name = "cn_b", type_id = f64, nullable = true}},
	cn_c = {base = {table = "landuse_types", name = "cn_c", type_id = f64, nullable = true}},
	cn_d = {base = {table = "landuse_types", name = "cn_d", type_id = f64, nullable = true}},
}

MetGridObservations := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	source_id: sb.Column(i64),
	measured_date: sb.Column(time.Time),
	avg_precip_cm: sb.Column(f64),
	avg_temp_c: sb.Column(f64),
}{
	_info = {name = "met_grid_observations"},
	id = {base = {table = "met_grid_observations", name = "id", type_id = i64}},
	source_id = {base = {table = "met_grid_observations", name = "source_id", type_id = i64}},
	measured_date = {base = {table = "met_grid_observations", name = "measured_date", type_id = time.Time}},
	avg_precip_cm = {base = {table = "met_grid_observations", name = "avg_precip_cm", type_id = f64}},
	avg_temp_c = {base = {table = "met_grid_observations", name = "avg_temp_c", type_id = f64}},
}

Migrations := struct {
	_info: sb.Table_Info,
	id: sb.Column(string),
	applied_at: sb.Column(time.Time),
}{
	_info = {name = "migrations"},
	id = {base = {table = "migrations", name = "id", type_id = string}},
	applied_at = {base = {table = "migrations", name = "applied_at", type_id = time.Time, nullable = true}},
}

RunCatchments := struct {
	_info: sb.Table_Info,
	run_id: sb.Column(i64),
	comid: sb.Column(i64),
}{
	_info = {name = "run_catchments"},
	run_id = {base = {table = "run_catchments", name = "run_id", type_id = i64}},
	comid = {base = {table = "run_catchments", name = "comid", type_id = i64}},
}

RunResults := struct {
	_info: sb.Table_Info,
	run_id: sb.Column(string),
	comid: sb.Column(i64),
	date: sb.Column(time.Time),
	flow: sb.Column(f64),
	flowin: sb.Column(f64),
	flowout: sb.Column(f64),
	runoff: sb.Column(f64),
	water_runoff: sb.Column(f64),
	temp: sb.Column(f64),
	precip: sb.Column(f64),
	et: sb.Column(f64),
	pet: sb.Column(f64),
	deep_seepage: sb.Column(f64),
	unsat_stor: sb.Column(f64),
	sat_stor: sb.Column(f64),
	generated_sediment: sb.Column(f64),
	routed_sediment: sb.Column(f64),
	gw_sediment: sb.Column(f64),
	generated_nitrogen: sb.Column(f64),
	routed_nitrogen: sb.Column(f64),
	septic_nitrogen: sb.Column(f64),
	gw_nitrogen: sb.Column(f64),
	generated_phosphorus: sb.Column(f64),
	routed_phosphorus: sb.Column(f64),
	gw_phosphorus: sb.Column(f64),
}{
	_info = {name = "run_results"},
	run_id = {base = {table = "run_results", name = "run_id", type_id = string}},
	comid = {base = {table = "run_results", name = "comid", type_id = i64}},
	date = {base = {table = "run_results", name = "date", type_id = time.Time}},
	flow = {base = {table = "run_results", name = "flow", type_id = f64, nullable = true}},
	flowin = {base = {table = "run_results", name = "flowin", type_id = f64, nullable = true}},
	flowout = {base = {table = "run_results", name = "flowout", type_id = f64, nullable = true}},
	runoff = {base = {table = "run_results", name = "runoff", type_id = f64, nullable = true}},
	water_runoff = {base = {table = "run_results", name = "water_runoff", type_id = f64, nullable = true}},
	temp = {base = {table = "run_results", name = "temp", type_id = f64, nullable = true}},
	precip = {base = {table = "run_results", name = "precip", type_id = f64, nullable = true}},
	et = {base = {table = "run_results", name = "et", type_id = f64, nullable = true}},
	pet = {base = {table = "run_results", name = "pet", type_id = f64, nullable = true}},
	deep_seepage = {base = {table = "run_results", name = "deep_seepage", type_id = f64, nullable = true}},
	unsat_stor = {base = {table = "run_results", name = "unsat_stor", type_id = f64, nullable = true}},
	sat_stor = {base = {table = "run_results", name = "sat_stor", type_id = f64, nullable = true}},
	generated_sediment = {base = {table = "run_results", name = "generated_sediment", type_id = f64, nullable = true}},
	routed_sediment = {base = {table = "run_results", name = "routed_sediment", type_id = f64, nullable = true}},
	gw_sediment = {base = {table = "run_results", name = "gw_sediment", type_id = f64, nullable = true}},
	generated_nitrogen = {base = {table = "run_results", name = "generated_nitrogen", type_id = f64, nullable = true}},
	routed_nitrogen = {base = {table = "run_results", name = "routed_nitrogen", type_id = f64, nullable = true}},
	septic_nitrogen = {base = {table = "run_results", name = "septic_nitrogen", type_id = f64, nullable = true}},
	gw_nitrogen = {base = {table = "run_results", name = "gw_nitrogen", type_id = f64, nullable = true}},
	generated_phosphorus = {base = {table = "run_results", name = "generated_phosphorus", type_id = f64, nullable = true}},
	routed_phosphorus = {base = {table = "run_results", name = "routed_phosphorus", type_id = f64, nullable = true}},
	gw_phosphorus = {base = {table = "run_results", name = "gw_phosphorus", type_id = f64, nullable = true}},
}

Runs := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	uid: sb.Column(string),
	name: sb.Column(string),
	start_date: sb.Column(time.Time),
	end_date: sb.Column(time.Time),
	outlet: sb.Column(i64),
	hydro_source_id: sb.Column(i64),
	land_source_id: sb.Column(i64),
	met_source_id: sb.Column(i64),
	run_config: sb.Column(string),
	ran_at: sb.Column(time.Time),
}{
	_info = {name = "runs"},
	id = {base = {table = "runs", name = "id", type_id = i64}},
	uid = {base = {table = "runs", name = "uid", type_id = string}},
	name = {base = {table = "runs", name = "name", type_id = string}},
	start_date = {base = {table = "runs", name = "start_date", type_id = time.Time}},
	end_date = {base = {table = "runs", name = "end_date", type_id = time.Time}},
	outlet = {base = {table = "runs", name = "outlet", type_id = i64}},
	hydro_source_id = {base = {table = "runs", name = "hydro_source_id", type_id = i64}},
	land_source_id = {base = {table = "runs", name = "land_source_id", type_id = i64}},
	met_source_id = {base = {table = "runs", name = "met_source_id", type_id = i64}},
	run_config = {base = {table = "runs", name = "run_config", type_id = string, nullable = true}},
	ran_at = {base = {table = "runs", name = "ran_at", type_id = time.Time, nullable = true}},
}

SourceTypes := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	name: sb.Column(string),
}{
	_info = {name = "source_types"},
	id = {base = {table = "source_types", name = "id", type_id = i64}},
	name = {base = {table = "source_types", name = "name", type_id = string}},
}

Sources := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	source_type_id: sb.Column(i64),
	name: sb.Column(string),
}{
	_info = {name = "sources"},
	id = {base = {table = "sources", name = "id", type_id = i64}},
	source_type_id = {base = {table = "sources", name = "source_type_id", type_id = i64}},
	name = {base = {table = "sources", name = "name", type_id = string}},
}

