// migragen — embed a directory of `.sql` migration files into a generated
// Odin source file, so an application can ship its migrations inside the
// binary instead of reading them from disk at runtime.
//
// Usage:
//   odin run tools/migragen -- <sql-dir> <out-dir> [-package=<name>] [-var=<NAME>]
//
//   <sql-dir>   directory of <version>_<name>.up.sql / .down.sql files
//   <out-dir>   package directory to write <out-dir>/migrations.gen.odin into
//   -package=   package name for the generated file (default: inferred from
//               <out-dir>, falling back to its basename)
//   -var=       name of the generated slice (default: MIGRATIONS)
//
// The emitted file declares, e.g.:
//
//   MIGRATIONS := []migrate.Migration{
//       {version = 20260101090000, name = "create_users", up = "...", down = "..."},
//   }
//
// which you pass straight to the runner: `migrate.up(db, MIGRATIONS)`. migragen
// reuses migrate.from_dir for parsing/validation, so the same file-name rules
// (and errors) apply — it is simply from_dir plus an Odin emitter.
package migragen

import "core:flags"
import "core:fmt"
import "core:odin/parser"
import "core:os"
import "core:path/filepath"
import "core:strings"

import migrate "database:migrate"

// Options is the migragen command line, parsed declaratively by core:flags.
Options :: struct {
	sql_dir:  string `args:"pos=0,required" usage:"directory of <version>_<name>.up.sql / .down.sql files"`,
	out_dir:  string `args:"pos=1,required" usage:"package directory to write migrations.gen.odin into"`,
	pkg:      string `args:"name=package"   usage:"package name for the generated file (default: inferred from out-dir)"`,
	var_name: string `args:"name=var"       usage:"name of the generated slice (default: MIGRATIONS)"`,
}

// run parses args and embeds the migrations, returning a process exit code.
// `prog` is the program name shown in usage ("migragen" standalone,
// "odb migrate-gen" under the unified CLI). Exposed for the `odb` dispatcher.
run :: proc(prog: string, args: []string) -> int {
	opt := Options {
		var_name = "MIGRATIONS", // default; overwritten only if -var is given
	}
	program_args := make([]string, len(args) + 1, context.temp_allocator)
	program_args[0] = prog
	copy(program_args[1:], args)
	flags.parse_or_exit(&opt, program_args, .Unix) // accepts `-flag value` and `-flag=value`; handles -h/usage/errors

	migs, err := migrate.from_dir(opt.sql_dir)
	if err != nil {
		fmt.eprintfln("migragen: load %s: %v", opt.sql_dir, err)
		return 1
	}
	defer migrate.destroy_migrations(migs)

	pkg_name := opt.pkg
	if pkg_name == "" {
		pkg_name = infer_package_name(opt.out_dir)
	}

	src := emit(pkg_name, opt.var_name, migs)
	out, _ := filepath.join({opt.out_dir, "migrations.gen.odin"}, context.allocator)
	if werr := os.write_entire_file(out, transmute([]u8)src); werr != nil {
		fmt.eprintfln("migragen: write %s: %v", out, werr)
		return 1
	}
	fmt.printfln("migragen: wrote %s (%d migration(s))", out, len(migs))
	return 0
}

main :: proc() {
	os.exit(run(os.args[0], os.args[1:]))
}

// infer_package_name reads the package declaration of any .odin file already in
// out_dir; if there are none (or it can't be parsed) it falls back to the
// directory's basename.
infer_package_name :: proc(dir: string) -> string {
	if pkg, ok := parser.parse_package_from_path(dir); ok {
		for _, f in pkg.files {
			if f.pkg_decl != nil && f.pkg_decl.name != "" {
				return f.pkg_decl.name
			}
		}
	}
	return filepath.base(dir)
}

emit :: proc(pkg_name, var_name: string, migs: []migrate.Migration) -> string {
	b := strings.builder_make()
	w := strings.write_string

	w(&b, "// Code generated by tools/migragen. DO NOT EDIT.\n")
	w(&b, "package ")
	w(&b, pkg_name)
	w(&b, "\n\n")
	w(&b, "import migrate \"database:migrate\"\n\n")

	w(&b, var_name)
	w(&b, " := []migrate.Migration{\n")
	for m in migs {
		w(&b, "\t{\n")
		fmt.sbprintf(&b, "\t\tversion = %d,\n", m.version)
		w(&b, "\t\tname    = ")
		emit_string(&b, m.name)
		w(&b, ",\n")
		w(&b, "\t\tup      = ")
		emit_string(&b, m.up)
		w(&b, ",\n")
		w(&b, "\t\tdown    = ")
		emit_string(&b, m.down)
		w(&b, ",\n")
		w(&b, "\t},\n")
	}
	w(&b, "}\n")
	return strings.to_string(b)
}

// emit_string writes s as a double-quoted Odin string literal, escaping the
// characters that would otherwise break the literal. Iterating bytes is fine —
// UTF-8 continuation bytes pass through unchanged inside a quoted literal.
emit_string :: proc(b: ^strings.Builder, s: string) {
	strings.write_byte(b, '"')
	for i in 0 ..< len(s) {
		switch c := s[i]; c {
		case '"':
			strings.write_string(b, "\\\"")
		case '\\':
			strings.write_string(b, "\\\\")
		case '\n':
			strings.write_string(b, "\\n")
		case '\r':
			strings.write_string(b, "\\r")
		case '\t':
			strings.write_string(b, "\\t")
		case:
			strings.write_byte(b, c)
		}
	}
	strings.write_byte(b, '"')
}
