// migragen — embed a directory of `.sql` migration files into a generated
// Odin source file, so an application can ship its migrations inside the
// binary instead of reading them from disk at runtime.
//
// Usage:
//   odin run tools/migragen -- <sql-dir> <out-dir> [-package=<name>] [-var=<NAME>]
//
//   <sql-dir>   directory of <version>_<name>.up.sql / .down.sql files
//   <out-dir>   package directory to write <out-dir>/migrations.gen.odin into
//   -package=   package name for the generated file (default: inferred from
//               <out-dir>, falling back to its basename)
//   -var=       name of the generated slice (default: MIGRATIONS)
//
// The emitted file declares, e.g.:
//
//   MIGRATIONS := []migrate.Migration{
//       {version = 20260101090000, name = "create_users", up = "...", down = "..."},
//   }
//
// which you pass straight to the runner: `migrate.up(db, MIGRATIONS)`. migragen
// reuses migrate.from_dir for parsing/validation, so the same file-name rules
// (and errors) apply — it is simply from_dir plus an Odin emitter.
package migragen

import "core:fmt"
import "core:odin/parser"
import "core:os"
import "core:path/filepath"
import "core:strings"

import migrate "database:migrate"

main :: proc() {
	sql_dir, out_dir, pkg_override, var_name := parse_args()

	migs, err := migrate.from_dir(sql_dir)
	if err != nil {
		fmt.eprintfln("migragen: load %s: %v", sql_dir, err)
		os.exit(1)
	}
	defer migrate.destroy_migrations(migs)

	pkg_name := pkg_override
	if pkg_name == "" {
		pkg_name = infer_package_name(out_dir)
	}

	src := emit(pkg_name, var_name, migs)
	out, _ := filepath.join({out_dir, "migrations.gen.odin"}, context.allocator)
	if werr := os.write_entire_file(out, transmute([]u8)src); werr != nil {
		fmt.eprintfln("migragen: write %s: %v", out, werr)
		os.exit(1)
	}
	fmt.printfln("migragen: wrote %s (%d migration(s))", out, len(migs))
}

parse_args :: proc() -> (sql_dir, out_dir, pkg, var_name: string) {
	var_name = "MIGRATIONS"
	positional: [dynamic]string
	defer delete(positional)

	for arg in os.args[1:] {
		switch {
		case strings.has_prefix(arg, "-package="):
			pkg = arg[len("-package="):]
		case strings.has_prefix(arg, "-var="):
			var_name = arg[len("-var="):]
		case:
			append(&positional, arg)
		}
	}

	if len(positional) != 2 {
		fmt.eprintln("usage: migragen <sql-dir> <out-dir> [-package=<name>] [-var=<NAME>]")
		os.exit(2)
	}
	return positional[0], positional[1], pkg, var_name
}

// infer_package_name reads the package declaration of any .odin file already in
// out_dir; if there are none (or it can't be parsed) it falls back to the
// directory's basename.
infer_package_name :: proc(dir: string) -> string {
	if pkg, ok := parser.parse_package_from_path(dir); ok {
		for _, f in pkg.files {
			if f.pkg_decl != nil && f.pkg_decl.name != "" {
				return f.pkg_decl.name
			}
		}
	}
	return filepath.base(dir)
}

emit :: proc(pkg_name, var_name: string, migs: []migrate.Migration) -> string {
	b := strings.builder_make()
	w := strings.write_string

	w(&b, "// Code generated by tools/migragen. DO NOT EDIT.\n")
	w(&b, "package ")
	w(&b, pkg_name)
	w(&b, "\n\n")
	w(&b, "import migrate \"database:migrate\"\n\n")

	w(&b, var_name)
	w(&b, " := []migrate.Migration{\n")
	for m in migs {
		w(&b, "\t{\n")
		fmt.sbprintf(&b, "\t\tversion = %d,\n", m.version)
		w(&b, "\t\tname    = ")
		emit_string(&b, m.name)
		w(&b, ",\n")
		w(&b, "\t\tup      = ")
		emit_string(&b, m.up)
		w(&b, ",\n")
		w(&b, "\t\tdown    = ")
		emit_string(&b, m.down)
		w(&b, ",\n")
		w(&b, "\t},\n")
	}
	w(&b, "}\n")
	return strings.to_string(b)
}

// emit_string writes s as a double-quoted Odin string literal, escaping the
// characters that would otherwise break the literal. Iterating bytes is fine —
// UTF-8 continuation bytes pass through unchanged inside a quoted literal.
emit_string :: proc(b: ^strings.Builder, s: string) {
	strings.write_byte(b, '"')
	for i in 0 ..< len(s) {
		switch c := s[i]; c {
		case '"':
			strings.write_string(b, "\\\"")
		case '\\':
			strings.write_string(b, "\\\\")
		case '\n':
			strings.write_string(b, "\\n")
		case '\r':
			strings.write_string(b, "\\r")
		case '\t':
			strings.write_string(b, "\\t")
		case:
			strings.write_byte(b, c)
		}
	}
	strings.write_byte(b, '"')
}
