// introspection — demonstrates schemagen's DB front-end.
//
// schema.gen.odin in this package is generated by introspecting a real SQLite
// database (see schema.sql). The database is the single source of truth for
// BOTH the row structs (`User`, `Post`) used when scanning and the query
// descriptors (`Users`, `Posts`) used to build typed queries. Nullable columns
// become `Maybe(T)` fields.
//
// Regenerate with `just gen-introspection` after editing schema.sql.
package introspection

import "core:fmt"

import sqlite "database:drivers/sqlite"
import sql "database:sql"
import sb "database:sqlbuilder"

main :: proc() {
	db, err := sql.open(&sqlite.driver, ":memory:")
	if err != nil {fmt.eprintfln("open: %v", err);return}
	defer sql.close(db)

	// A live schema matching schema.sql, so the introspected descriptors and
	// structs line up with the running database.
	_, err = sql.exec(
		db,
		"CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email VARCHAR(255), age INTEGER, rating REAL, avatar BLOB, created_at DATETIME)",
	)
	if err != nil {fmt.eprintfln("create: %v", err);return}

	_, err = sql.exec(
		db,
		"INSERT INTO users (name, email, age, rating) VALUES (?, ?, ?, ?)",
		"Alice",
		"alice@example.com",
		i64(30),
		f64(4.5),
	)
	if err != nil {fmt.eprintfln("insert: %v", err);return}

	// Build a typed query against the introspected `Users` descriptor.
	b: sb.Builder
	sb.init(&b)
	defer sb.destroy(&b)

	sb.select(&b, Users.id, Users.name, Users.email, Users.age, Users.rating)
	sb.from(&b, Users)
	sb.where_(&b, sb.ge(Users.age, 18))
	sb.order_by(&b, sb.asc(Users.name))

	q, args := sb.to_query(&b)
	fmt.printfln("sql: %s", q)

	rows, qerr := sql.query(db, q, ..args)
	if qerr != nil {fmt.eprintfln("query: %v", qerr);return}
	defer sql.rows_close(&rows)

	for sql.next(&rows) {
		u: User // the introspected row struct (singular name)
		if serr := scan(&rows, &u); serr != nil { 	// concrete scanner from scangen
			fmt.eprintfln("scan: %v", serr)
			return
		}
		// email is nullable, so it scans into a Maybe(string).
		email := u.email.? or_else "(null)"
		fmt.printfln(
			"  id=%v  name=%v  email=%v  age=%v  rating=%v",
			u.id,
			u.name,
			email,
			u.age,
			u.rating,
		)
	}
	// next() returns false for both a clean end-of-rows and a mid-stream
	// failure; rows_err disambiguates them (nil = fully consumed).
	if rerr := sql.rows_err(&rows); rerr != nil {
		fmt.eprintfln("rows: %v", rerr)
		return
	}
}
