// Code generated by tools/scangen. DO NOT EDIT.
package introspection

import "core:strings"
import "core:time"
import sql "database:sql"

scan_Post :: proc(rows: ^sql.Rows, dest: ^Post) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "user_id":
			if v, ok := val.(i64); ok { dest.user_id = i64(v) }
		case "title":
			if v, ok := val.(string); ok {
				dest.title = v if detached else strings.clone(v)
			}
		case "published_at":
			if v, ok := val.(time.Time); ok { dest.published_at = v }
		}
	}
	return nil
}

scan_User :: proc(rows: ^sql.Rows, dest: ^User) -> sql.Error {
	if !rows.has_row {
		return sql.Scan_Error{kind = .No_Row, col_idx = -1}
	}
	detached := sql.row_detached(rows)
	_ = detached
	for ci in 0 ..< rows.col_count {
		name := sql.row_col_name(rows, ci)
		val  := sql.row_value(rows, ci)
		_ = val
		switch name {
		case "id":
			if v, ok := val.(i64); ok { dest.id = i64(v) }
		case "name":
			if v, ok := val.(string); ok {
				dest.name = v if detached else strings.clone(v)
			}
		case "email":
			if v, ok := val.(string); ok {
				dest.email = v if detached else strings.clone(v)
			}
		case "age":
			if v, ok := val.(i64); ok { dest.age = i64(v) }
		case "rating":
			#partial switch v in val {
			case f64: dest.rating = v
			case i64: dest.rating = f64(v)
			}
		case "avatar":
			if v, ok := val.([]byte); ok {
				if detached {
					dest.avatar = v
				} else {
					cp := make([]byte, len(v)); copy(cp, v); dest.avatar = cp
				}
			}
		case "created_at":
			if v, ok := val.(time.Time); ok { dest.created_at = v }
		}
	}
	return nil
}

scan :: proc{
	scan_Post,
	scan_User,
	sql.scan_struct,
	sql.scan_values,
	sql.row_scan_struct,
	sql.row_scan_values,
}
