// Code generated by tools/schemagen. DO NOT EDIT.
package introspection

import "core:time"
import sb "database:sqlbuilder"

//+sql:scan
Post :: struct {
	id: i64,
	user_id: Maybe(i64),
	title: Maybe(string),
	published_at: Maybe(time.Time),
}

//+sql:scan
User :: struct {
	id: i64,
	name: string,
	email: Maybe(string),
	age: Maybe(i64),
	rating: Maybe(f64),
	avatar: Maybe([]byte),
	created_at: Maybe(time.Time),
}

Posts := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	user_id: sb.Column(i64),
	title: sb.Column(string),
	published_at: sb.Column(time.Time),
}{
	_info = {name = "posts"},
	id = {base = {table = "posts", name = "id", type_id = i64}},
	user_id = {base = {table = "posts", name = "user_id", type_id = i64, nullable = true}},
	title = {base = {table = "posts", name = "title", type_id = string, nullable = true}},
	published_at = {base = {table = "posts", name = "published_at", type_id = time.Time, nullable = true}},
}

Users := struct {
	_info: sb.Table_Info,
	id: sb.Column(i64),
	name: sb.Column(string),
	email: sb.Column(string),
	age: sb.Column(i64),
	rating: sb.Column(f64),
	avatar: sb.Column([]byte),
	created_at: sb.Column(time.Time),
}{
	_info = {name = "users"},
	id = {base = {table = "users", name = "id", type_id = i64}},
	name = {base = {table = "users", name = "name", type_id = string}},
	email = {base = {table = "users", name = "email", type_id = string, nullable = true}},
	age = {base = {table = "users", name = "age", type_id = i64, nullable = true}},
	rating = {base = {table = "users", name = "rating", type_id = f64, nullable = true}},
	avatar = {base = {table = "users", name = "avatar", type_id = []byte, nullable = true}},
	created_at = {base = {table = "users", name = "created_at", type_id = time.Time, nullable = true}},
}

